/**
 * This file is generated by dvorak_keydata_gen.py
 * Do not edit this file directly.
 */
#pragma once

#include "dvorak.h"

struct dvorak_node;

typedef struct dvorak_node dvorak_node_t;

struct dvorak_node {
  const dvorak_node_t *parent;                      // 4 bytes
  const dvorak_node_t *(*next_node)(uint16_t key);  // 4 bytes
  const uint16_t key;
  const uint8_t bounds;  //  First 4 bits: modifier, Last 4 bits: keycode
                         //  bounds & 0xF0: Enter event end of the string
                         //  bounds & 0x0F: Exit event end of the string
  const uint8_t keys[];
};

const dvorak_node_t dvorak_node_root;
