#pragma once
// EEPROMに保存する設定

enum combo_events {  //
  DVO_TO_NAGI_COMBO,
  DVO_NULL_COMBO,
  NAGI_TO_DVO,
  VIM_DVO_TO_NAGI_COMBO,
  VIM_DVO_NULL_COMBO,
  VIM_NAGI_TO_DVO,
  ONESHOT_MEH_R,
  ONESHOT_MEH_L,
  ONESHOT_HYPER_R,
  ONESHOT_HYPER_L,
  ONESHOT_LCAG_R,
  ONESHOT_LCAG_L,
  COMBO_LENGTH
};
