#pragma once

#define MASTER_LEFT

#define HOLD_ON_OTHER_KEY_PRESS
#define TAPPING_FORCE_HOLD

#undef RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 200

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

#define OLED_TIMEOUT 5000
#define OLED_FADE_OUT_INTERVAL 1
#define OLED_FADE_OUT
#define OLED_UPDATE_INTERVAL 30

// Firmware のサイズ削減用のオプション
// #define NO_ACTION_TAPPING
// #define NO_ACTION_ONESHOT
#define LAYER_STATE_8BIT
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define IS_RIGHT
// #define RETRO_TAPPING
#define PERMISSIVE_HOLD
#define TAPPING_TERM 170

#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define ENABLE_RGB_MATRIX_RAINDROPS
#define ENABLE_RGB_MATRIX_PIXEL_RAIN
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_MULTISPLASH

enum layer_number {
    L_DVORAK,
    L_NAGINATA,
    L_RAISE,
    L_ADJUST,
    L_MODIFIER,
    L_LOWER,
    L_GAME,
    L_GAME2,
};

// vim:set sw=4 ts=4 sts=4:
