/**
 * This file is generated by dvorak_keydata_gen.py
 * Do not edit this file directly.
 */
#include "dvorak_keydata_generated.h"

#define B_A (1ULL << (DV_A - DV_A))
#define B_B (1ULL << (DV_B - DV_A))
#define B_C (1ULL << (DV_C - DV_A))
#define B_D (1ULL << (DV_D - DV_A))
#define B_E (1ULL << (DV_E - DV_A))
#define B_F (1ULL << (DV_F - DV_A))
#define B_G (1ULL << (DV_G - DV_A))
#define B_H (1ULL << (DV_H - DV_A))
#define B_I (1ULL << (DV_I - DV_A))
#define B_J (1ULL << (DV_J - DV_A))
#define B_K (1ULL << (DV_K - DV_A))
#define B_L (1ULL << (DV_L - DV_A))
#define B_M (1ULL << (DV_M - DV_A))
#define B_N (1ULL << (DV_N - DV_A))
#define B_O (1ULL << (DV_O - DV_A))
#define B_P (1ULL << (DV_P - DV_A))
#define B_Q (1ULL << (DV_Q - DV_A))
#define B_R (1ULL << (DV_R - DV_A))
#define B_S (1ULL << (DV_S - DV_A))
#define B_T (1ULL << (DV_T - DV_A))
#define B_U (1ULL << (DV_U - DV_A))
#define B_V (1ULL << (DV_V - DV_A))
#define B_W (1ULL << (DV_W - DV_A))
#define B_X (1ULL << (DV_X - DV_A))
#define B_Y (1ULL << (DV_Y - DV_A))
#define B_Z (1ULL << (DV_Z - DV_A))

#define B_QUOT (1ULL << (DV_QUOT - DV_A))
#define B_COMM (1ULL << (DV_COMM - DV_A))
#define B_DOT (1ULL << (DV_DOT - DV_A))
#define B_SCLN (1ULL << (DV_SCLN - DV_A))
#define B_LS1 (1ULL << (DV_LSFT1 - DV_A))
#define B_RS1 (1ULL << (DV_RSFT1 - DV_A))
#define B_LS2 (1ULL << (DV_LSFT2 - DV_A))
#define B_RS2 (1ULL << (DV_RSFT2 - DV_A))
#define B_LS3 (1ULL << (DV_LSFT2 - DV_A))
#define B_RS3 (1ULL << (DV_RSFT2 - DV_A))

const PROGMEM dvorak_keymap dvmap_generated[DVORAK_KEY_NUMBER_GENERATED] = {
{.key = B_QUOT, .val = "'"},
{.key = B_COMM, .val = ","},
{.key = B_DOT, .val = "."},
{.key = B_P, .val = "p"},
{.key = B_Y, .val = "y"},
{.key = B_F, .val = "f"},
{.key = B_G, .val = "g"},
{.key = B_C, .val = "c"},
{.key = B_R, .val = "r"},
{.key = B_L, .val = "l"},
{.key = B_A, .val = "a"},
{.key = B_O, .val = "o"},
{.key = B_E, .val = "e"},
{.key = B_U, .val = "u"},
{.key = B_I, .val = "i"},
{.key = B_D, .val = "d"},
{.key = B_H, .val = "h"},
{.key = B_T, .val = "t"},
{.key = B_N, .val = "n"},
{.key = B_S, .val = "s"},
{.key = B_SCLN, .val = ";"},
{.key = B_Q, .val = "q"},
{.key = B_J, .val = "j"},
{.key = B_K, .val = "k"},
{.key = B_X, .val = "x"},
{.key = B_B, .val = "b"},
{.key = B_M, .val = "m"},
{.key = B_W, .val = "w"},
{.key = B_V, .val = "v"},
{.key = B_Z, .val = "z"},
{.key = B_LS2, .val = " "},
{.key = B_LS3, .val = "hey"},
{.key = B_RS2, .val = SS_TAP(X_ENT)},
{.key = B_QUOT | B_RS2, .val = "\""},
{.key = B_COMM | B_RS2, .val = "<"},
{.key = B_DOT | B_RS2, .val = ">"},
{.key = B_P | B_RS2, .val = "P"},
{.key = B_Y | B_RS2, .val = "Y"},
{.key = B_F | B_RS2, .val = "F"},
{.key = B_G | B_RS2, .val = "G"},
{.key = B_C | B_RS2, .val = "C"},
{.key = B_R | B_RS2, .val = "R"},
{.key = B_L | B_RS2, .val = "L"},
{.key = B_A | B_RS2, .val = "A"},
{.key = B_O | B_RS2, .val = "O"},
{.key = B_E | B_RS2, .val = "E"},
{.key = B_U | B_RS2, .val = "U"},
{.key = B_I | B_RS2, .val = "I"},
{.key = B_D | B_RS2, .val = "D"},
{.key = B_H | B_RS2, .val = "H"},
{.key = B_T | B_RS2, .val = "T"},
{.key = B_N | B_RS2, .val = "N"},
{.key = B_S | B_RS2, .val = "S"},
{.key = B_SCLN | B_RS2, .val = ":"},
{.key = B_Q | B_RS2, .val = "Q"},
{.key = B_J | B_RS2, .val = "J"},
{.key = B_K | B_RS2, .val = "K"},
{.key = B_X | B_RS2, .val = "X"},
{.key = B_B | B_RS2, .val = "B"},
{.key = B_M | B_RS2, .val = "M"},
{.key = B_W | B_RS2, .val = "W"},
{.key = B_V | B_RS2, .val = "V"},
{.key = B_Z | B_RS2, .val = "Z"},
{.key = B_QUOT | B_LS2, .val = SS_LCTL("'")},
{.key = B_COMM | B_LS2, .val = SS_LCTL(",")},
{.key = B_DOT | B_LS2, .val = SS_LCTL(".")},
{.key = B_P | B_LS2, .val = SS_LCTL("p")},
{.key = B_Y | B_LS2, .val = SS_LCTL("y")},
{.key = B_F | B_LS2, .val = SS_LCTL("f")},
{.key = B_G | B_LS2, .val = SS_LCTL("g")},
{.key = B_C | B_LS2, .val = SS_LCTL("c")},
{.key = B_R | B_LS2, .val = SS_LCTL("r")},
{.key = B_L | B_LS2, .val = SS_LCTL("l")},
{.key = B_A | B_LS2, .val = SS_LCTL("a")},
{.key = B_O | B_LS2, .val = SS_LCTL("o")},
{.key = B_E | B_LS2, .val = SS_LCTL("e")},
{.key = B_U | B_LS2, .val = SS_LCTL("u")},
{.key = B_I | B_LS2, .val = SS_LCTL("i")},
{.key = B_D | B_LS2, .val = SS_LCTL("d")},
{.key = B_H | B_LS2, .val = SS_LCTL("h")},
{.key = B_T | B_LS2, .val = SS_LCTL("t")},
{.key = B_N | B_LS2, .val = SS_LCTL("n")},
{.key = B_S | B_LS2, .val = SS_LCTL("s")},
{.key = B_SCLN | B_LS2, .val = SS_LCTL(";")},
{.key = B_Q | B_LS2, .val = SS_LCTL("q")},
{.key = B_J | B_LS2, .val = SS_LCTL("j")},
{.key = B_K | B_LS2, .val = SS_LCTL("k")},
{.key = B_X | B_LS2, .val = SS_LCTL("x")},
{.key = B_B | B_LS2, .val = SS_LCTL("b")},
{.key = B_M | B_LS2, .val = SS_LCTL("m")},
{.key = B_W | B_LS2, .val = SS_LCTL("w")},
{.key = B_V | B_LS2, .val = SS_LCTL("v")},
{.key = B_Z | B_LS2, .val = SS_LCTL("z")},
{.key = B_QUOT | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("'"))},
{.key = B_COMM | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL(","))},
{.key = B_DOT | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("."))},
{.key = B_P | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("p"))},
{.key = B_Y | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("y"))},
{.key = B_F | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("f"))},
{.key = B_G | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("g"))},
{.key = B_C | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("c"))},
{.key = B_R | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("r"))},
{.key = B_L | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("l"))},
{.key = B_A | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("a"))},
{.key = B_O | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("o"))},
{.key = B_E | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("e"))},
{.key = B_U | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("u"))},
{.key = B_I | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("i"))},
{.key = B_D | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("d"))},
{.key = B_H | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("h"))},
{.key = B_T | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("t"))},
{.key = B_N | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("n"))},
{.key = B_S | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("s"))},
{.key = B_SCLN | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL(";"))},
{.key = B_Q | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("q"))},
{.key = B_J | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("j"))},
{.key = B_K | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("k"))},
{.key = B_X | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("x"))},
{.key = B_B | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("b"))},
{.key = B_M | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("m"))},
{.key = B_W | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("w"))},
{.key = B_V | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("v"))},
{.key = B_Z | B_LS2 | B_RS2, .val = SS_LSFT(SS_LCTL("z"))},
{.key = B_F | B_U, .val = "]"},
{.key = B_G | B_U, .val = ")"},
{.key = B_C | B_U, .val = "}"},
{.key = B_R | B_U, .val = "$"},
{.key = B_L | B_U, .val = "!"},
{.key = B_D | B_U, .val = "_"},
{.key = B_N | B_U, .val = "^"},
{.key = B_S | B_U, .val = "~"},
{.key = B_B | B_U, .val = "-"},
{.key = B_M | B_U, .val = "@"},
{.key = B_W | B_U, .val = "?"},
{.key = B_V | B_U, .val = "*"},
{.key = B_QUOT | B_H, .val = "`"},
{.key = B_COMM | B_H, .val = "%"},
{.key = B_DOT | B_H, .val = "{"},
{.key = B_P | B_H, .val = "("},
{.key = B_Y | B_H, .val = "["},
{.key = B_A | B_H, .val = "#"},
{.key = B_O | B_H, .val = "/"},
{.key = B_I | B_H, .val = "|"},
{.key = B_Q | B_H, .val = "\\"},
{.key = B_J | B_H, .val = "&"},
{.key = B_K | B_H, .val = "="},
{.key = B_X | B_H, .val = "+"},
{.key = B_QUOT | B_T, .val = "1"},
{.key = B_COMM | B_T, .val = "2"},
{.key = B_DOT | B_T, .val = "3"},
{.key = B_P | B_T, .val = "4"},
{.key = B_Y | B_T, .val = "5"},
{.key = B_F | B_T, .val = "6"},
{.key = B_G | B_T, .val = "7"},
{.key = B_C | B_T, .val = "8"},
{.key = B_R | B_T, .val = "9"},
{.key = B_L | B_T, .val = "0"},
{.key = B_QUOT | B_E, .val = "1"},
{.key = B_COMM | B_E, .val = "2"},
{.key = B_DOT | B_E, .val = "3"},
{.key = B_P | B_E, .val = "4"},
{.key = B_Y | B_E, .val = "5"},
{.key = B_F | B_E, .val = "6"},
{.key = B_G | B_E, .val = "7"},
{.key = B_C | B_E, .val = "8"},
{.key = B_R | B_E, .val = "9"},
{.key = B_L | B_E, .val = "0"},
};
