/**
 * This file is generated by dvorak_keydata_gen.py
 * Do not edit this file directly.
 */
#pragma once

#include "dvorak.h"

struct dvorak_node;

typedef struct dvorak_node dvorak_node_t;

struct dvorak_node {
    const dvorak_node_t* parent;
    int16_t                key;
    const char*            value;
    bool                   reverse;
    const dvorak_node_t* (*next_node)(uint16_t key);
    const dvorak_node_t* (*prev_node)(uint16_t key);
};

const dvorak_node_t dvorak_node_root;
