/**
 * This file is generated by dvorak_keydata_gen.py
 * Do not edit this file directly.
 */
#pragma once

#include "dvorak.h"

struct dv_node;

typedef struct dv_node dv_node_t;

struct dv_node {
    const dv_node_t*  parent;
    const dv_node_t** children;
    uint8_t           children_num;
    int8_t            key;
    const char*       value;
};

const PROGMEM dv_node_t dvnode_root;
