/**
 * This file is generated by code generator
 * Do not edit this file directly.
 */
#include "dvorak_keydata.h"

const dvorak_node_t dvorak_node_root;
const dvorak_node_t dvorak_node_DV_QUOT;
const dvorak_node_t dvorak_node_DV_COMM;
const dvorak_node_t dvorak_node_DV_COMM_DV_DOT;
const dvorak_node_t dvorak_node_DV_DOT;
const dvorak_node_t dvorak_node_DV_DOT_DV_COMM;
const dvorak_node_t dvorak_node_DV_P;
const dvorak_node_t dvorak_node_DV_Y;
const dvorak_node_t dvorak_node_DV_F;
const dvorak_node_t dvorak_node_DV_G;
const dvorak_node_t dvorak_node_DV_C;
const dvorak_node_t dvorak_node_DV_R;
const dvorak_node_t dvorak_node_DV_L;
const dvorak_node_t dvorak_node_DV_A;
const dvorak_node_t dvorak_node_DV_O;
const dvorak_node_t dvorak_node_DV_E;
const dvorak_node_t dvorak_node_DV_U;
const dvorak_node_t dvorak_node_DV_I;
const dvorak_node_t dvorak_node_DV_D;
const dvorak_node_t dvorak_node_DV_H;
const dvorak_node_t dvorak_node_DV_T;
const dvorak_node_t dvorak_node_DV_N;
const dvorak_node_t dvorak_node_DV_S;
const dvorak_node_t dvorak_node_DV_SCLN;
const dvorak_node_t dvorak_node_DV_Q;
const dvorak_node_t dvorak_node_DV_J;
const dvorak_node_t dvorak_node_DV_K;
const dvorak_node_t dvorak_node_DV_X;
const dvorak_node_t dvorak_node_DV_B;
const dvorak_node_t dvorak_node_DV_M;
const dvorak_node_t dvorak_node_DV_W;
const dvorak_node_t dvorak_node_DV_V;
const dvorak_node_t dvorak_node_DV_Z;
const dvorak_node_t dvorak_node_DV_LSFT1;
const dvorak_node_t dvorak_node_DV_LSFT2;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_QUOT;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_COMM;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_DOT;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_P;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_Y;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_F;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_G;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_C;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_R;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_L;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_A;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_O;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_E;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_U;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_I;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_D;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_H;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_T;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_N;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_S;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_SCLN;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_Q;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_J;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_K;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_X;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_B;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_M;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_W;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_V;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_Z;
const dvorak_node_t dvorak_node_DV_LSFT2_DV_RSFT2;
const dvorak_node_t dvorak_node_DV_RSFT2;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_QUOT;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_COMM;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_DOT;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_P;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_Y;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_F;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_G;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_C;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_R;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_L;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_A;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_O;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_E;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_U;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_I;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_D;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_H;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_T;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_N;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_S;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_SCLN;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_Q;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_J;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_K;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_X;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_B;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_M;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_W;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_V;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_Z;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_LSFT1;
const dvorak_node_t dvorak_node_DV_RSFT2_DV_RSFT1;
const dvorak_node_t dvorak_node_DV_RSFT1;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_QUOT;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_COMM;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_DOT;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_P;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_Y;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_F;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_G;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_C;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_R;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_L;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_A;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_O;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_E;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_U;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_I;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_D;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_H;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_T;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_N;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_S;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_SCLN;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_Q;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_J;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_K;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_X;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_B;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_M;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_W;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_V;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_Z;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_LSFT1;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_LSFT2;
const dvorak_node_t dvorak_node_DV_RSFT1_DV_RSFT2;
const dvorak_node_t* dvorak_node_root_next_node(uint16_t key) {
  switch (key) {
    case DV_QUOT: return &dvorak_node_DV_QUOT;
    case DV_COMM: return &dvorak_node_DV_COMM;
    case DV_DOT: return &dvorak_node_DV_DOT;
    case DV_P: return &dvorak_node_DV_P;
    case DV_Y: return &dvorak_node_DV_Y;
    case DV_F: return &dvorak_node_DV_F;
    case DV_G: return &dvorak_node_DV_G;
    case DV_C: return &dvorak_node_DV_C;
    case DV_R: return &dvorak_node_DV_R;
    case DV_L: return &dvorak_node_DV_L;
    case DV_A: return &dvorak_node_DV_A;
    case DV_O: return &dvorak_node_DV_O;
    case DV_E: return &dvorak_node_DV_E;
    case DV_U: return &dvorak_node_DV_U;
    case DV_I: return &dvorak_node_DV_I;
    case DV_D: return &dvorak_node_DV_D;
    case DV_H: return &dvorak_node_DV_H;
    case DV_T: return &dvorak_node_DV_T;
    case DV_N: return &dvorak_node_DV_N;
    case DV_S: return &dvorak_node_DV_S;
    case DV_SCLN: return &dvorak_node_DV_SCLN;
    case DV_Q: return &dvorak_node_DV_Q;
    case DV_J: return &dvorak_node_DV_J;
    case DV_K: return &dvorak_node_DV_K;
    case DV_X: return &dvorak_node_DV_X;
    case DV_B: return &dvorak_node_DV_B;
    case DV_M: return &dvorak_node_DV_M;
    case DV_W: return &dvorak_node_DV_W;
    case DV_V: return &dvorak_node_DV_V;
    case DV_Z: return &dvorak_node_DV_Z;
    case DV_LSFT1: return &dvorak_node_DV_LSFT1;
    case DV_LSFT2: return &dvorak_node_DV_LSFT2;
    case DV_RSFT2: return &dvorak_node_DV_RSFT2;
    case DV_RSFT1: return &dvorak_node_DV_RSFT1;
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_root = {
  .parent       = NULL,
  .next_node    = &dvorak_node_root_next_node,
  .key          = -1,
  .bounds       = 0,
  .keys         = {},
};

const dvorak_node_t* dvorak_node_DV_QUOT_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_QUOT = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_QUOT_next_node,
  .key          = DV_QUOT,
  .bounds       = 1,
  .keys         = { KC_QUOT },
};

const dvorak_node_t* dvorak_node_DV_COMM_next_node(uint16_t key) {
  switch (key) {
    case DV_DOT: return &dvorak_node_DV_COMM_DV_DOT;
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_COMM = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_COMM_next_node,
  .key          = DV_COMM,
  .bounds       = 1,
  .keys         = { KC_COMM },
};

const dvorak_node_t* dvorak_node_DV_COMM_DV_DOT_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_COMM_DV_DOT = {
  .parent       = &dvorak_node_DV_COMM,
  .next_node    = &dvorak_node_DV_COMM_DV_DOT_next_node,
  .key          = DV_DOT,
  .bounds       = 1,
  .keys         = { KC_ESC },
};

const dvorak_node_t* dvorak_node_DV_DOT_next_node(uint16_t key) {
  switch (key) {
    case DV_COMM: return &dvorak_node_DV_DOT_DV_COMM;
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_DOT = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_DOT_next_node,
  .key          = DV_DOT,
  .bounds       = 1,
  .keys         = { KC_DOT },
};

const dvorak_node_t* dvorak_node_DV_DOT_DV_COMM_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_DOT_DV_COMM = {
  .parent       = &dvorak_node_DV_DOT,
  .next_node    = &dvorak_node_DV_DOT_DV_COMM_next_node,
  .key          = DV_COMM,
  .bounds       = 1,
  .keys         = { KC_ESC },
};

const dvorak_node_t* dvorak_node_DV_P_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_P = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_P_next_node,
  .key          = DV_P,
  .bounds       = 1,
  .keys         = { KC_P },
};

const dvorak_node_t* dvorak_node_DV_Y_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_Y = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_Y_next_node,
  .key          = DV_Y,
  .bounds       = 1,
  .keys         = { KC_Y },
};

const dvorak_node_t* dvorak_node_DV_F_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_F = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_F_next_node,
  .key          = DV_F,
  .bounds       = 1,
  .keys         = { KC_F },
};

const dvorak_node_t* dvorak_node_DV_G_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_G = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_G_next_node,
  .key          = DV_G,
  .bounds       = 1,
  .keys         = { KC_G },
};

const dvorak_node_t* dvorak_node_DV_C_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_C = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_C_next_node,
  .key          = DV_C,
  .bounds       = 1,
  .keys         = { KC_C },
};

const dvorak_node_t* dvorak_node_DV_R_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_R = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_R_next_node,
  .key          = DV_R,
  .bounds       = 1,
  .keys         = { KC_R },
};

const dvorak_node_t* dvorak_node_DV_L_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_L = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_L_next_node,
  .key          = DV_L,
  .bounds       = 1,
  .keys         = { KC_L },
};

const dvorak_node_t* dvorak_node_DV_A_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_A = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_A_next_node,
  .key          = DV_A,
  .bounds       = 1,
  .keys         = { KC_A },
};

const dvorak_node_t* dvorak_node_DV_O_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_O = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_O_next_node,
  .key          = DV_O,
  .bounds       = 1,
  .keys         = { KC_O },
};

const dvorak_node_t* dvorak_node_DV_E_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_E = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_E_next_node,
  .key          = DV_E,
  .bounds       = 1,
  .keys         = { KC_E },
};

const dvorak_node_t* dvorak_node_DV_U_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_U = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_U_next_node,
  .key          = DV_U,
  .bounds       = 1,
  .keys         = { KC_U },
};

const dvorak_node_t* dvorak_node_DV_I_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_I = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_I_next_node,
  .key          = DV_I,
  .bounds       = 1,
  .keys         = { KC_I },
};

const dvorak_node_t* dvorak_node_DV_D_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_D = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_D_next_node,
  .key          = DV_D,
  .bounds       = 1,
  .keys         = { KC_D },
};

const dvorak_node_t* dvorak_node_DV_H_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_H = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_H_next_node,
  .key          = DV_H,
  .bounds       = 1,
  .keys         = { KC_H },
};

const dvorak_node_t* dvorak_node_DV_T_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_T = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_T_next_node,
  .key          = DV_T,
  .bounds       = 1,
  .keys         = { KC_T },
};

const dvorak_node_t* dvorak_node_DV_N_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_N = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_N_next_node,
  .key          = DV_N,
  .bounds       = 1,
  .keys         = { KC_N },
};

const dvorak_node_t* dvorak_node_DV_S_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_S = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_S_next_node,
  .key          = DV_S,
  .bounds       = 1,
  .keys         = { KC_S },
};

const dvorak_node_t* dvorak_node_DV_SCLN_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_SCLN = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_SCLN_next_node,
  .key          = DV_SCLN,
  .bounds       = 1,
  .keys         = { KC_SCLN },
};

const dvorak_node_t* dvorak_node_DV_Q_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_Q = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_Q_next_node,
  .key          = DV_Q,
  .bounds       = 1,
  .keys         = { KC_Q },
};

const dvorak_node_t* dvorak_node_DV_J_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_J = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_J_next_node,
  .key          = DV_J,
  .bounds       = 1,
  .keys         = { KC_J },
};

const dvorak_node_t* dvorak_node_DV_K_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_K = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_K_next_node,
  .key          = DV_K,
  .bounds       = 1,
  .keys         = { KC_K },
};

const dvorak_node_t* dvorak_node_DV_X_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_X = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_X_next_node,
  .key          = DV_X,
  .bounds       = 1,
  .keys         = { KC_X },
};

const dvorak_node_t* dvorak_node_DV_B_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_B = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_B_next_node,
  .key          = DV_B,
  .bounds       = 1,
  .keys         = { KC_B },
};

const dvorak_node_t* dvorak_node_DV_M_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_M = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_M_next_node,
  .key          = DV_M,
  .bounds       = 1,
  .keys         = { KC_M },
};

const dvorak_node_t* dvorak_node_DV_W_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_W = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_W_next_node,
  .key          = DV_W,
  .bounds       = 1,
  .keys         = { KC_W },
};

const dvorak_node_t* dvorak_node_DV_V_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_V = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_V_next_node,
  .key          = DV_V,
  .bounds       = 1,
  .keys         = { KC_V },
};

const dvorak_node_t* dvorak_node_DV_Z_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_Z = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_Z_next_node,
  .key          = DV_Z,
  .bounds       = 1,
  .keys         = { KC_Z },
};

const dvorak_node_t* dvorak_node_DV_LSFT1_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT1 = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_LSFT1_next_node,
  .key          = DV_LSFT1,
  .bounds       = 1,
  .keys         = { KC_BSPC },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_next_node(uint16_t key) {
  switch (key) {
    case DV_QUOT: return &dvorak_node_DV_LSFT2_DV_QUOT;
    case DV_COMM: return &dvorak_node_DV_LSFT2_DV_COMM;
    case DV_DOT: return &dvorak_node_DV_LSFT2_DV_DOT;
    case DV_P: return &dvorak_node_DV_LSFT2_DV_P;
    case DV_Y: return &dvorak_node_DV_LSFT2_DV_Y;
    case DV_F: return &dvorak_node_DV_LSFT2_DV_F;
    case DV_G: return &dvorak_node_DV_LSFT2_DV_G;
    case DV_C: return &dvorak_node_DV_LSFT2_DV_C;
    case DV_R: return &dvorak_node_DV_LSFT2_DV_R;
    case DV_L: return &dvorak_node_DV_LSFT2_DV_L;
    case DV_A: return &dvorak_node_DV_LSFT2_DV_A;
    case DV_O: return &dvorak_node_DV_LSFT2_DV_O;
    case DV_E: return &dvorak_node_DV_LSFT2_DV_E;
    case DV_U: return &dvorak_node_DV_LSFT2_DV_U;
    case DV_I: return &dvorak_node_DV_LSFT2_DV_I;
    case DV_D: return &dvorak_node_DV_LSFT2_DV_D;
    case DV_H: return &dvorak_node_DV_LSFT2_DV_H;
    case DV_T: return &dvorak_node_DV_LSFT2_DV_T;
    case DV_N: return &dvorak_node_DV_LSFT2_DV_N;
    case DV_S: return &dvorak_node_DV_LSFT2_DV_S;
    case DV_SCLN: return &dvorak_node_DV_LSFT2_DV_SCLN;
    case DV_Q: return &dvorak_node_DV_LSFT2_DV_Q;
    case DV_J: return &dvorak_node_DV_LSFT2_DV_J;
    case DV_K: return &dvorak_node_DV_LSFT2_DV_K;
    case DV_X: return &dvorak_node_DV_LSFT2_DV_X;
    case DV_B: return &dvorak_node_DV_LSFT2_DV_B;
    case DV_M: return &dvorak_node_DV_LSFT2_DV_M;
    case DV_W: return &dvorak_node_DV_LSFT2_DV_W;
    case DV_V: return &dvorak_node_DV_LSFT2_DV_V;
    case DV_Z: return &dvorak_node_DV_LSFT2_DV_Z;
    case DV_RSFT2: return &dvorak_node_DV_LSFT2_DV_RSFT2;
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2 = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_LSFT2_next_node,
  .key          = DV_LSFT2,
  .bounds       = 18,
  .keys         = { KC_LCTL, KC_SPC },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_QUOT_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_QUOT = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_QUOT_next_node,
  .key          = DV_QUOT,
  .bounds       = 1,
  .keys         = { KC_QUOT },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_COMM_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_COMM = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_COMM_next_node,
  .key          = DV_COMM,
  .bounds       = 1,
  .keys         = { KC_COMM },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_DOT_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_DOT = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_DOT_next_node,
  .key          = DV_DOT,
  .bounds       = 1,
  .keys         = { KC_DOT },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_P_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_P = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_P_next_node,
  .key          = DV_P,
  .bounds       = 1,
  .keys         = { KC_P },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_Y_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_Y = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_Y_next_node,
  .key          = DV_Y,
  .bounds       = 1,
  .keys         = { KC_Y },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_F_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_F = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_F_next_node,
  .key          = DV_F,
  .bounds       = 1,
  .keys         = { KC_F },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_G_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_G = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_G_next_node,
  .key          = DV_G,
  .bounds       = 1,
  .keys         = { KC_G },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_C_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_C = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_C_next_node,
  .key          = DV_C,
  .bounds       = 1,
  .keys         = { KC_C },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_R_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_R = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_R_next_node,
  .key          = DV_R,
  .bounds       = 1,
  .keys         = { KC_R },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_L_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_L = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_L_next_node,
  .key          = DV_L,
  .bounds       = 1,
  .keys         = { KC_L },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_A_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_A = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_A_next_node,
  .key          = DV_A,
  .bounds       = 1,
  .keys         = { KC_A },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_O_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_O = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_O_next_node,
  .key          = DV_O,
  .bounds       = 1,
  .keys         = { KC_O },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_E_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_E = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_E_next_node,
  .key          = DV_E,
  .bounds       = 1,
  .keys         = { KC_E },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_U_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_U = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_U_next_node,
  .key          = DV_U,
  .bounds       = 1,
  .keys         = { KC_U },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_I_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_I = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_I_next_node,
  .key          = DV_I,
  .bounds       = 1,
  .keys         = { KC_I },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_D_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_D = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_D_next_node,
  .key          = DV_D,
  .bounds       = 1,
  .keys         = { KC_D },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_H_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_H = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_H_next_node,
  .key          = DV_H,
  .bounds       = 1,
  .keys         = { KC_H },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_T_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_T = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_T_next_node,
  .key          = DV_T,
  .bounds       = 1,
  .keys         = { KC_T },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_N_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_N = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_N_next_node,
  .key          = DV_N,
  .bounds       = 1,
  .keys         = { KC_N },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_S_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_S = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_S_next_node,
  .key          = DV_S,
  .bounds       = 1,
  .keys         = { KC_S },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_SCLN_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_SCLN = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_SCLN_next_node,
  .key          = DV_SCLN,
  .bounds       = 1,
  .keys         = { KC_SCLN },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_Q_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_Q = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_Q_next_node,
  .key          = DV_Q,
  .bounds       = 1,
  .keys         = { KC_Q },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_J_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_J = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_J_next_node,
  .key          = DV_J,
  .bounds       = 1,
  .keys         = { KC_J },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_K_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_K = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_K_next_node,
  .key          = DV_K,
  .bounds       = 1,
  .keys         = { KC_K },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_X_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_X = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_X_next_node,
  .key          = DV_X,
  .bounds       = 1,
  .keys         = { KC_X },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_B_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_B = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_B_next_node,
  .key          = DV_B,
  .bounds       = 1,
  .keys         = { KC_B },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_M_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_M = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_M_next_node,
  .key          = DV_M,
  .bounds       = 1,
  .keys         = { KC_M },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_W_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_W = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_W_next_node,
  .key          = DV_W,
  .bounds       = 1,
  .keys         = { KC_W },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_V_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_V = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_V_next_node,
  .key          = DV_V,
  .bounds       = 1,
  .keys         = { KC_V },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_Z_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_Z = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_Z_next_node,
  .key          = DV_Z,
  .bounds       = 1,
  .keys         = { KC_Z },
};

const dvorak_node_t* dvorak_node_DV_LSFT2_DV_RSFT2_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_LSFT2_DV_RSFT2 = {
  .parent       = &dvorak_node_DV_LSFT2,
  .next_node    = &dvorak_node_DV_LSFT2_DV_RSFT2_next_node,
  .key          = DV_RSFT2,
  .bounds       = 1,
  .keys         = { KC_ENT },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_next_node(uint16_t key) {
  switch (key) {
    case DV_QUOT: return &dvorak_node_DV_RSFT2_DV_QUOT;
    case DV_COMM: return &dvorak_node_DV_RSFT2_DV_COMM;
    case DV_DOT: return &dvorak_node_DV_RSFT2_DV_DOT;
    case DV_P: return &dvorak_node_DV_RSFT2_DV_P;
    case DV_Y: return &dvorak_node_DV_RSFT2_DV_Y;
    case DV_F: return &dvorak_node_DV_RSFT2_DV_F;
    case DV_G: return &dvorak_node_DV_RSFT2_DV_G;
    case DV_C: return &dvorak_node_DV_RSFT2_DV_C;
    case DV_R: return &dvorak_node_DV_RSFT2_DV_R;
    case DV_L: return &dvorak_node_DV_RSFT2_DV_L;
    case DV_A: return &dvorak_node_DV_RSFT2_DV_A;
    case DV_O: return &dvorak_node_DV_RSFT2_DV_O;
    case DV_E: return &dvorak_node_DV_RSFT2_DV_E;
    case DV_U: return &dvorak_node_DV_RSFT2_DV_U;
    case DV_I: return &dvorak_node_DV_RSFT2_DV_I;
    case DV_D: return &dvorak_node_DV_RSFT2_DV_D;
    case DV_H: return &dvorak_node_DV_RSFT2_DV_H;
    case DV_T: return &dvorak_node_DV_RSFT2_DV_T;
    case DV_N: return &dvorak_node_DV_RSFT2_DV_N;
    case DV_S: return &dvorak_node_DV_RSFT2_DV_S;
    case DV_SCLN: return &dvorak_node_DV_RSFT2_DV_SCLN;
    case DV_Q: return &dvorak_node_DV_RSFT2_DV_Q;
    case DV_J: return &dvorak_node_DV_RSFT2_DV_J;
    case DV_K: return &dvorak_node_DV_RSFT2_DV_K;
    case DV_X: return &dvorak_node_DV_RSFT2_DV_X;
    case DV_B: return &dvorak_node_DV_RSFT2_DV_B;
    case DV_M: return &dvorak_node_DV_RSFT2_DV_M;
    case DV_W: return &dvorak_node_DV_RSFT2_DV_W;
    case DV_V: return &dvorak_node_DV_RSFT2_DV_V;
    case DV_Z: return &dvorak_node_DV_RSFT2_DV_Z;
    case DV_LSFT1: return &dvorak_node_DV_RSFT2_DV_LSFT1;
    case DV_RSFT1: return &dvorak_node_DV_RSFT2_DV_RSFT1;
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2 = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_RSFT2_next_node,
  .key          = DV_RSFT2,
  .bounds       = 18,
  .keys         = { KC_LSFT, KC_ENT },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_QUOT_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_QUOT = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_QUOT_next_node,
  .key          = DV_QUOT,
  .bounds       = 1,
  .keys         = { KC_QUOT },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_COMM_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_COMM = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_COMM_next_node,
  .key          = DV_COMM,
  .bounds       = 1,
  .keys         = { KC_COMM },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_DOT_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_DOT = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_DOT_next_node,
  .key          = DV_DOT,
  .bounds       = 1,
  .keys         = { KC_DOT },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_P_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_P = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_P_next_node,
  .key          = DV_P,
  .bounds       = 1,
  .keys         = { KC_P },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_Y_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_Y = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_Y_next_node,
  .key          = DV_Y,
  .bounds       = 1,
  .keys         = { KC_Y },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_F_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_F = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_F_next_node,
  .key          = DV_F,
  .bounds       = 1,
  .keys         = { KC_F },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_G_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_G = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_G_next_node,
  .key          = DV_G,
  .bounds       = 1,
  .keys         = { KC_G },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_C_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_C = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_C_next_node,
  .key          = DV_C,
  .bounds       = 1,
  .keys         = { KC_C },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_R_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_R = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_R_next_node,
  .key          = DV_R,
  .bounds       = 1,
  .keys         = { KC_R },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_L_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_L = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_L_next_node,
  .key          = DV_L,
  .bounds       = 1,
  .keys         = { KC_L },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_A_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_A = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_A_next_node,
  .key          = DV_A,
  .bounds       = 1,
  .keys         = { KC_A },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_O_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_O = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_O_next_node,
  .key          = DV_O,
  .bounds       = 1,
  .keys         = { KC_O },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_E_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_E = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_E_next_node,
  .key          = DV_E,
  .bounds       = 1,
  .keys         = { KC_E },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_U_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_U = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_U_next_node,
  .key          = DV_U,
  .bounds       = 1,
  .keys         = { KC_U },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_I_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_I = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_I_next_node,
  .key          = DV_I,
  .bounds       = 1,
  .keys         = { KC_I },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_D_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_D = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_D_next_node,
  .key          = DV_D,
  .bounds       = 1,
  .keys         = { KC_D },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_H_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_H = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_H_next_node,
  .key          = DV_H,
  .bounds       = 1,
  .keys         = { KC_H },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_T_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_T = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_T_next_node,
  .key          = DV_T,
  .bounds       = 1,
  .keys         = { KC_T },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_N_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_N = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_N_next_node,
  .key          = DV_N,
  .bounds       = 1,
  .keys         = { KC_N },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_S_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_S = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_S_next_node,
  .key          = DV_S,
  .bounds       = 1,
  .keys         = { KC_S },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_SCLN_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_SCLN = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_SCLN_next_node,
  .key          = DV_SCLN,
  .bounds       = 1,
  .keys         = { KC_SCLN },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_Q_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_Q = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_Q_next_node,
  .key          = DV_Q,
  .bounds       = 1,
  .keys         = { KC_Q },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_J_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_J = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_J_next_node,
  .key          = DV_J,
  .bounds       = 1,
  .keys         = { KC_J },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_K_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_K = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_K_next_node,
  .key          = DV_K,
  .bounds       = 1,
  .keys         = { KC_K },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_X_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_X = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_X_next_node,
  .key          = DV_X,
  .bounds       = 1,
  .keys         = { KC_X },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_B_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_B = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_B_next_node,
  .key          = DV_B,
  .bounds       = 1,
  .keys         = { KC_B },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_M_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_M = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_M_next_node,
  .key          = DV_M,
  .bounds       = 1,
  .keys         = { KC_M },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_W_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_W = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_W_next_node,
  .key          = DV_W,
  .bounds       = 1,
  .keys         = { KC_W },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_V_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_V = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_V_next_node,
  .key          = DV_V,
  .bounds       = 1,
  .keys         = { KC_V },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_Z_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_Z = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_Z_next_node,
  .key          = DV_Z,
  .bounds       = 1,
  .keys         = { KC_Z },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_LSFT1_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_LSFT1 = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_LSFT1_next_node,
  .key          = DV_LSFT1,
  .bounds       = 1,
  .keys         = { KC_BSPC },
};

const dvorak_node_t* dvorak_node_DV_RSFT2_DV_RSFT1_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT2_DV_RSFT1 = {
  .parent       = &dvorak_node_DV_RSFT2,
  .next_node    = &dvorak_node_DV_RSFT2_DV_RSFT1_next_node,
  .key          = DV_RSFT1,
  .bounds       = 1,
  .keys         = { KC_TAB },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_next_node(uint16_t key) {
  switch (key) {
    case DV_QUOT: return &dvorak_node_DV_RSFT1_DV_QUOT;
    case DV_COMM: return &dvorak_node_DV_RSFT1_DV_COMM;
    case DV_DOT: return &dvorak_node_DV_RSFT1_DV_DOT;
    case DV_P: return &dvorak_node_DV_RSFT1_DV_P;
    case DV_Y: return &dvorak_node_DV_RSFT1_DV_Y;
    case DV_F: return &dvorak_node_DV_RSFT1_DV_F;
    case DV_G: return &dvorak_node_DV_RSFT1_DV_G;
    case DV_C: return &dvorak_node_DV_RSFT1_DV_C;
    case DV_R: return &dvorak_node_DV_RSFT1_DV_R;
    case DV_L: return &dvorak_node_DV_RSFT1_DV_L;
    case DV_A: return &dvorak_node_DV_RSFT1_DV_A;
    case DV_O: return &dvorak_node_DV_RSFT1_DV_O;
    case DV_E: return &dvorak_node_DV_RSFT1_DV_E;
    case DV_U: return &dvorak_node_DV_RSFT1_DV_U;
    case DV_I: return &dvorak_node_DV_RSFT1_DV_I;
    case DV_D: return &dvorak_node_DV_RSFT1_DV_D;
    case DV_H: return &dvorak_node_DV_RSFT1_DV_H;
    case DV_T: return &dvorak_node_DV_RSFT1_DV_T;
    case DV_N: return &dvorak_node_DV_RSFT1_DV_N;
    case DV_S: return &dvorak_node_DV_RSFT1_DV_S;
    case DV_SCLN: return &dvorak_node_DV_RSFT1_DV_SCLN;
    case DV_Q: return &dvorak_node_DV_RSFT1_DV_Q;
    case DV_J: return &dvorak_node_DV_RSFT1_DV_J;
    case DV_K: return &dvorak_node_DV_RSFT1_DV_K;
    case DV_X: return &dvorak_node_DV_RSFT1_DV_X;
    case DV_B: return &dvorak_node_DV_RSFT1_DV_B;
    case DV_M: return &dvorak_node_DV_RSFT1_DV_M;
    case DV_W: return &dvorak_node_DV_RSFT1_DV_W;
    case DV_V: return &dvorak_node_DV_RSFT1_DV_V;
    case DV_Z: return &dvorak_node_DV_RSFT1_DV_Z;
    case DV_LSFT1: return &dvorak_node_DV_RSFT1_DV_LSFT1;
    case DV_LSFT2: return &dvorak_node_DV_RSFT1_DV_LSFT2;
    case DV_RSFT2: return &dvorak_node_DV_RSFT1_DV_RSFT2;
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1 = {
  .parent       = &dvorak_node_root,
  .next_node    = &dvorak_node_DV_RSFT1_next_node,
  .key          = DV_RSFT1,
  .bounds       = 18,
  .keys         = { KC_LGUI, KC_TAB },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_QUOT_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_QUOT = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_QUOT_next_node,
  .key          = DV_QUOT,
  .bounds       = 1,
  .keys         = { KC_QUOT },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_COMM_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_COMM = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_COMM_next_node,
  .key          = DV_COMM,
  .bounds       = 1,
  .keys         = { KC_COMM },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_DOT_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_DOT = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_DOT_next_node,
  .key          = DV_DOT,
  .bounds       = 1,
  .keys         = { KC_DOT },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_P_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_P = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_P_next_node,
  .key          = DV_P,
  .bounds       = 1,
  .keys         = { KC_P },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_Y_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_Y = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_Y_next_node,
  .key          = DV_Y,
  .bounds       = 1,
  .keys         = { KC_Y },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_F_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_F = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_F_next_node,
  .key          = DV_F,
  .bounds       = 1,
  .keys         = { KC_F },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_G_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_G = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_G_next_node,
  .key          = DV_G,
  .bounds       = 1,
  .keys         = { KC_G },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_C_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_C = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_C_next_node,
  .key          = DV_C,
  .bounds       = 1,
  .keys         = { KC_C },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_R_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_R = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_R_next_node,
  .key          = DV_R,
  .bounds       = 1,
  .keys         = { KC_R },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_L_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_L = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_L_next_node,
  .key          = DV_L,
  .bounds       = 1,
  .keys         = { KC_L },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_A_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_A = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_A_next_node,
  .key          = DV_A,
  .bounds       = 1,
  .keys         = { KC_A },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_O_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_O = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_O_next_node,
  .key          = DV_O,
  .bounds       = 1,
  .keys         = { KC_O },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_E_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_E = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_E_next_node,
  .key          = DV_E,
  .bounds       = 1,
  .keys         = { KC_E },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_U_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_U = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_U_next_node,
  .key          = DV_U,
  .bounds       = 1,
  .keys         = { KC_U },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_I_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_I = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_I_next_node,
  .key          = DV_I,
  .bounds       = 1,
  .keys         = { KC_I },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_D_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_D = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_D_next_node,
  .key          = DV_D,
  .bounds       = 1,
  .keys         = { KC_D },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_H_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_H = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_H_next_node,
  .key          = DV_H,
  .bounds       = 1,
  .keys         = { KC_H },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_T_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_T = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_T_next_node,
  .key          = DV_T,
  .bounds       = 1,
  .keys         = { KC_T },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_N_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_N = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_N_next_node,
  .key          = DV_N,
  .bounds       = 1,
  .keys         = { KC_N },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_S_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_S = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_S_next_node,
  .key          = DV_S,
  .bounds       = 1,
  .keys         = { KC_S },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_SCLN_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_SCLN = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_SCLN_next_node,
  .key          = DV_SCLN,
  .bounds       = 1,
  .keys         = { KC_SCLN },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_Q_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_Q = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_Q_next_node,
  .key          = DV_Q,
  .bounds       = 1,
  .keys         = { KC_Q },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_J_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_J = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_J_next_node,
  .key          = DV_J,
  .bounds       = 1,
  .keys         = { KC_J },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_K_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_K = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_K_next_node,
  .key          = DV_K,
  .bounds       = 1,
  .keys         = { KC_K },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_X_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_X = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_X_next_node,
  .key          = DV_X,
  .bounds       = 1,
  .keys         = { KC_X },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_B_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_B = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_B_next_node,
  .key          = DV_B,
  .bounds       = 1,
  .keys         = { KC_B },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_M_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_M = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_M_next_node,
  .key          = DV_M,
  .bounds       = 1,
  .keys         = { KC_M },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_W_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_W = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_W_next_node,
  .key          = DV_W,
  .bounds       = 1,
  .keys         = { KC_W },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_V_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_V = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_V_next_node,
  .key          = DV_V,
  .bounds       = 1,
  .keys         = { KC_V },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_Z_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_Z = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_Z_next_node,
  .key          = DV_Z,
  .bounds       = 1,
  .keys         = { KC_Z },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_LSFT1_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_LSFT1 = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_LSFT1_next_node,
  .key          = DV_LSFT1,
  .bounds       = 1,
  .keys         = { KC_BSPC },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_LSFT2_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_LSFT2 = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_LSFT2_next_node,
  .key          = DV_LSFT2,
  .bounds       = 1,
  .keys         = { KC_SPC },
};

const dvorak_node_t* dvorak_node_DV_RSFT1_DV_RSFT2_next_node(uint16_t key) {
  switch (key) {
    default: return NULL;
  }
}

const dvorak_node_t dvorak_node_DV_RSFT1_DV_RSFT2 = {
  .parent       = &dvorak_node_DV_RSFT1,
  .next_node    = &dvorak_node_DV_RSFT1_DV_RSFT2_next_node,
  .key          = DV_RSFT2,
  .bounds       = 1,
  .keys         = { KC_ENT },
};
