/**
 * This file is generated by dvorak_keydata_gen.py
 * Do not edit this file directly.
 */
#pragma once

#include "dvorak.h"
#include "dvorak_keydata.h"

enum { DVORAK_KEY_NUMBER_GENERATED = 167 };

extern const PROGMEM dvorak_keymap dvmap_generated[DVORAK_KEY_NUMBER_GENERATED];
