/**
 * This file is generated by code generator
 * Do not edit this file directly.
 */
#include "dvorak_keydata.h"

#define B_A    0
#define B_B    1
#define B_C    2
#define B_D    3
#define B_E    4
#define B_F    5
#define B_G    6
#define B_H    7
#define B_I    8
#define B_J    9
#define B_K    10
#define B_L    11
#define B_M    12
#define B_N    13
#define B_O    14
#define B_P    15
#define B_Q    16
#define B_R    17
#define B_S    18
#define B_T    19
#define B_U    20
#define B_V    21
#define B_W    22
#define B_X    23
#define B_Y    24
#define B_Z    25
#define B_QUOT 26
#define B_COMM 27
#define B_DOT  28
#define B_SCLN 29
#define B_LS1  30
#define B_RS1  31
#define B_LS2  32
#define B_RS2  33
#define B_LS3  34
#define B_RS3  35

const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_DOT;
const dvorak_node_t dvorak_node_B_LS2_B_F;
const dvorak_node_t dvorak_node_B_RS2_B_A;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_E;
const dvorak_node_t dvorak_node_B_E_B_C;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_A;
const dvorak_node_t dvorak_node_B_LS1;
const dvorak_node_t dvorak_node_B_RS1_B_U;
const dvorak_node_t dvorak_node_B_U_B_O_B_R;
const dvorak_node_t dvorak_node_B_LS1_B_RS2;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_D;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_V;
const dvorak_node_t dvorak_node_B_N_B_H_B_U;
const dvorak_node_t dvorak_node_B_LS1_B_COMM;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_B;
const dvorak_node_t dvorak_node_B_RS2_B_QUOT;
const dvorak_node_t dvorak_node_B_U_B_O_B_D;
const dvorak_node_t dvorak_node_B_LS2_B_W;
const dvorak_node_t dvorak_node_B_O_B_U_B_D;
const dvorak_node_t dvorak_node_B_LS2_B_M;
const dvorak_node_t dvorak_node_B_LS1_B_K;
const dvorak_node_t dvorak_node_B_T_B_COMM;
const dvorak_node_t dvorak_node_B_RS2_B_F;
const dvorak_node_t dvorak_node_B_O_B_U_B_W;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_F;
const dvorak_node_t dvorak_node_B_K;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_R;
const dvorak_node_t dvorak_node_B_V;
const dvorak_node_t dvorak_node_B_RS2_B_LS2;
const dvorak_node_t dvorak_node_B_LS2_B_Z;
const dvorak_node_t dvorak_node_B_LS1_B_F;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_G;
const dvorak_node_t dvorak_node_B_H_B_N_B_Y;
const dvorak_node_t dvorak_node_B_RS1_B_Z;
const dvorak_node_t dvorak_node_B_RS2_B_COMM;
const dvorak_node_t dvorak_node_B_A;
const dvorak_node_t dvorak_node_B_RS1_B_L;
const dvorak_node_t dvorak_node_B_LS2_B_B;
const dvorak_node_t dvorak_node_B_LS2_B_E;
const dvorak_node_t dvorak_node_B_LS1_B_Z;
const dvorak_node_t dvorak_node_B_O_B_U_B_L;
const dvorak_node_t dvorak_node_B_O_B_U_B_RS2;
const dvorak_node_t dvorak_node_B_LS1_B_DOT;
const dvorak_node_t dvorak_node_B_RS1_B_B;
const dvorak_node_t dvorak_node_B_G;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_C;
const dvorak_node_t dvorak_node_B_R;
const dvorak_node_t dvorak_node_B_RS1_B_Q;
const dvorak_node_t dvorak_node_B_H_B_N_B_DOT;
const dvorak_node_t dvorak_node_B_LS2_B_COMM;
const dvorak_node_t dvorak_node_B_LS1_B_G;
const dvorak_node_t dvorak_node_B_LS1_B_LS2;
const dvorak_node_t dvorak_node_B_LS1_B_L;
const dvorak_node_t dvorak_node_B_LS2_B_T;
const dvorak_node_t dvorak_node_B_U_B_O_B_S;
const dvorak_node_t dvorak_node_B_LS1_B_J;
const dvorak_node_t dvorak_node_B_RS1_B_J;
const dvorak_node_t dvorak_node_B_O_B_U;
const dvorak_node_t dvorak_node_B_LS1_B_H;
const dvorak_node_t dvorak_node_B_P;
const dvorak_node_t dvorak_node_B_RS2_B_R;
const dvorak_node_t dvorak_node_B_RS1_B_Y;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_K;
const dvorak_node_t dvorak_node_B_RS2_B_T;
const dvorak_node_t dvorak_node_B_H_B_N_B_SCLN;
const dvorak_node_t dvorak_node_B_M;
const dvorak_node_t dvorak_node_B_LS2_B_T_B_E;
const dvorak_node_t dvorak_node_B_U_B_O_B_B;
const dvorak_node_t dvorak_node_B_LS2_B_J;
const dvorak_node_t dvorak_node_B_H_B_N;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_H;
const dvorak_node_t dvorak_node_B_LS1_B_S;
const dvorak_node_t dvorak_node_B_RS2_B_Y;
const dvorak_node_t dvorak_node_B_LS2_B_Q;
const dvorak_node_t dvorak_node_B_U_B_O_B_C;
const dvorak_node_t dvorak_node_B_RS2_B_P;
const dvorak_node_t dvorak_node_B_H_B_N_B_U;
const dvorak_node_t dvorak_node_B_LS2_B_E_B_N;
const dvorak_node_t dvorak_node_B_N_B_H;
const dvorak_node_t dvorak_node_B_Y;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_I;
const dvorak_node_t dvorak_node_B_RS2_B_W;
const dvorak_node_t dvorak_node_B_LS2_B_X;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_J;
const dvorak_node_t dvorak_node_B_RS1_B_V;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_D;
const dvorak_node_t dvorak_node_B_H_B_N_B_COMM;
const dvorak_node_t dvorak_node_B_T_B_Y;
const dvorak_node_t dvorak_node_B_LS1_B_U;
const dvorak_node_t dvorak_node_B_O_B_U_B_R;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_T;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_E;
const dvorak_node_t dvorak_node_B_QUOT;
const dvorak_node_t dvorak_node_B_E_B_R;
const dvorak_node_t dvorak_node_B_Q;
const dvorak_node_t dvorak_node_B_RS2_B_E;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_C;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_G;
const dvorak_node_t dvorak_node_B_LS2_B_O;
const dvorak_node_t dvorak_node_B_H_B_D;
const dvorak_node_t dvorak_node_B_H;
const dvorak_node_t dvorak_node_B_N_B_H_B_QUOT;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_P;
const dvorak_node_t dvorak_node_B_RS2_B_V;
const dvorak_node_t dvorak_node_B_LS2;
const dvorak_node_t dvorak_node_B_LS2_B_P;
const dvorak_node_t dvorak_node_B_H_B_N_B_QUOT;
const dvorak_node_t dvorak_node_B_H_B_N_B_Q;
const dvorak_node_t dvorak_node_B_O_B_U_B_V;
const dvorak_node_t dvorak_node_B_RS3;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_R;
const dvorak_node_t dvorak_node_B_RS2_B_I;
const dvorak_node_t dvorak_node_B_U_B_O_B_RS2;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_V;
const dvorak_node_t dvorak_node_B_U_B_O_B_W;
const dvorak_node_t dvorak_node_B_U_B_O_B_M;
const dvorak_node_t dvorak_node_B_O_B_U_B_B;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_F;
const dvorak_node_t dvorak_node_B_LS1_B_Q;
const dvorak_node_t dvorak_node_B_U;
const dvorak_node_t dvorak_node_B_COMM_B_DOT;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_S;
const dvorak_node_t dvorak_node_B_RS1_B_A;
const dvorak_node_t dvorak_node_B_SCLN;
const dvorak_node_t dvorak_node_B_RS1_B_D;
const dvorak_node_t dvorak_node_B_RS2_B_B;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_W;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_Y;
const dvorak_node_t dvorak_node_B_RS1_B_W;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_DOT;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_N;
const dvorak_node_t dvorak_node_B_H_B_N_B_J;
const dvorak_node_t dvorak_node_B_U_B_O;
const dvorak_node_t dvorak_node_B_RS1_B_LS1;
const dvorak_node_t dvorak_node_B_RS2_B_L;
const dvorak_node_t dvorak_node_B_N_B_H_B_P;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_M;
const dvorak_node_t dvorak_node_B_T_B_DOT;
const dvorak_node_t dvorak_node_B_T_B_P;
const dvorak_node_t dvorak_node_B_B;
const dvorak_node_t dvorak_node_B_N_B_H_B_E;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_O;
const dvorak_node_t dvorak_node_B_LS2_B_G;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_K;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_U;
const dvorak_node_t dvorak_node_B_RS2_B_C;
const dvorak_node_t dvorak_node_B_LS2_B_D;
const dvorak_node_t dvorak_node_B_LS1_B_W;
const dvorak_node_t dvorak_node_B_RS1_B_K;
const dvorak_node_t dvorak_node_B_RS2_B_T_B_E;
const dvorak_node_t dvorak_node_B_N_B_H_B_Y;
const dvorak_node_t dvorak_node_B_G_B_P;
const dvorak_node_t dvorak_node_B_U_B_O_B_V;
const dvorak_node_t dvorak_node_B_LS1_B_QUOT;
const dvorak_node_t dvorak_node_B_T_B_Q;
const dvorak_node_t dvorak_node_B_RS3_B_O;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_S;
const dvorak_node_t dvorak_node_B_RS2_B_S;
const dvorak_node_t dvorak_node_B_U_B_O_B_L;
const dvorak_node_t dvorak_node_B_RS2_B_U;
const dvorak_node_t dvorak_node_B_RS2_B_O;
const dvorak_node_t dvorak_node_B_LS2_B_RS2;
const dvorak_node_t dvorak_node_B_J;
const dvorak_node_t dvorak_node_B_RS2_B_DOT;
const dvorak_node_t dvorak_node_B_RS1_B_SCLN;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_O;
const dvorak_node_t dvorak_node_B_O_B_U_B_F;
const dvorak_node_t dvorak_node_B_E_B_B;
const dvorak_node_t dvorak_node_B_RS1_B_G;
const dvorak_node_t dvorak_node_B_O_B_U_B_H;
const dvorak_node_t dvorak_node_B_RS1_B_COMM;
const dvorak_node_t dvorak_node_B_LS2_B_H;
const dvorak_node_t dvorak_node_B_RS1_B_DOT;
const dvorak_node_t dvorak_node_B_L;
const dvorak_node_t dvorak_node_B_H_B_N_B_LS2;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_T;
const dvorak_node_t dvorak_node_B_RS2_B_SCLN;
const dvorak_node_t dvorak_node_B_U_B_O_B_Z;
const dvorak_node_t dvorak_node_B_O_B_U_B_G;
const dvorak_node_t dvorak_node_B_RS1_B_T;
const dvorak_node_t dvorak_node_B_U_B_O_B_N;
const dvorak_node_t dvorak_node_B_RS2_B_J;
const dvorak_node_t dvorak_node_B_W;
const dvorak_node_t dvorak_node_B_LS1_B_R;
const dvorak_node_t dvorak_node_B_LS2_B_U;
const dvorak_node_t dvorak_node_B_U_B_O_B_G;
const dvorak_node_t dvorak_node_B_RS2_B_E_B_T;
const dvorak_node_t dvorak_node_B_RS1;
const dvorak_node_t dvorak_node_B_X;
const dvorak_node_t dvorak_node_B_S;
const dvorak_node_t dvorak_node_B_H_B_N_B_K;
const dvorak_node_t dvorak_node_B_LS2_B_L;
const dvorak_node_t dvorak_node_B_DOT_B_COMM;
const dvorak_node_t dvorak_node_B_D;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_N;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_J;
const dvorak_node_t dvorak_node_B_U_B_O_B_F;
const dvorak_node_t dvorak_node_B_RS2_B_D;
const dvorak_node_t dvorak_node_B_E_B_L;
const dvorak_node_t dvorak_node_B_N_B_H_B_DOT;
const dvorak_node_t dvorak_node_B_N_B_H_B_Q;
const dvorak_node_t dvorak_node_B_LS1_B_M;
const dvorak_node_t dvorak_node_B_N_B_H_B_K;
const dvorak_node_t dvorak_node_B_E;
const dvorak_node_t dvorak_node_B_LS2_B_S;
const dvorak_node_t dvorak_node_B_LS2_B_SCLN;
const dvorak_node_t dvorak_node_B_RS1_B_LS2;
const dvorak_node_t dvorak_node_B_LS1_B_C;
const dvorak_node_t dvorak_node_B_D_B_H;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_A;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_COMM;
const dvorak_node_t dvorak_node_B_LS1_B_E;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_P;
const dvorak_node_t dvorak_node_B_N_B_H_B_I;
const dvorak_node_t dvorak_node_B_RS1_B_S;
const dvorak_node_t dvorak_node_B_I;
const dvorak_node_t dvorak_node_B_N;
const dvorak_node_t dvorak_node_B_E_B_F;
const dvorak_node_t dvorak_node_B_DOT;
const dvorak_node_t dvorak_node_B_RS2_B_Z;
const dvorak_node_t dvorak_node_B_RS3_B_E;
const dvorak_node_t dvorak_node_B_LS2_B_Y;
const dvorak_node_t dvorak_node_B_O;
const dvorak_node_t dvorak_node_B_H_B_N_B_P;
const dvorak_node_t dvorak_node_B_U_B_O_B_H;
const dvorak_node_t dvorak_node_B_COMM;
const dvorak_node_t dvorak_node_B_H_B_N_B_E;
const dvorak_node_t dvorak_node_B_T;
const dvorak_node_t dvorak_node_B_RS1_B_X;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_Y;
const dvorak_node_t dvorak_node_B_LS1_B_T;
const dvorak_node_t dvorak_node_B_RS2_B_M;
const dvorak_node_t dvorak_node_B_N_B_H_B_SCLN;
const dvorak_node_t dvorak_node_B_F;
const dvorak_node_t dvorak_node_B_RS2;
const dvorak_node_t dvorak_node_B_LS2_B_C;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_M;
const dvorak_node_t dvorak_node_B_N_B_H_B_J;
const dvorak_node_t dvorak_node_B_H_B_N_B_I;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_B;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_H;
const dvorak_node_t dvorak_node_B_LS1_B_SCLN;
const dvorak_node_t dvorak_node_B_RS2_B_N;
const dvorak_node_t dvorak_node_B_O_B_U_B_M;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_W;
const dvorak_node_t dvorak_node_B_O_B_U_B_T;
const dvorak_node_t dvorak_node_B_N_B_H_B_LS2;
const dvorak_node_t dvorak_node_B_RS2_B_Q;
const dvorak_node_t dvorak_node_B_LS2_B_N_B_E;
const dvorak_node_t dvorak_node_B_RS3_B_A;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_COMM;
const dvorak_node_t dvorak_node_B_H_B_N_B_O;
const dvorak_node_t dvorak_node_B_H_B_N_B_X;
const dvorak_node_t dvorak_node_B_LS1_B_Y;
const dvorak_node_t dvorak_node_B_I_B_U;
const dvorak_node_t dvorak_node_B_RS1_B_QUOT;
const dvorak_node_t dvorak_node_B_LS2_B_R;
const dvorak_node_t dvorak_node_B_U_B_I;
const dvorak_node_t dvorak_node_B_RS1_B_RS2;
const dvorak_node_t dvorak_node_B_RS1_B_O;
const dvorak_node_t dvorak_node_B_RS1_B_M;
const dvorak_node_t dvorak_node_B_U_B_O_B_T;
const dvorak_node_t dvorak_node_B_RS1_B_N;
const dvorak_node_t dvorak_node_B_LS1_B_X;
const dvorak_node_t dvorak_node_B_O_B_U_B_S;
const dvorak_node_t dvorak_node_B_LS2_B_V;
const dvorak_node_t dvorak_node_B_O_B_U_B_C;
const dvorak_node_t dvorak_node_B_N_B_H_B_COMM;
const dvorak_node_t dvorak_node_B_RS1_B_P;
const dvorak_node_t dvorak_node_B_C;
const dvorak_node_t dvorak_node_B_N_B_H_B_O;
const dvorak_node_t dvorak_node_B_LS1_B_B;
const dvorak_node_t dvorak_node_B_RS1_B_C;
const dvorak_node_t dvorak_node_B_N_B_H_B_X;
const dvorak_node_t dvorak_node_B_LS1_B_V;
const dvorak_node_t dvorak_node_B_LS2_B_N;
const dvorak_node_t dvorak_node_B_RS2_B_H;
const dvorak_node_t dvorak_node_B_LS2_B_A;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_U;
const dvorak_node_t dvorak_node_B_E_B_G;
const dvorak_node_t dvorak_node_B_LS1_B_A;
const dvorak_node_t dvorak_node_B_RS1_B_I;
const dvorak_node_t dvorak_node_B_LS2_B_I;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_I;
const dvorak_node_t dvorak_node_B_RS1_B_F;
const dvorak_node_t dvorak_node_B_T_B_QUOT;
const dvorak_node_t dvorak_node_B_RS2_B_G;
const dvorak_node_t dvorak_node_B_LS2_B_QUOT;
const dvorak_node_t dvorak_node_B_LS1_B_I;
const dvorak_node_t dvorak_node_B_RS1_B_E;
const dvorak_node_t dvorak_node_B_O_B_U_B_N;
const dvorak_node_t dvorak_node_B_LS1_B_O;
const dvorak_node_t dvorak_node_B_RS2_B_X;
const dvorak_node_t dvorak_node_B_RS1_B_R;
const dvorak_node_t dvorak_node_B_N_B_H_B_A;
const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_X;
const dvorak_node_t dvorak_node_B_LS2_B_E_B_T;
const dvorak_node_t dvorak_node_B_LS1_B_D;
const dvorak_node_t dvorak_node_B_Z;
const dvorak_node_t dvorak_node_B_RS2_B_K;
const dvorak_node_t dvorak_node_B_RS1_B_H;
const dvorak_node_t dvorak_node_B_LS1_B_P;
const dvorak_node_t dvorak_node_B_LS1_B_N;
const dvorak_node_t dvorak_node_B_LS2_B_DOT;
const dvorak_node_t dvorak_node_B_O_B_U_B_Z;
const dvorak_node_t dvorak_node_B_H_B_N_B_A;
const dvorak_node_t dvorak_node_B_P_B_G;
const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_X;
const dvorak_node_t dvorak_node_B_LS2_B_K;


const dvorak_node_t dvorak_node_B_LS2_B_H = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_H,
  .value        = SS_LCTL("h"),
};


const dvorak_node_t dvorak_node_B_LS1_B_I = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_I,
  .value        = SS_LALT("i"),
};


const dvorak_node_t dvorak_node_B_G_B_P = {
  .parent       = &dvorak_node_B_G,
  .children     = NULL,
  .children_num = 0,
  .key          = B_P,
  .value        = SS_TAP(X_TAB),
};


const dvorak_node_t dvorak_node_B_RS1_B_D = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_D,
  .value        = SS_LGUI("d"),
};


const dvorak_node_t dvorak_node_B_COMM_B_DOT = {
  .parent       = &dvorak_node_B_COMM,
  .children     = NULL,
  .children_num = 0,
  .key          = B_DOT,
  .value        = SS_TAP(X_ESC),
};


const dvorak_node_t dvorak_node_B_U_B_O_B_Z = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Z,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("z")))),
};


const dvorak_node_t dvorak_node_B_U_B_O_B_G = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_G,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("g")))),
};


const dvorak_node_t dvorak_node_B_U_B_O_B_C = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_C,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("c")))),
};

const dvorak_node_t* dvorak_node_B_DOT_children[1] = {
  &dvorak_node_B_DOT_B_COMM,
};
const dvorak_node_t dvorak_node_B_DOT = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_DOT_children,
  .children_num = 1,
  .key          = B_DOT,
  .value        = ".",
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_A = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_A,
  .value        = "1",
};


const dvorak_node_t dvorak_node_B_RS2_B_QUOT = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_QUOT,
  .value        = "\"",
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_I = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_I,
  .value        = "5",
};


const dvorak_node_t dvorak_node_B_RS1_B_J = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_J,
  .value        = SS_LGUI("j"),
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_X = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_X,
  .value        = "=",
};


const dvorak_node_t dvorak_node_B_N_B_H_B_A = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_A,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("a")))),
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_D = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_D,
  .value        = "6",
};


const dvorak_node_t dvorak_node_B_LS2_B_E_B_T = {
  .parent       = &dvorak_node_B_LS2_B_E,
  .children     = NULL,
  .children_num = 0,
  .key          = B_T,
  .value        = SS_LCTL("^"),
};


const dvorak_node_t dvorak_node_B_RS1_B_C = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_C,
  .value        = SS_LGUI("c"),
};


const dvorak_node_t dvorak_node_B_RS2_B_X = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_X,
  .value        = "X",
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_J = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_J,
  .value        = "|",
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_O = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_O,
  .value        = "2",
};


const dvorak_node_t dvorak_node_B_M = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_M,
  .value        = "m",
};


const dvorak_node_t dvorak_node_B_LS2_B_A = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_A,
  .value        = SS_LCTL("a"),
};


const dvorak_node_t dvorak_node_B_LS2_B_T_B_E = {
  .parent       = &dvorak_node_B_LS2_B_T,
  .children     = NULL,
  .children_num = 0,
  .key          = B_E,
  .value        = SS_LCTL(SS_TAP(X_TAB)),
};

const dvorak_node_t* dvorak_node_root_children[35] = {
  &dvorak_node_B_QUOT,
  &dvorak_node_B_COMM,
  &dvorak_node_B_DOT,
  &dvorak_node_B_P,
  &dvorak_node_B_Y,
  &dvorak_node_B_F,
  &dvorak_node_B_G,
  &dvorak_node_B_C,
  &dvorak_node_B_R,
  &dvorak_node_B_L,
  &dvorak_node_B_A,
  &dvorak_node_B_O,
  &dvorak_node_B_E,
  &dvorak_node_B_U,
  &dvorak_node_B_I,
  &dvorak_node_B_D,
  &dvorak_node_B_H,
  &dvorak_node_B_T,
  &dvorak_node_B_N,
  &dvorak_node_B_S,
  &dvorak_node_B_SCLN,
  &dvorak_node_B_Q,
  &dvorak_node_B_J,
  &dvorak_node_B_K,
  &dvorak_node_B_X,
  &dvorak_node_B_B,
  &dvorak_node_B_M,
  &dvorak_node_B_W,
  &dvorak_node_B_V,
  &dvorak_node_B_Z,
  &dvorak_node_B_LS1,
  &dvorak_node_B_LS2,
  &dvorak_node_B_RS2,
  &dvorak_node_B_RS1,
  &dvorak_node_B_RS3,
};
const dvorak_node_t dvorak_node_root = {
  .parent       = NULL,
  .children     = dvorak_node_root_children,
  .children_num = 35,
  .key          = -1,
  .value        = NULL,
};


const dvorak_node_t dvorak_node_B_H_B_N_B_COMM = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_COMM,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL(",")))),
};

const dvorak_node_t* dvorak_node_B_COMM_children[1] = {
  &dvorak_node_B_COMM_B_DOT,
};
const dvorak_node_t dvorak_node_B_COMM = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_COMM_children,
  .children_num = 1,
  .key          = B_COMM,
  .value        = ",",
};


const dvorak_node_t dvorak_node_B_LS2_B_Z = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Z,
  .value        = SS_LCTL("z"),
};


const dvorak_node_t dvorak_node_B_RS1_B_H = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_H,
  .value        = SS_LGUI("h"),
};


const dvorak_node_t dvorak_node_B_LS1_B_H = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_H,
  .value        = SS_LALT("h"),
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_K = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_K,
  .value        = "+",
};


const dvorak_node_t dvorak_node_B_RS2_B_R = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_R,
  .value        = "R",
};

const dvorak_node_t* dvorak_node_B_RS3_children[3] = {
  &dvorak_node_B_RS3_B_A,
  &dvorak_node_B_RS3_B_O,
  &dvorak_node_B_RS3_B_E,
};
const dvorak_node_t dvorak_node_B_RS3 = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_RS3_children,
  .children_num = 3,
  .key          = B_RS3,
  .value        = NULL,
};


const dvorak_node_t dvorak_node_B_LS1_B_F = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_F,
  .value        = SS_LALT("f"),
};


const dvorak_node_t dvorak_node_B_RS3_B_A = {
  .parent       = &dvorak_node_B_RS3,
  .children     = NULL,
  .children_num = 0,
  .key          = B_A,
  .value        = SS_LGUI("@"),
};


const dvorak_node_t dvorak_node_B_U_B_O_B_R = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_R,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("r")))),
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_COMM = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_COMM,
  .value        = "/",
};


const dvorak_node_t dvorak_node_B_LS1_B_B = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_B,
  .value        = SS_LALT("b"),
};


const dvorak_node_t dvorak_node_B_LS1_B_Y = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Y,
  .value        = SS_LALT("y"),
};


const dvorak_node_t dvorak_node_B_N_B_H_B_COMM = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_COMM,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL(",")))),
};


const dvorak_node_t dvorak_node_B_LS1_B_COMM = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_COMM,
  .value        = SS_LALT(","),
};


const dvorak_node_t dvorak_node_B_RS1_B_I = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_I,
  .value        = SS_LGUI("i"),
};


const dvorak_node_t dvorak_node_B_LS1_B_DOT = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_DOT,
  .value        = SS_LALT("."),
};


const dvorak_node_t dvorak_node_B_RS2_B_U = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_U,
  .value        = "U",
};


const dvorak_node_t dvorak_node_B_O_B_U_B_R = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_R,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("r")))),
};


const dvorak_node_t dvorak_node_B_LS2_B_QUOT = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_QUOT,
  .value        = SS_LCTL("'"),
};


const dvorak_node_t dvorak_node_B_RS2_B_E_B_T = {
  .parent       = &dvorak_node_B_RS2_B_E,
  .children     = NULL,
  .children_num = 0,
  .key          = B_T,
  .value        = SS_LSFT(SS_TAP(X_TAB)),
};


const dvorak_node_t dvorak_node_B_T_B_DOT = {
  .parent       = &dvorak_node_B_T,
  .children     = NULL,
  .children_num = 0,
  .key          = B_DOT,
  .value        = "#",
};


const dvorak_node_t dvorak_node_B_O_B_U_B_M = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_M,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("m")))),
};


const dvorak_node_t dvorak_node_B_RS2_B_L = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_L,
  .value        = "L",
};


const dvorak_node_t dvorak_node_B_LS1_B_SCLN = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_SCLN,
  .value        = SS_LALT(";"),
};


const dvorak_node_t dvorak_node_B_H_B_N_B_Q = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Q,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("q")))),
};


const dvorak_node_t dvorak_node_B_U_B_O_B_F = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_F,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("f")))),
};

const dvorak_node_t* dvorak_node_B_H_B_N_children[16] = {
  &dvorak_node_B_H_B_N_B_QUOT,
  &dvorak_node_B_H_B_N_B_COMM,
  &dvorak_node_B_H_B_N_B_DOT,
  &dvorak_node_B_H_B_N_B_P,
  &dvorak_node_B_H_B_N_B_Y,
  &dvorak_node_B_H_B_N_B_A,
  &dvorak_node_B_H_B_N_B_O,
  &dvorak_node_B_H_B_N_B_E,
  &dvorak_node_B_H_B_N_B_U,
  &dvorak_node_B_H_B_N_B_I,
  &dvorak_node_B_H_B_N_B_SCLN,
  &dvorak_node_B_H_B_N_B_Q,
  &dvorak_node_B_H_B_N_B_J,
  &dvorak_node_B_H_B_N_B_K,
  &dvorak_node_B_H_B_N_B_X,
  &dvorak_node_B_H_B_N_B_LS2,
};
const dvorak_node_t dvorak_node_B_H_B_N = {
  .parent       = &dvorak_node_B_H,
  .children     = dvorak_node_B_H_B_N_children,
  .children_num = 16,
  .key          = B_N,
  .value        = NULL,
};


const dvorak_node_t dvorak_node_B_H_B_N_B_QUOT = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_QUOT,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("'")))),
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_B = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_B,
  .value        = "!",
};


const dvorak_node_t dvorak_node_B_RS2_B_I = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_I,
  .value        = "I",
};


const dvorak_node_t dvorak_node_B_LS2_B_DOT = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_DOT,
  .value        = SS_LCTL("."),
};


const dvorak_node_t dvorak_node_B_N_B_H_B_K = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_K,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("k")))),
};

const dvorak_node_t* dvorak_node_B_LS2_B_N_children[1] = {
  &dvorak_node_B_LS2_B_N_B_E,
};
const dvorak_node_t dvorak_node_B_LS2_B_N = {
  .parent       = &dvorak_node_B_LS2,
  .children     = dvorak_node_B_LS2_B_N_children,
  .children_num = 1,
  .key          = B_N,
  .value        = SS_LCTL("n"),
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_H = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_H,
  .value        = "7",
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_P = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_P,
  .value        = "(",
};


const dvorak_node_t dvorak_node_B_H_B_N_B_U = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_U,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("u")))),
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_C = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_C,
  .value        = "}",
};


const dvorak_node_t dvorak_node_B_RS2_B_J = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_J,
  .value        = "J",
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_N = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_N,
  .value        = "9",
};


const dvorak_node_t dvorak_node_B_RS1_B_R = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_R,
  .value        = SS_LGUI("r"),
};


const dvorak_node_t dvorak_node_B_J = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_J,
  .value        = "j",
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_K = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_K,
  .value        = "+",
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_U = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_U,
  .value        = "4",
};


const dvorak_node_t dvorak_node_B_N_B_H_B_P = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_P,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("p")))),
};


const dvorak_node_t dvorak_node_B_O_B_U_B_C = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_C,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("c")))),
};


const dvorak_node_t dvorak_node_B_LS1_B_U = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_U,
  .value        = SS_LALT("u"),
};


const dvorak_node_t dvorak_node_B_RS1_B_Y = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Y,
  .value        = SS_LGUI("y"),
};


const dvorak_node_t dvorak_node_B_RS1_B_M = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_M,
  .value        = SS_LGUI("m"),
};


const dvorak_node_t dvorak_node_B_LS2_B_D = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_D,
  .value        = SS_LCTL("d"),
};

const dvorak_node_t* dvorak_node_B_RS2_children[31] = {
  &dvorak_node_B_RS2_B_QUOT,
  &dvorak_node_B_RS2_B_COMM,
  &dvorak_node_B_RS2_B_DOT,
  &dvorak_node_B_RS2_B_P,
  &dvorak_node_B_RS2_B_Y,
  &dvorak_node_B_RS2_B_F,
  &dvorak_node_B_RS2_B_G,
  &dvorak_node_B_RS2_B_C,
  &dvorak_node_B_RS2_B_R,
  &dvorak_node_B_RS2_B_L,
  &dvorak_node_B_RS2_B_A,
  &dvorak_node_B_RS2_B_O,
  &dvorak_node_B_RS2_B_E,
  &dvorak_node_B_RS2_B_U,
  &dvorak_node_B_RS2_B_I,
  &dvorak_node_B_RS2_B_D,
  &dvorak_node_B_RS2_B_H,
  &dvorak_node_B_RS2_B_T,
  &dvorak_node_B_RS2_B_N,
  &dvorak_node_B_RS2_B_S,
  &dvorak_node_B_RS2_B_SCLN,
  &dvorak_node_B_RS2_B_Q,
  &dvorak_node_B_RS2_B_J,
  &dvorak_node_B_RS2_B_K,
  &dvorak_node_B_RS2_B_X,
  &dvorak_node_B_RS2_B_B,
  &dvorak_node_B_RS2_B_M,
  &dvorak_node_B_RS2_B_W,
  &dvorak_node_B_RS2_B_V,
  &dvorak_node_B_RS2_B_Z,
  &dvorak_node_B_RS2_B_LS2,
};
const dvorak_node_t dvorak_node_B_RS2 = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_RS2_children,
  .children_num = 31,
  .key          = B_RS2,
  .value        = SS_TAP(X_ENT),
};


const dvorak_node_t dvorak_node_B_RS1_B_K = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_K,
  .value        = SS_LGUI("k"),
};


const dvorak_node_t dvorak_node_B_LS1_B_N = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_N,
  .value        = SS_LALT("n"),
};


const dvorak_node_t dvorak_node_B_H_B_N_B_I = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_I,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("i")))),
};


const dvorak_node_t dvorak_node_B_RS2_B_K = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_K,
  .value        = "K",
};


const dvorak_node_t dvorak_node_B_LS2_B_N_B_E = {
  .parent       = &dvorak_node_B_LS2_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_E,
  .value        = SS_LCTL("^"),
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_A = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_A,
  .value        = "1",
};


const dvorak_node_t dvorak_node_B_U_B_I = {
  .parent       = &dvorak_node_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_I,
  .value        = "",
};


const dvorak_node_t dvorak_node_B_RS1_B_F = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_F,
  .value        = SS_LGUI("f"),
};


const dvorak_node_t dvorak_node_B_LS1_B_LS2 = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_LS2,
  .value        = SS_LALT(" "),
};


const dvorak_node_t dvorak_node_B_LS1_B_V = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_V,
  .value        = SS_LALT("v"),
};


const dvorak_node_t dvorak_node_B_C = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_C,
  .value        = "c",
};


const dvorak_node_t dvorak_node_B_LS2_B_X = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_X,
  .value        = SS_LCTL("x"),
};


const dvorak_node_t dvorak_node_B_LS2_B_Y = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Y,
  .value        = SS_LCTL("y"),
};


const dvorak_node_t dvorak_node_B_LS1_B_L = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_L,
  .value        = SS_LALT("l"),
};


const dvorak_node_t dvorak_node_B_E_B_L = {
  .parent       = &dvorak_node_B_E,
  .children     = NULL,
  .children_num = 0,
  .key          = B_L,
  .value        = "$",
};


const dvorak_node_t dvorak_node_B_N_B_H_B_U = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_U,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("u")))),
};

const dvorak_node_t* dvorak_node_B_RS2_B_E_children[1] = {
  &dvorak_node_B_RS2_B_E_B_T,
};
const dvorak_node_t dvorak_node_B_RS2_B_E = {
  .parent       = &dvorak_node_B_RS2,
  .children     = dvorak_node_B_RS2_B_E_children,
  .children_num = 1,
  .key          = B_E,
  .value        = "E",
};


const dvorak_node_t dvorak_node_B_B = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_B,
  .value        = "b",
};


const dvorak_node_t dvorak_node_B_A = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_A,
  .value        = "a",
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_X = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_X,
  .value        = "=",
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_E = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_E,
  .value        = "3",
};


const dvorak_node_t dvorak_node_B_RS1_B_W = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_W,
  .value        = SS_LGUI("w"),
};


const dvorak_node_t dvorak_node_B_H_B_N_B_P = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_P,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("p")))),
};


const dvorak_node_t dvorak_node_B_U_B_O_B_V = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_V,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("v")))),
};


const dvorak_node_t dvorak_node_B_QUOT = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_QUOT,
  .value        = "'",
};


const dvorak_node_t dvorak_node_B_RS1_B_Z = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Z,
  .value        = SS_LGUI("z"),
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_T = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_T,
  .value        = "8",
};

const dvorak_node_t* dvorak_node_B_LS2_B_T_children[1] = {
  &dvorak_node_B_LS2_B_T_B_E,
};
const dvorak_node_t dvorak_node_B_LS2_B_T = {
  .parent       = &dvorak_node_B_LS2,
  .children     = dvorak_node_B_LS2_B_T_children,
  .children_num = 1,
  .key          = B_T,
  .value        = SS_LCTL("t"),
};


const dvorak_node_t dvorak_node_B_RS1_B_QUOT = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_QUOT,
  .value        = SS_LGUI("'"),
};


const dvorak_node_t dvorak_node_B_U_B_O_B_M = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_M,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("m")))),
};


const dvorak_node_t dvorak_node_B_U_B_O_B_D = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_D,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("d")))),
};


const dvorak_node_t dvorak_node_B_RS1_B_LS1 = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_LS1,
  .value        = SS_LGUI(SS_TAP(X_BSPC)),
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_H = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_H,
  .value        = "7",
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_S = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_S,
  .value        = "0",
};


const dvorak_node_t dvorak_node_B_D_B_H = {
  .parent       = &dvorak_node_B_D,
  .children     = NULL,
  .children_num = 0,
  .key          = B_H,
  .value        = "nag",
};


const dvorak_node_t dvorak_node_B_N_B_H_B_O = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_O,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("o")))),
};


const dvorak_node_t dvorak_node_B_H_B_D = {
  .parent       = &dvorak_node_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_D,
  .value        = "nag",
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_O = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_O,
  .value        = "2",
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_U = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_U,
  .value        = "4",
};


const dvorak_node_t dvorak_node_B_RS1_B_LS2 = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_LS2,
  .value        = SS_LGUI(" "),
};

const dvorak_node_t* dvorak_node_B_P_children[1] = {
  &dvorak_node_B_P_B_G,
};
const dvorak_node_t dvorak_node_B_P = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_P_children,
  .children_num = 1,
  .key          = B_P,
  .value        = "p",
};


const dvorak_node_t dvorak_node_B_RS2_B_A = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_A,
  .value        = "A",
};


const dvorak_node_t dvorak_node_B_N_B_H_B_Q = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Q,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("q")))),
};


const dvorak_node_t dvorak_node_B_U_B_O_B_N = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_N,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("n")))),
};

const dvorak_node_t* dvorak_node_B_LS2_children[31] = {
  &dvorak_node_B_LS2_B_QUOT,
  &dvorak_node_B_LS2_B_COMM,
  &dvorak_node_B_LS2_B_DOT,
  &dvorak_node_B_LS2_B_P,
  &dvorak_node_B_LS2_B_Y,
  &dvorak_node_B_LS2_B_F,
  &dvorak_node_B_LS2_B_G,
  &dvorak_node_B_LS2_B_C,
  &dvorak_node_B_LS2_B_R,
  &dvorak_node_B_LS2_B_L,
  &dvorak_node_B_LS2_B_A,
  &dvorak_node_B_LS2_B_O,
  &dvorak_node_B_LS2_B_E,
  &dvorak_node_B_LS2_B_U,
  &dvorak_node_B_LS2_B_I,
  &dvorak_node_B_LS2_B_D,
  &dvorak_node_B_LS2_B_H,
  &dvorak_node_B_LS2_B_T,
  &dvorak_node_B_LS2_B_N,
  &dvorak_node_B_LS2_B_S,
  &dvorak_node_B_LS2_B_SCLN,
  &dvorak_node_B_LS2_B_Q,
  &dvorak_node_B_LS2_B_J,
  &dvorak_node_B_LS2_B_K,
  &dvorak_node_B_LS2_B_X,
  &dvorak_node_B_LS2_B_B,
  &dvorak_node_B_LS2_B_M,
  &dvorak_node_B_LS2_B_W,
  &dvorak_node_B_LS2_B_V,
  &dvorak_node_B_LS2_B_Z,
  &dvorak_node_B_LS2_B_RS2,
};
const dvorak_node_t dvorak_node_B_LS2 = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_LS2_children,
  .children_num = 31,
  .key          = B_LS2,
  .value        = " ",
};


const dvorak_node_t dvorak_node_B_N_B_H_B_I = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_I,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("i")))),
};


const dvorak_node_t dvorak_node_B_RS1_B_T = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_T,
  .value        = SS_LGUI("t"),
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_C = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_C,
  .value        = "}",
};


const dvorak_node_t dvorak_node_B_RS2_B_Y = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Y,
  .value        = "Y",
};


const dvorak_node_t dvorak_node_B_LS1_B_P = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_P,
  .value        = SS_LALT("p"),
};


const dvorak_node_t dvorak_node_B_RS2_B_W = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_W,
  .value        = "W",
};


const dvorak_node_t dvorak_node_B_H_B_N_B_DOT = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_DOT,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL(".")))),
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_R = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_R,
  .value        = "%",
};

const dvorak_node_t* dvorak_node_B_U_children[2] = {
  &dvorak_node_B_U_B_O,
  &dvorak_node_B_U_B_I,
};
const dvorak_node_t dvorak_node_B_U = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_U_children,
  .children_num = 2,
  .key          = B_U,
  .value        = "u",
};


const dvorak_node_t dvorak_node_B_LS1_B_A = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_A,
  .value        = SS_LALT("a"),
};


const dvorak_node_t dvorak_node_B_O_B_U_B_N = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_N,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("n")))),
};


const dvorak_node_t dvorak_node_B_LS1_B_QUOT = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_QUOT,
  .value        = SS_LALT("'"),
};


const dvorak_node_t dvorak_node_B_LS1_B_S = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_S,
  .value        = SS_LALT("s"),
};


const dvorak_node_t dvorak_node_B_O_B_U_B_G = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_G,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("g")))),
};


const dvorak_node_t dvorak_node_B_RS2_B_DOT = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_DOT,
  .value        = ">",
};


const dvorak_node_t dvorak_node_B_RS2_B_S = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_S,
  .value        = "S",
};


const dvorak_node_t dvorak_node_B_DOT_B_COMM = {
  .parent       = &dvorak_node_B_DOT,
  .children     = NULL,
  .children_num = 0,
  .key          = B_COMM,
  .value        = SS_TAP(X_ESC),
};


const dvorak_node_t dvorak_node_B_RS1_B_X = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_X,
  .value        = SS_LGUI("x"),
};


const dvorak_node_t dvorak_node_B_RS2_B_G = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_G,
  .value        = "G",
};


const dvorak_node_t dvorak_node_B_RS1_B_O = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_O,
  .value        = SS_LGUI("o"),
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_W = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_W,
  .value        = "*",
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_S = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_S,
  .value        = "0",
};


const dvorak_node_t dvorak_node_B_RS2_B_B = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_B,
  .value        = "B",
};


const dvorak_node_t dvorak_node_B_T_B_QUOT = {
  .parent       = &dvorak_node_B_T,
  .children     = NULL,
  .children_num = 0,
  .key          = B_QUOT,
  .value        = "`",
};


const dvorak_node_t dvorak_node_B_RS1_B_A = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_A,
  .value        = SS_LGUI("a"),
};


const dvorak_node_t dvorak_node_B_U_B_O_B_S = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_S,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("s")))),
};


const dvorak_node_t dvorak_node_B_LS1_B_T = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_T,
  .value        = SS_LALT("t"),
};


const dvorak_node_t dvorak_node_B_LS1_B_Z = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Z,
  .value        = SS_LALT("z"),
};


const dvorak_node_t dvorak_node_B_RS2_B_V = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_V,
  .value        = "V",
};


const dvorak_node_t dvorak_node_B_O_B_U_B_L = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_L,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("l")))),
};


const dvorak_node_t dvorak_node_B_O_B_U_B_S = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_S,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("s")))),
};


const dvorak_node_t dvorak_node_B_N_B_H_B_DOT = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_DOT,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL(".")))),
};


const dvorak_node_t dvorak_node_B_LS1_B_R = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_R,
  .value        = SS_LALT("r"),
};


const dvorak_node_t dvorak_node_B_LS2_B_O = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_O,
  .value        = SS_LCTL("o"),
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_D = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_D,
  .value        = "6",
};


const dvorak_node_t dvorak_node_B_H_B_N_B_X = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_X,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("x")))),
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_B = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_B,
  .value        = "!",
};


const dvorak_node_t dvorak_node_B_RS2_B_D = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_D,
  .value        = "D",
};

const dvorak_node_t* dvorak_node_B_G_children[1] = {
  &dvorak_node_B_G_B_P,
};
const dvorak_node_t dvorak_node_B_G = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_G_children,
  .children_num = 1,
  .key          = B_G,
  .value        = "g",
};


const dvorak_node_t dvorak_node_B_S = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_S,
  .value        = "s",
};


const dvorak_node_t dvorak_node_B_H_B_N_B_Y = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Y,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("y")))),
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_COMM = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_COMM,
  .value        = "/",
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_DOT = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_DOT,
  .value        = "{",
};

const dvorak_node_t* dvorak_node_B_LS1_children[32] = {
  &dvorak_node_B_LS1_B_QUOT,
  &dvorak_node_B_LS1_B_COMM,
  &dvorak_node_B_LS1_B_DOT,
  &dvorak_node_B_LS1_B_P,
  &dvorak_node_B_LS1_B_Y,
  &dvorak_node_B_LS1_B_F,
  &dvorak_node_B_LS1_B_G,
  &dvorak_node_B_LS1_B_C,
  &dvorak_node_B_LS1_B_R,
  &dvorak_node_B_LS1_B_L,
  &dvorak_node_B_LS1_B_A,
  &dvorak_node_B_LS1_B_O,
  &dvorak_node_B_LS1_B_E,
  &dvorak_node_B_LS1_B_U,
  &dvorak_node_B_LS1_B_I,
  &dvorak_node_B_LS1_B_D,
  &dvorak_node_B_LS1_B_H,
  &dvorak_node_B_LS1_B_T,
  &dvorak_node_B_LS1_B_N,
  &dvorak_node_B_LS1_B_S,
  &dvorak_node_B_LS1_B_SCLN,
  &dvorak_node_B_LS1_B_Q,
  &dvorak_node_B_LS1_B_J,
  &dvorak_node_B_LS1_B_K,
  &dvorak_node_B_LS1_B_X,
  &dvorak_node_B_LS1_B_B,
  &dvorak_node_B_LS1_B_M,
  &dvorak_node_B_LS1_B_W,
  &dvorak_node_B_LS1_B_V,
  &dvorak_node_B_LS1_B_Z,
  &dvorak_node_B_LS1_B_LS2,
  &dvorak_node_B_LS1_B_RS2,
};
const dvorak_node_t dvorak_node_B_LS1 = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_LS1_children,
  .children_num = 32,
  .key          = B_LS1,
  .value        = SS_TAP(X_BSPC),
};


const dvorak_node_t dvorak_node_B_RS2_B_O = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_O,
  .value        = "O",
};


const dvorak_node_t dvorak_node_B_LS2_B_Q = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Q,
  .value        = SS_LCTL("q"),
};


const dvorak_node_t dvorak_node_B_LS2_B_V = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_V,
  .value        = SS_LCTL("v"),
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_J = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_J,
  .value        = "|",
};


const dvorak_node_t dvorak_node_B_RS1_B_SCLN = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_SCLN,
  .value        = SS_LGUI(";"),
};


const dvorak_node_t dvorak_node_B_LS2_B_P = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_P,
  .value        = SS_LCTL("p"),
};


const dvorak_node_t dvorak_node_B_LS2_B_I = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_I,
  .value        = SS_LCTL("i"),
};


const dvorak_node_t dvorak_node_B_N_B_H_B_X = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_X,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("x")))),
};

const dvorak_node_t* dvorak_node_B_RS2_B_LS2_children[25] = {
  &dvorak_node_B_RS2_B_LS2_B_COMM,
  &dvorak_node_B_RS2_B_LS2_B_DOT,
  &dvorak_node_B_RS2_B_LS2_B_P,
  &dvorak_node_B_RS2_B_LS2_B_Y,
  &dvorak_node_B_RS2_B_LS2_B_F,
  &dvorak_node_B_RS2_B_LS2_B_G,
  &dvorak_node_B_RS2_B_LS2_B_C,
  &dvorak_node_B_RS2_B_LS2_B_R,
  &dvorak_node_B_RS2_B_LS2_B_A,
  &dvorak_node_B_RS2_B_LS2_B_O,
  &dvorak_node_B_RS2_B_LS2_B_E,
  &dvorak_node_B_RS2_B_LS2_B_U,
  &dvorak_node_B_RS2_B_LS2_B_I,
  &dvorak_node_B_RS2_B_LS2_B_D,
  &dvorak_node_B_RS2_B_LS2_B_H,
  &dvorak_node_B_RS2_B_LS2_B_T,
  &dvorak_node_B_RS2_B_LS2_B_N,
  &dvorak_node_B_RS2_B_LS2_B_S,
  &dvorak_node_B_RS2_B_LS2_B_J,
  &dvorak_node_B_RS2_B_LS2_B_K,
  &dvorak_node_B_RS2_B_LS2_B_X,
  &dvorak_node_B_RS2_B_LS2_B_B,
  &dvorak_node_B_RS2_B_LS2_B_M,
  &dvorak_node_B_RS2_B_LS2_B_W,
  &dvorak_node_B_RS2_B_LS2_B_V,
};
const dvorak_node_t dvorak_node_B_RS2_B_LS2 = {
  .parent       = &dvorak_node_B_RS2,
  .children     = dvorak_node_B_RS2_B_LS2_children,
  .children_num = 25,
  .key          = B_LS2,
  .value        = NULL,
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_I = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_I,
  .value        = "5",
};


const dvorak_node_t dvorak_node_B_RS2_B_P = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_P,
  .value        = "P",
};


const dvorak_node_t dvorak_node_B_RS1_B_B = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_B,
  .value        = SS_LGUI("b"),
};


const dvorak_node_t dvorak_node_B_U_B_O_B_RS2 = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_RS2,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL(SS_TAP(X_ENT))))),
};


const dvorak_node_t dvorak_node_B_RS2_B_N = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_N,
  .value        = "N",
};


const dvorak_node_t dvorak_node_B_RS1_B_N = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_N,
  .value        = SS_LGUI("n"),
};


const dvorak_node_t dvorak_node_B_RS1_B_U = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_U,
  .value        = SS_LGUI("u"),
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_T = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_T,
  .value        = "8",
};


const dvorak_node_t dvorak_node_B_P_B_G = {
  .parent       = &dvorak_node_B_P,
  .children     = NULL,
  .children_num = 0,
  .key          = B_G,
  .value        = SS_TAP(X_TAB),
};


const dvorak_node_t dvorak_node_B_RS1_B_L = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_L,
  .value        = SS_LGUI("l"),
};


const dvorak_node_t dvorak_node_B_O_B_U_B_D = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_D,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("d")))),
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_DOT = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_DOT,
  .value        = "{",
};


const dvorak_node_t dvorak_node_B_H_B_N_B_SCLN = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_SCLN,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL(";")))),
};


const dvorak_node_t dvorak_node_B_T_B_P = {
  .parent       = &dvorak_node_B_T,
  .children     = NULL,
  .children_num = 0,
  .key          = B_P,
  .value        = "&",
};


const dvorak_node_t dvorak_node_B_LS2_B_K = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_K,
  .value        = SS_LCTL("k"),
};

const dvorak_node_t* dvorak_node_B_LS2_B_RS2_children[25] = {
  &dvorak_node_B_LS2_B_RS2_B_COMM,
  &dvorak_node_B_LS2_B_RS2_B_DOT,
  &dvorak_node_B_LS2_B_RS2_B_P,
  &dvorak_node_B_LS2_B_RS2_B_Y,
  &dvorak_node_B_LS2_B_RS2_B_F,
  &dvorak_node_B_LS2_B_RS2_B_G,
  &dvorak_node_B_LS2_B_RS2_B_C,
  &dvorak_node_B_LS2_B_RS2_B_R,
  &dvorak_node_B_LS2_B_RS2_B_A,
  &dvorak_node_B_LS2_B_RS2_B_O,
  &dvorak_node_B_LS2_B_RS2_B_E,
  &dvorak_node_B_LS2_B_RS2_B_U,
  &dvorak_node_B_LS2_B_RS2_B_I,
  &dvorak_node_B_LS2_B_RS2_B_D,
  &dvorak_node_B_LS2_B_RS2_B_H,
  &dvorak_node_B_LS2_B_RS2_B_T,
  &dvorak_node_B_LS2_B_RS2_B_N,
  &dvorak_node_B_LS2_B_RS2_B_S,
  &dvorak_node_B_LS2_B_RS2_B_J,
  &dvorak_node_B_LS2_B_RS2_B_K,
  &dvorak_node_B_LS2_B_RS2_B_X,
  &dvorak_node_B_LS2_B_RS2_B_B,
  &dvorak_node_B_LS2_B_RS2_B_M,
  &dvorak_node_B_LS2_B_RS2_B_W,
  &dvorak_node_B_LS2_B_RS2_B_V,
};
const dvorak_node_t dvorak_node_B_LS2_B_RS2 = {
  .parent       = &dvorak_node_B_LS2,
  .children     = dvorak_node_B_LS2_B_RS2_children,
  .children_num = 25,
  .key          = B_RS2,
  .value        = NULL,
};

const dvorak_node_t* dvorak_node_B_U_B_O_children[16] = {
  &dvorak_node_B_U_B_O_B_F,
  &dvorak_node_B_U_B_O_B_G,
  &dvorak_node_B_U_B_O_B_C,
  &dvorak_node_B_U_B_O_B_R,
  &dvorak_node_B_U_B_O_B_L,
  &dvorak_node_B_U_B_O_B_D,
  &dvorak_node_B_U_B_O_B_H,
  &dvorak_node_B_U_B_O_B_T,
  &dvorak_node_B_U_B_O_B_N,
  &dvorak_node_B_U_B_O_B_S,
  &dvorak_node_B_U_B_O_B_B,
  &dvorak_node_B_U_B_O_B_M,
  &dvorak_node_B_U_B_O_B_W,
  &dvorak_node_B_U_B_O_B_V,
  &dvorak_node_B_U_B_O_B_Z,
  &dvorak_node_B_U_B_O_B_RS2,
};
const dvorak_node_t dvorak_node_B_U_B_O = {
  .parent       = &dvorak_node_B_U,
  .children     = dvorak_node_B_U_B_O_children,
  .children_num = 16,
  .key          = B_O,
  .value        = NULL,
};


const dvorak_node_t dvorak_node_B_F = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_F,
  .value        = "f",
};


const dvorak_node_t dvorak_node_B_I_B_U = {
  .parent       = &dvorak_node_B_I,
  .children     = NULL,
  .children_num = 0,
  .key          = B_U,
  .value        = "",
};

const dvorak_node_t* dvorak_node_B_N_children[1] = {
  &dvorak_node_B_N_B_H,
};
const dvorak_node_t dvorak_node_B_N = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_N_children,
  .children_num = 1,
  .key          = B_N,
  .value        = "n",
};


const dvorak_node_t dvorak_node_B_LS1_B_O = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_O,
  .value        = SS_LALT("o"),
};


const dvorak_node_t dvorak_node_B_LS1_B_D = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_D,
  .value        = SS_LALT("d"),
};


const dvorak_node_t dvorak_node_B_RS1_B_G = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_G,
  .value        = SS_LGUI("g"),
};


const dvorak_node_t dvorak_node_B_H_B_N_B_E = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_E,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("e")))),
};


const dvorak_node_t dvorak_node_B_Z = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Z,
  .value        = "z",
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_V = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_V,
  .value        = "^",
};


const dvorak_node_t dvorak_node_B_V = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_V,
  .value        = "v",
};


const dvorak_node_t dvorak_node_B_L = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_L,
  .value        = "l",
};


const dvorak_node_t dvorak_node_B_H_B_N_B_J = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_J,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("j")))),
};

const dvorak_node_t* dvorak_node_B_H_children[2] = {
  &dvorak_node_B_H_B_N,
  &dvorak_node_B_H_B_D,
};
const dvorak_node_t dvorak_node_B_H = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_H_children,
  .children_num = 2,
  .key          = B_H,
  .value        = "h",
};


const dvorak_node_t dvorak_node_B_RS2_B_Q = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Q,
  .value        = "Q",
};


const dvorak_node_t dvorak_node_B_RS1_B_V = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_V,
  .value        = SS_LGUI("v"),
};

const dvorak_node_t* dvorak_node_B_O_B_U_children[16] = {
  &dvorak_node_B_O_B_U_B_F,
  &dvorak_node_B_O_B_U_B_G,
  &dvorak_node_B_O_B_U_B_C,
  &dvorak_node_B_O_B_U_B_R,
  &dvorak_node_B_O_B_U_B_L,
  &dvorak_node_B_O_B_U_B_D,
  &dvorak_node_B_O_B_U_B_H,
  &dvorak_node_B_O_B_U_B_T,
  &dvorak_node_B_O_B_U_B_N,
  &dvorak_node_B_O_B_U_B_S,
  &dvorak_node_B_O_B_U_B_B,
  &dvorak_node_B_O_B_U_B_M,
  &dvorak_node_B_O_B_U_B_W,
  &dvorak_node_B_O_B_U_B_V,
  &dvorak_node_B_O_B_U_B_Z,
  &dvorak_node_B_O_B_U_B_RS2,
};
const dvorak_node_t dvorak_node_B_O_B_U = {
  .parent       = &dvorak_node_B_O,
  .children     = dvorak_node_B_O_B_U_children,
  .children_num = 16,
  .key          = B_U,
  .value        = NULL,
};


const dvorak_node_t dvorak_node_B_RS1_B_S = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_S,
  .value        = SS_LGUI("s"),
};


const dvorak_node_t dvorak_node_B_LS2_B_SCLN = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_SCLN,
  .value        = SS_LCTL(";"),
};

const dvorak_node_t* dvorak_node_B_LS2_B_E_children[2] = {
  &dvorak_node_B_LS2_B_E_B_N,
  &dvorak_node_B_LS2_B_E_B_T,
};
const dvorak_node_t dvorak_node_B_LS2_B_E = {
  .parent       = &dvorak_node_B_LS2,
  .children     = dvorak_node_B_LS2_B_E_children,
  .children_num = 2,
  .key          = B_E,
  .value        = SS_LCTL("e"),
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_G = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_G,
  .value        = ")",
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_V = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_V,
  .value        = "^",
};


const dvorak_node_t dvorak_node_B_N_B_H_B_QUOT = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_QUOT,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("'")))),
};

const dvorak_node_t* dvorak_node_B_RS2_B_T_children[1] = {
  &dvorak_node_B_RS2_B_T_B_E,
};
const dvorak_node_t dvorak_node_B_RS2_B_T = {
  .parent       = &dvorak_node_B_RS2,
  .children     = dvorak_node_B_RS2_B_T_children,
  .children_num = 1,
  .key          = B_T,
  .value        = "T",
};


const dvorak_node_t dvorak_node_B_O_B_U_B_H = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_H,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("h")))),
};


const dvorak_node_t dvorak_node_B_LS1_B_X = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_X,
  .value        = SS_LALT("x"),
};


const dvorak_node_t dvorak_node_B_N_B_H_B_J = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_J,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("j")))),
};


const dvorak_node_t dvorak_node_B_RS1_B_COMM = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_COMM,
  .value        = SS_LGUI(","),
};


const dvorak_node_t dvorak_node_B_H_B_N_B_LS2 = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_LS2,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL(" ")))),
};


const dvorak_node_t dvorak_node_B_E_B_G = {
  .parent       = &dvorak_node_B_E,
  .children     = NULL,
  .children_num = 0,
  .key          = B_G,
  .value        = "@",
};

const dvorak_node_t* dvorak_node_B_RS1_children[33] = {
  &dvorak_node_B_RS1_B_QUOT,
  &dvorak_node_B_RS1_B_COMM,
  &dvorak_node_B_RS1_B_DOT,
  &dvorak_node_B_RS1_B_P,
  &dvorak_node_B_RS1_B_Y,
  &dvorak_node_B_RS1_B_F,
  &dvorak_node_B_RS1_B_G,
  &dvorak_node_B_RS1_B_C,
  &dvorak_node_B_RS1_B_R,
  &dvorak_node_B_RS1_B_L,
  &dvorak_node_B_RS1_B_A,
  &dvorak_node_B_RS1_B_O,
  &dvorak_node_B_RS1_B_E,
  &dvorak_node_B_RS1_B_U,
  &dvorak_node_B_RS1_B_I,
  &dvorak_node_B_RS1_B_D,
  &dvorak_node_B_RS1_B_H,
  &dvorak_node_B_RS1_B_T,
  &dvorak_node_B_RS1_B_N,
  &dvorak_node_B_RS1_B_S,
  &dvorak_node_B_RS1_B_SCLN,
  &dvorak_node_B_RS1_B_Q,
  &dvorak_node_B_RS1_B_J,
  &dvorak_node_B_RS1_B_K,
  &dvorak_node_B_RS1_B_X,
  &dvorak_node_B_RS1_B_B,
  &dvorak_node_B_RS1_B_M,
  &dvorak_node_B_RS1_B_W,
  &dvorak_node_B_RS1_B_V,
  &dvorak_node_B_RS1_B_Z,
  &dvorak_node_B_RS1_B_LS1,
  &dvorak_node_B_RS1_B_LS2,
  &dvorak_node_B_RS1_B_RS2,
};
const dvorak_node_t dvorak_node_B_RS1 = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_RS1_children,
  .children_num = 33,
  .key          = B_RS1,
  .value        = NULL,
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_F = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_F,
  .value        = "]",
};


const dvorak_node_t dvorak_node_B_Y = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Y,
  .value        = "y",
};


const dvorak_node_t dvorak_node_B_RS1_B_RS2 = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_RS2,
  .value        = SS_LGUI(SS_TAP(X_ENT)),
};


const dvorak_node_t dvorak_node_B_LS2_B_W = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_W,
  .value        = SS_LCTL("w"),
};


const dvorak_node_t dvorak_node_B_N_B_H_B_E = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_E,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("e")))),
};


const dvorak_node_t dvorak_node_B_LS1_B_RS2 = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_RS2,
  .value        = SS_LALT(SS_TAP(X_ENT)),
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_Y = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Y,
  .value        = "[",
};


const dvorak_node_t dvorak_node_B_RS2_B_COMM = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_COMM,
  .value        = "<",
};


const dvorak_node_t dvorak_node_B_RS2_B_C = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_C,
  .value        = "C",
};

const dvorak_node_t* dvorak_node_B_I_children[1] = {
  &dvorak_node_B_I_B_U,
};
const dvorak_node_t dvorak_node_B_I = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_I_children,
  .children_num = 1,
  .key          = B_I,
  .value        = "i",
};


const dvorak_node_t dvorak_node_B_R = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_R,
  .value        = "r",
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_E = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_E,
  .value        = "3",
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_F = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_F,
  .value        = "]",
};


const dvorak_node_t dvorak_node_B_H_B_N_B_A = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_A,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("a")))),
};


const dvorak_node_t dvorak_node_B_LS1_B_W = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_W,
  .value        = SS_LALT("w"),
};


const dvorak_node_t dvorak_node_B_W = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_W,
  .value        = "w",
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_Y = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Y,
  .value        = "[",
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_G = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_G,
  .value        = ")",
};


const dvorak_node_t dvorak_node_B_RS1_B_P = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_P,
  .value        = SS_LGUI("p"),
};


const dvorak_node_t dvorak_node_B_LS1_B_C = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_C,
  .value        = SS_LALT("c"),
};


const dvorak_node_t dvorak_node_B_H_B_N_B_K = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_K,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("k")))),
};


const dvorak_node_t dvorak_node_B_LS2_B_E_B_N = {
  .parent       = &dvorak_node_B_LS2_B_E,
  .children     = NULL,
  .children_num = 0,
  .key          = B_N,
  .value        = SS_LCTL("^"),
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_M = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_M,
  .value        = "-",
};


const dvorak_node_t dvorak_node_B_RS2_B_F = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_F,
  .value        = "F",
};


const dvorak_node_t dvorak_node_B_LS2_B_B = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_B,
  .value        = SS_LCTL("b"),
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_W = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_W,
  .value        = "*",
};


const dvorak_node_t dvorak_node_B_O_B_U_B_Z = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Z,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("z")))),
};


const dvorak_node_t dvorak_node_B_RS2_B_H = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_H,
  .value        = "H",
};


const dvorak_node_t dvorak_node_B_RS2_B_SCLN = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_SCLN,
  .value        = ":",
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_P = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_P,
  .value        = "(",
};


const dvorak_node_t dvorak_node_B_LS2_B_F = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_F,
  .value        = SS_LCTL("f"),
};


const dvorak_node_t dvorak_node_B_LS2_B_M = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_M,
  .value        = SS_LCTL("m"),
};


const dvorak_node_t dvorak_node_B_LS2_B_S = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_S,
  .value        = SS_LCTL("s"),
};


const dvorak_node_t dvorak_node_B_Q = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Q,
  .value        = "q",
};


const dvorak_node_t dvorak_node_B_U_B_O_B_H = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_H,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("h")))),
};


const dvorak_node_t dvorak_node_B_N_B_H_B_SCLN = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_SCLN,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL(";")))),
};


const dvorak_node_t dvorak_node_B_RS1_B_Q = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Q,
  .value        = SS_LGUI("q"),
};


const dvorak_node_t dvorak_node_B_T_B_COMM = {
  .parent       = &dvorak_node_B_T,
  .children     = NULL,
  .children_num = 0,
  .key          = B_COMM,
  .value        = "/",
};


const dvorak_node_t dvorak_node_B_LS1_B_M = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_M,
  .value        = SS_LALT("m"),
};

const dvorak_node_t* dvorak_node_B_D_children[1] = {
  &dvorak_node_B_D_B_H,
};
const dvorak_node_t dvorak_node_B_D = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_D_children,
  .children_num = 1,
  .key          = B_D,
  .value        = "d",
};


const dvorak_node_t dvorak_node_B_O_B_U_B_W = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_W,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("w")))),
};


const dvorak_node_t dvorak_node_B_N_B_H_B_LS2 = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_LS2,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL(" ")))),
};


const dvorak_node_t dvorak_node_B_O_B_U_B_F = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_F,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("f")))),
};


const dvorak_node_t dvorak_node_B_E_B_C = {
  .parent       = &dvorak_node_B_E,
  .children     = NULL,
  .children_num = 0,
  .key          = B_C,
  .value        = "~",
};


const dvorak_node_t dvorak_node_B_LS2_B_G = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_G,
  .value        = SS_LCTL("g"),
};


const dvorak_node_t dvorak_node_B_N_B_H_B_Y = {
  .parent       = &dvorak_node_B_N_B_H,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Y,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("y")))),
};


const dvorak_node_t dvorak_node_B_U_B_O_B_W = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_W,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("w")))),
};


const dvorak_node_t dvorak_node_B_LS2_B_L = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_L,
  .value        = SS_LCTL("l"),
};


const dvorak_node_t dvorak_node_B_LS2_B_U = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_U,
  .value        = SS_LCTL("u"),
};


const dvorak_node_t dvorak_node_B_E_B_F = {
  .parent       = &dvorak_node_B_E,
  .children     = NULL,
  .children_num = 0,
  .key          = B_F,
  .value        = "!",
};

const dvorak_node_t* dvorak_node_B_N_B_H_children[16] = {
  &dvorak_node_B_N_B_H_B_QUOT,
  &dvorak_node_B_N_B_H_B_COMM,
  &dvorak_node_B_N_B_H_B_DOT,
  &dvorak_node_B_N_B_H_B_P,
  &dvorak_node_B_N_B_H_B_Y,
  &dvorak_node_B_N_B_H_B_A,
  &dvorak_node_B_N_B_H_B_O,
  &dvorak_node_B_N_B_H_B_E,
  &dvorak_node_B_N_B_H_B_U,
  &dvorak_node_B_N_B_H_B_I,
  &dvorak_node_B_N_B_H_B_SCLN,
  &dvorak_node_B_N_B_H_B_Q,
  &dvorak_node_B_N_B_H_B_J,
  &dvorak_node_B_N_B_H_B_K,
  &dvorak_node_B_N_B_H_B_X,
  &dvorak_node_B_N_B_H_B_LS2,
};
const dvorak_node_t dvorak_node_B_N_B_H = {
  .parent       = &dvorak_node_B_N,
  .children     = dvorak_node_B_N_B_H_children,
  .children_num = 16,
  .key          = B_H,
  .value        = NULL,
};


const dvorak_node_t dvorak_node_B_LS1_B_K = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_K,
  .value        = SS_LALT("k"),
};


const dvorak_node_t dvorak_node_B_LS2_B_C = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_C,
  .value        = SS_LCTL("c"),
};


const dvorak_node_t dvorak_node_B_T_B_Q = {
  .parent       = &dvorak_node_B_T,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Q,
  .value        = "\\",
};


const dvorak_node_t dvorak_node_B_O_B_U_B_B = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_B,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("b")))),
};


const dvorak_node_t dvorak_node_B_RS1_B_E = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_E,
  .value        = SS_LGUI("e"),
};


const dvorak_node_t dvorak_node_B_LS2_B_J = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_J,
  .value        = SS_LCTL("j"),
};


const dvorak_node_t dvorak_node_B_RS3_B_O = {
  .parent       = &dvorak_node_B_RS3,
  .children     = NULL,
  .children_num = 0,
  .key          = B_O,
  .value        = SS_LGUI(SS_LSFT("4")),
};

const dvorak_node_t* dvorak_node_B_E_children[6] = {
  &dvorak_node_B_E_B_F,
  &dvorak_node_B_E_B_G,
  &dvorak_node_B_E_B_C,
  &dvorak_node_B_E_B_R,
  &dvorak_node_B_E_B_L,
  &dvorak_node_B_E_B_B,
};
const dvorak_node_t dvorak_node_B_E = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_E_children,
  .children_num = 6,
  .key          = B_E,
  .value        = "e",
};


const dvorak_node_t dvorak_node_B_LS2_B_R = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_R,
  .value        = SS_LCTL("r"),
};


const dvorak_node_t dvorak_node_B_LS1_B_Q = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Q,
  .value        = SS_LALT("q"),
};


const dvorak_node_t dvorak_node_B_RS2_B_M = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_M,
  .value        = "M",
};


const dvorak_node_t dvorak_node_B_RS3_B_E = {
  .parent       = &dvorak_node_B_RS3,
  .children     = NULL,
  .children_num = 0,
  .key          = B_E,
  .value        = SS_LGUI(SS_LSFT("5")),
};


const dvorak_node_t dvorak_node_B_U_B_O_B_T = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_T,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("t")))),
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_R = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_R,
  .value        = "%",
};


const dvorak_node_t dvorak_node_B_U_B_O_B_L = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_L,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("l")))),
};


const dvorak_node_t dvorak_node_B_O_B_U_B_V = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_V,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("v")))),
};


const dvorak_node_t dvorak_node_B_RS2_B_LS2_B_N = {
  .parent       = &dvorak_node_B_RS2_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_N,
  .value        = "9",
};


const dvorak_node_t dvorak_node_B_X = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_X,
  .value        = "x",
};

const dvorak_node_t* dvorak_node_B_T_children[6] = {
  &dvorak_node_B_T_B_QUOT,
  &dvorak_node_B_T_B_COMM,
  &dvorak_node_B_T_B_DOT,
  &dvorak_node_B_T_B_P,
  &dvorak_node_B_T_B_Y,
  &dvorak_node_B_T_B_Q,
};
const dvorak_node_t dvorak_node_B_T = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_T_children,
  .children_num = 6,
  .key          = B_T,
  .value        = "t",
};


const dvorak_node_t dvorak_node_B_E_B_R = {
  .parent       = &dvorak_node_B_E,
  .children     = NULL,
  .children_num = 0,
  .key          = B_R,
  .value        = "%",
};


const dvorak_node_t dvorak_node_B_LS2_B_RS2_B_M = {
  .parent       = &dvorak_node_B_LS2_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_M,
  .value        = "-",
};


const dvorak_node_t dvorak_node_B_LS2_B_COMM = {
  .parent       = &dvorak_node_B_LS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_COMM,
  .value        = SS_LCTL(","),
};


const dvorak_node_t dvorak_node_B_H_B_N_B_O = {
  .parent       = &dvorak_node_B_H_B_N,
  .children     = NULL,
  .children_num = 0,
  .key          = B_O,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("o")))),
};


const dvorak_node_t dvorak_node_B_SCLN = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_SCLN,
  .value        = ";",
};


const dvorak_node_t dvorak_node_B_O_B_U_B_T = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_T,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("t")))),
};


const dvorak_node_t dvorak_node_B_LS1_B_E = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_E,
  .value        = SS_LALT("e"),
};


const dvorak_node_t dvorak_node_B_T_B_Y = {
  .parent       = &dvorak_node_B_T,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Y,
  .value        = "?",
};


const dvorak_node_t dvorak_node_B_E_B_B = {
  .parent       = &dvorak_node_B_E,
  .children     = NULL,
  .children_num = 0,
  .key          = B_B,
  .value        = "_",
};


const dvorak_node_t dvorak_node_B_RS2_B_Z = {
  .parent       = &dvorak_node_B_RS2,
  .children     = NULL,
  .children_num = 0,
  .key          = B_Z,
  .value        = "Z",
};


const dvorak_node_t dvorak_node_B_K = {
  .parent       = &dvorak_node_root,
  .children     = NULL,
  .children_num = 0,
  .key          = B_K,
  .value        = "k",
};


const dvorak_node_t dvorak_node_B_RS2_B_T_B_E = {
  .parent       = &dvorak_node_B_RS2_B_T,
  .children     = NULL,
  .children_num = 0,
  .key          = B_E,
  .value        = SS_LSFT(SS_TAP(X_TAB)),
};


const dvorak_node_t dvorak_node_B_RS1_B_DOT = {
  .parent       = &dvorak_node_B_RS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_DOT,
  .value        = SS_LGUI("."),
};


const dvorak_node_t dvorak_node_B_U_B_O_B_B = {
  .parent       = &dvorak_node_B_U_B_O,
  .children     = NULL,
  .children_num = 0,
  .key          = B_B,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("b")))),
};


const dvorak_node_t dvorak_node_B_LS1_B_J = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_J,
  .value        = SS_LALT("j"),
};


const dvorak_node_t dvorak_node_B_LS1_B_G = {
  .parent       = &dvorak_node_B_LS1,
  .children     = NULL,
  .children_num = 0,
  .key          = B_G,
  .value        = SS_LALT("g"),
};

const dvorak_node_t* dvorak_node_B_O_children[1] = {
  &dvorak_node_B_O_B_U,
};
const dvorak_node_t dvorak_node_B_O = {
  .parent       = &dvorak_node_root,
  .children     = dvorak_node_B_O_children,
  .children_num = 1,
  .key          = B_O,
  .value        = "o",
};


const dvorak_node_t dvorak_node_B_O_B_U_B_RS2 = {
  .parent       = &dvorak_node_B_O_B_U,
  .children     = NULL,
  .children_num = 0,
  .key          = B_RS2,
  .value        = SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL(SS_TAP(X_ENT))))),
};
