/**
 * This file is generated by dvorak_keydata_gen.py
 * Do not edit this file directly.
 */
#include "dvorak_keydata.h"

#define B_A    0
#define B_B    1
#define B_C    2
#define B_D    3
#define B_E    4
#define B_F    5
#define B_G    6
#define B_H    7
#define B_I    8
#define B_J    9
#define B_K    10
#define B_L    11
#define B_M    12
#define B_N    13
#define B_O    14
#define B_P    15
#define B_Q    16
#define B_R    17
#define B_S    18
#define B_T    19
#define B_U    20
#define B_V    21
#define B_W    22
#define B_X    23
#define B_Y    24
#define B_Z    25
#define B_QUOT 26
#define B_COMM 27
#define B_DOT  28
#define B_SCLN 29
#define B_LS1  30
#define B_RS1  31
#define B_LS2  32
#define B_RS2  33
#define B_LS3  34
#define B_RS3  35

const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_C;
const dv_node_t PROGMEM dvnode_B_T_B_R;
const dv_node_t PROGMEM dvnode_B_N_B_LS2;
const dv_node_t PROGMEM dvnode_B_H_B_Y;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_G;
const dv_node_t PROGMEM dvnode_B_LS2_B_E;
const dv_node_t PROGMEM dvnode_B_LS2_B_S;
const dv_node_t PROGMEM dvnode_B_T_B_C;
const dv_node_t PROGMEM dvnode_B_E_B_Y;
const dv_node_t PROGMEM dvnode_B_U_B_R;
const dv_node_t PROGMEM dvnode_B_A;
const dv_node_t PROGMEM dvnode_B_V;
const dv_node_t PROGMEM dvnode_B_LS2_B_I;
const dv_node_t PROGMEM dvnode_B_LS2_B_D;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_P;
const dv_node_t PROGMEM dvnode_B_U_B_S;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_M;
const dv_node_t PROGMEM dvnode_B_U;
const dv_node_t PROGMEM dvnode_B_N;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_P;
const dv_node_t PROGMEM dvnode_B_LS2_B_N_B_E;
const dv_node_t PROGMEM dvnode_B_DOT;
const dv_node_t PROGMEM dvnode_B_RS2_B_B;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_A;
const dv_node_t PROGMEM dvnode_B_N_B_LS2_B_E;
const dv_node_t PROGMEM dvnode_B_QUOT;
const dv_node_t PROGMEM dvnode_B_RS2_B_X;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_QUOT;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_K;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_V;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_L;
const dv_node_t PROGMEM dvnode_B_LS2_B_A;
const dv_node_t PROGMEM dvnode_B_RS2_B_H;
const dv_node_t PROGMEM dvnode_B_RS2_B_V;
const dv_node_t PROGMEM dvnode_B_H_B_X;
const dv_node_t PROGMEM dvnode_B_Y;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_QUOT;
const dv_node_t PROGMEM dvnode_B_U_B_M;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_W;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_T;
const dv_node_t PROGMEM dvnode_B_H_B_QUOT;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_Q;
const dv_node_t PROGMEM dvnode_B_E_B_COMM;
const dv_node_t PROGMEM dvnode_B_RS2_B_M;
const dv_node_t PROGMEM dvnode_B_LS2_B_L;
const dv_node_t PROGMEM dvnode_B_RS2_B_Y;
const dv_node_t PROGMEM dvnode_B_H_B_P;
const dv_node_t PROGMEM dvnode_B_E_B_DOT;
const dv_node_t PROGMEM dvnode_B_X;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_J;
const dv_node_t PROGMEM dvnode_B_LS2_B_F;
const dv_node_t PROGMEM dvnode_B_H;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_COMM;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_I;
const dv_node_t PROGMEM dvnode_B_RS2_B_E;
const dv_node_t PROGMEM dvnode_B_LS2_B_B;
const dv_node_t PROGMEM dvnode_B_RS2_B_QUOT;
const dv_node_t PROGMEM dvnode_B_D;
const dv_node_t PROGMEM dvnode_B_RS2_B_SCLN;
const dv_node_t PROGMEM dvnode_B_O;
const dv_node_t PROGMEM dvnode_B_R;
const dv_node_t PROGMEM dvnode_B_RS2_B_DOT;
const dv_node_t PROGMEM dvnode_B_G;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_V;
const dv_node_t PROGMEM dvnode_B_RS2_B_W;
const dv_node_t PROGMEM dvnode_B_E;
const dv_node_t PROGMEM dvnode_B_LS2_B_SCLN;
const dv_node_t PROGMEM dvnode_B_RS2_B_Z;
const dv_node_t PROGMEM dvnode_B_J_B_W;
const dv_node_t PROGMEM dvnode_B_LS2_B_G;
const dv_node_t PROGMEM dvnode_B_W;
const dv_node_t PROGMEM dvnode_B_E_B_F;
const dv_node_t PROGMEM dvnode_B_C;
const dv_node_t PROGMEM dvnode_B_U_B_I;
const dv_node_t PROGMEM dvnode_B_H_B_Q;
const dv_node_t PROGMEM dvnode_B_H_B_K;
const dv_node_t PROGMEM dvnode_B_M;
const dv_node_t PROGMEM dvnode_B_F;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_X;
const dv_node_t PROGMEM dvnode_B_LS2_B_Z;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_H;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_D;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_A;
const dv_node_t PROGMEM dvnode_B_RS2_B_S;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_H;
const dv_node_t PROGMEM dvnode_B_T_B_P;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_DOT;
const dv_node_t PROGMEM dvnode_B_LS2_B_J;
const dv_node_t PROGMEM dvnode_B_LS2_B_M;
const dv_node_t PROGMEM dvnode_B_RS2_B_C;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_E;
const dv_node_t PROGMEM dvnode_B_H_B_I;
const dv_node_t PROGMEM dvnode_B_E_B_P;
const dv_node_t PROGMEM dvnode_B_U_B_N;
const dv_node_t PROGMEM dvnode_B_COMM;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_L;
const dv_node_t PROGMEM dvnode_B_E_B_LS2_B_N;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_Q;
const dv_node_t PROGMEM dvnode_B_T_B_DOT;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_Z;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_F;
const dv_node_t PROGMEM dvnode_B_U_B_F;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_J;
const dv_node_t PROGMEM dvnode_B_D_B_H;
const dv_node_t PROGMEM dvnode_B_K;
const dv_node_t PROGMEM dvnode_B_LS2_B_C;
const dv_node_t PROGMEM dvnode_B_RS2_B_O;
const dv_node_t PROGMEM dvnode_B_LS2_B_COMM;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_Z;
const dv_node_t PROGMEM dvnode_B_U_B_D;
const dv_node_t PROGMEM dvnode_B_E_B_LS2;
const dv_node_t PROGMEM dvnode_B_U_B_L;
const dv_node_t PROGMEM dvnode_B_T_B_L;
const dv_node_t PROGMEM dvnode_B_Q;
const dv_node_t PROGMEM dvnode_B_RS2_B_T;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_DOT;
const dv_node_t PROGMEM dvnode_B_H_B_DOT;
const dv_node_t PROGMEM dvnode_B_LS2_B_T;
const dv_node_t PROGMEM dvnode_B_RS2_B_G;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_U;
const dv_node_t PROGMEM dvnode_B_LS3;
const dv_node_t PROGMEM dvnode_B_U_B_W;
const dv_node_t PROGMEM dvnode_B_T_B_G;
const dv_node_t PROGMEM dvnode_B_T;
const dv_node_t PROGMEM dvnode_B_LS2_B_Q;
const dv_node_t PROGMEM dvnode_B_LS2_B_U;
const dv_node_t PROGMEM dvnode_B_B;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_K;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_W;
const dv_node_t PROGMEM dvnode_B_U_B_V;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_R;
const dv_node_t PROGMEM dvnode_B_E_B_L;
const dv_node_t PROGMEM dvnode_B_RS2_B_U;
const dv_node_t PROGMEM dvnode_B_H_B_O;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_Y;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_U;
const dv_node_t PROGMEM dvnode_B_RS2_B_L;
const dv_node_t PROGMEM dvnode_B_H_B_A;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_SCLN;
const dv_node_t PROGMEM dvnode_B_RS2_B_K;
const dv_node_t PROGMEM dvnode_B_LS2_B_O;
const dv_node_t PROGMEM dvnode_B_LS2_B_E_B_N;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_S;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_O;
const dv_node_t PROGMEM dvnode_B_RS2_B_J;
const dv_node_t PROGMEM dvnode_B_E_B_C;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_M;
const dv_node_t PROGMEM dvnode_B_H_B_D;
const dv_node_t PROGMEM dvnode_B_I;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_I;
const dv_node_t PROGMEM dvnode_B_T_B_Y;
const dv_node_t PROGMEM dvnode_B_S;
const dv_node_t PROGMEM dvnode_B_P;
const dv_node_t PROGMEM dvnode_B_T_B_COMM;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_R;
const dv_node_t PROGMEM dvnode_B_L;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_G;
const dv_node_t PROGMEM dvnode_B_H_B_J;
const dv_node_t PROGMEM dvnode_B_U_B_C;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_SCLN;
const dv_node_t PROGMEM dvnode_B_LS2_B_X;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2;
const dv_node_t PROGMEM dvnode_B_U_B_G;
const dv_node_t PROGMEM dvnode_B_W_B_J;
const dv_node_t PROGMEM dvnode_B_LS2;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_N;
const dv_node_t PROGMEM dvnode_B_U_B_B;
const dv_node_t PROGMEM dvnode_B_RS2_B_N;
const dv_node_t PROGMEM dvnode_B_RS2_B_F;
const dv_node_t PROGMEM dvnode_B_H_B_COMM;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_X;
const dv_node_t PROGMEM dvnode_B_LS2_B_V;
const dv_node_t PROGMEM dvnode_B_LS2_B_DOT;
const dv_node_t PROGMEM dvnode_B_LS2_B_R;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_N;
const dv_node_t PROGMEM dvnode_B_T_B_F;
const dv_node_t PROGMEM dvnode_B_E_B_G;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_Y;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_F;
const dv_node_t PROGMEM dvnode_B_T_B_QUOT;
const dv_node_t PROGMEM dvnode_B_RS2_B_R;
const dv_node_t PROGMEM dvnode_B_RS2_B_P;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_COMM;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_T;
const dv_node_t PROGMEM dvnode_B_Z;
const dv_node_t PROGMEM dvnode_B_LS2_B_P;
const dv_node_t PROGMEM dvnode_B_RS2_B_Q;
const dv_node_t PROGMEM dvnode_B_LS2_B_K;
const dv_node_t PROGMEM dvnode_B_RS2_B_D;
const dv_node_t PROGMEM dvnode_B_LS2_B_Y;
const dv_node_t PROGMEM dvnode_B_E_B_R;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_S;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_B;
const dv_node_t PROGMEM dvnode_B_E_B_QUOT;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_C;
const dv_node_t PROGMEM dvnode_B_LS2_B_H;
const dv_node_t PROGMEM dvnode_B_J;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_B;
const dv_node_t PROGMEM dvnode_B_RS2_B_COMM;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_D;
const dv_node_t PROGMEM dvnode_B_RS2_B_I;
const dv_node_t PROGMEM dvnode_B_SCLN;
const dv_node_t PROGMEM dvnode_B_RS2;
const dv_node_t PROGMEM dvnode_B_I_B_U;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2_B_E;
const dv_node_t PROGMEM dvnode_B_LS2_B_QUOT;
const dv_node_t PROGMEM dvnode_B_LS2_B_N;
const dv_node_t PROGMEM dvnode_B_RS2_B_A;
const dv_node_t PROGMEM dvnode_B_LS2_B_RS2_B_O;
const dv_node_t PROGMEM dvnode_B_RS2_B_LS2;
const dv_node_t PROGMEM dvnode_B_LS2_B_W;


const PROGMEM dv_node_t dvnode_B_DOT = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_DOT,
       .value        = ".",
};


const PROGMEM dv_node_t dvnode_B_T_B_R = {
       .parent       = &dvnode_B_T,
       .children     = NULL,
       .children_num = 0,
       .key          = B_R,
       .value        = "9",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_W = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_W,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_LS2_B_N_B_E = {
       .parent       = &dvnode_B_LS2_B_N,
       .children     = NULL,
       .children_num = 0,
       .key          = B_E,
       .value        = SS_LCTL("^"),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_M = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_M,
       .value        = SS_LCTL("m"),
};

const dv_node_t* dvnode_B_E_children[11] = {
	&dvnode_B_E_B_R,
	&dvnode_B_E_B_COMM,
	&dvnode_B_E_B_L,
	&dvnode_B_E_B_G,
	&dvnode_B_E_B_F,
	&dvnode_B_E_B_Y,
	&dvnode_B_E_B_P,
	&dvnode_B_E_B_QUOT,
	&dvnode_B_E_B_C,
	&dvnode_B_E_B_LS2,
	&dvnode_B_E_B_DOT,
};
const PROGMEM dv_node_t dvnode_B_E = {
       .parent       = &dvnode_root,
       .children     = dvnode_B_E_children,
       .children_num = 11,
       .key          = B_E,
       .value        = "e",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_QUOT = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_QUOT,
       .value        = "\"",
};


const PROGMEM dv_node_t dvnode_B_H_B_COMM = {
       .parent       = &dvnode_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_COMM,
       .value        = "%",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_N = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "N",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_Z = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Z,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_H_B_J = {
       .parent       = &dvnode_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "&",
};


const PROGMEM dv_node_t dvnode_B_H_B_K = {
       .parent       = &dvnode_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "=",
};


const PROGMEM dv_node_t dvnode_B_E_B_LS2_B_N = {
       .parent       = &dvnode_B_E_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_V = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_V,
       .value        = SS_LSFT(SS_LCTL("v")),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_Y = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Y,
       .value        = "Y",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_DOT = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_DOT,
       .value        = ">",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_O = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = SS_LCTL("o"),
};


const PROGMEM dv_node_t dvnode_B_O = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "o",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_F = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_F,
       .value        = SS_LCTL("f"),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_DOT = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_DOT,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_D_B_H = {
       .parent       = &dvnode_B_D,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "nag",
};

const dv_node_t* dvnode_root_children[33] = {
	&dvnode_B_LS2,
	&dvnode_B_RS2,
	&dvnode_B_E,
	&dvnode_B_I,
	&dvnode_B_T,
	&dvnode_B_S,
	&dvnode_B_M,
	&dvnode_B_H,
	&dvnode_B_Y,
	&dvnode_B_D,
	&dvnode_B_K,
	&dvnode_B_QUOT,
	&dvnode_B_Q,
	&dvnode_B_C,
	&dvnode_B_J,
	&dvnode_B_U,
	&dvnode_B_P,
	&dvnode_B_Z,
	&dvnode_B_SCLN,
	&dvnode_B_W,
	&dvnode_B_DOT,
	&dvnode_B_N,
	&dvnode_B_COMM,
	&dvnode_B_G,
	&dvnode_B_LS3,
	&dvnode_B_R,
	&dvnode_B_B,
	&dvnode_B_A,
	&dvnode_B_L,
	&dvnode_B_O,
	&dvnode_B_F,
	&dvnode_B_V,
	&dvnode_B_X,
};
const PROGMEM dv_node_t dvnode_root = {
       .parent       = NULL,
       .children     = dvnode_root_children,
       .children_num = 33,
       .key          = -1,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_RS2_B_M = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_M,
       .value        = "M",
};


const PROGMEM dv_node_t dvnode_B_T_B_F = {
       .parent       = &dvnode_B_T,
       .children     = NULL,
       .children_num = 0,
       .key          = B_F,
       .value        = "6",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_E = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_E,
       .value        = NULL,
};

const dv_node_t* dvnode_B_D_children[1] = {
	&dvnode_B_D_B_H,
};
const PROGMEM dv_node_t dvnode_B_D = {
       .parent       = &dvnode_root,
       .children     = dvnode_B_D_children,
       .children_num = 1,
       .key          = B_D,
       .value        = "d",
};


const PROGMEM dv_node_t dvnode_B_H_B_Q = {
       .parent       = &dvnode_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Q,
       .value        = "\\",
};

const dv_node_t* dvnode_B_LS2_B_E_children[1] = {
	&dvnode_B_LS2_B_E_B_N,
};
const PROGMEM dv_node_t dvnode_B_LS2_B_E = {
       .parent       = &dvnode_B_LS2,
       .children     = dvnode_B_LS2_B_E_children,
       .children_num = 1,
       .key          = B_E,
       .value        = SS_LCTL("e"),
};


const PROGMEM dv_node_t dvnode_B_H_B_Y = {
       .parent       = &dvnode_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Y,
       .value        = "[",
};

const dv_node_t* dvnode_B_N_children[1] = {
	&dvnode_B_N_B_LS2,
};
const PROGMEM dv_node_t dvnode_B_N = {
       .parent       = &dvnode_root,
       .children     = dvnode_B_N_children,
       .children_num = 1,
       .key          = B_N,
       .value        = "n",
};


const PROGMEM dv_node_t dvnode_B_A = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_A,
       .value        = "a",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_QUOT = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_QUOT,
       .value        = SS_LCTL("'"),
};


const PROGMEM dv_node_t dvnode_B_M = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_M,
       .value        = "m",
};


const PROGMEM dv_node_t dvnode_B_H_B_DOT = {
       .parent       = &dvnode_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_DOT,
       .value        = "{",
};


const PROGMEM dv_node_t dvnode_B_U_B_F = {
       .parent       = &dvnode_B_U,
       .children     = NULL,
       .children_num = 0,
       .key          = B_F,
       .value        = "]",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_F = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_F,
       .value        = "F",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_A = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_A,
       .value        = SS_LSFT(SS_LCTL("a")),
};

const dv_node_t* dvnode_B_N_B_LS2_children[1] = {
	&dvnode_B_N_B_LS2_B_E,
};
const PROGMEM dv_node_t dvnode_B_N_B_LS2 = {
       .parent       = &dvnode_B_N,
       .children     = dvnode_B_N_B_LS2_children,
       .children_num = 1,
       .key          = B_LS2,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_X = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_X,
       .value        = "x",
};

const dv_node_t* dvnode_B_H_children[13] = {
	&dvnode_B_H_B_A,
	&dvnode_B_H_B_I,
	&dvnode_B_H_B_O,
	&dvnode_B_H_B_X,
	&dvnode_B_H_B_Q,
	&dvnode_B_H_B_P,
	&dvnode_B_H_B_Y,
	&dvnode_B_H_B_K,
	&dvnode_B_H_B_QUOT,
	&dvnode_B_H_B_D,
	&dvnode_B_H_B_DOT,
	&dvnode_B_H_B_COMM,
	&dvnode_B_H_B_J,
};
const PROGMEM dv_node_t dvnode_B_H = {
       .parent       = &dvnode_root,
       .children     = dvnode_B_H_children,
       .children_num = 13,
       .key          = B_H,
       .value        = "h",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_SCLN = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_SCLN,
       .value        = SS_LSFT(SS_LCTL(";")),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_F = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_F,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_P = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "p",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_Y = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Y,
       .value        = SS_LCTL("y"),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_COMM = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_COMM,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_T_B_C = {
       .parent       = &dvnode_B_T,
       .children     = NULL,
       .children_num = 0,
       .key          = B_C,
       .value        = "8",
};


const PROGMEM dv_node_t dvnode_B_U_B_G = {
       .parent       = &dvnode_B_U,
       .children     = NULL,
       .children_num = 0,
       .key          = B_G,
       .value        = ")",
};


const PROGMEM dv_node_t dvnode_B_T_B_P = {
       .parent       = &dvnode_B_T,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "4",
};


const PROGMEM dv_node_t dvnode_B_SCLN = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_SCLN,
       .value        = ";",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_R = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_R,
       .value        = "R",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_B = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_B,
       .value        = "B",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_S = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_S,
       .value        = SS_LCTL("s"),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_B = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_B,
       .value        = SS_LCTL("b"),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_B = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_B,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_H_B_D = {
       .parent       = &dvnode_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_D,
       .value        = "nag",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_Q = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Q,
       .value        = "Q",
};


const PROGMEM dv_node_t dvnode_B_U_B_M = {
       .parent       = &dvnode_B_U,
       .children     = NULL,
       .children_num = 0,
       .key          = B_M,
       .value        = "@",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_M = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_M,
       .value        = SS_LSFT(SS_LCTL("m")),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_G = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_G,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_LS2_B_SCLN = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_SCLN,
       .value        = SS_LCTL(";"),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_T = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_T,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_RS2_B_W = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_W,
       .value        = "W",
};


const PROGMEM dv_node_t dvnode_B_I_B_U = {
       .parent       = &dvnode_B_I,
       .children     = NULL,
       .children_num = 0,
       .key          = B_U,
       .value        = SS_TAP(X_ESC),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_C = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_C,
       .value        = SS_LCTL("c"),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_D = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_D,
       .value        = SS_LCTL("d"),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_V = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_V,
       .value        = SS_LCTL("v"),
};


const PROGMEM dv_node_t dvnode_B_R = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_R,
       .value        = "r",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_I = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = SS_LSFT(SS_LCTL("i")),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_Y = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Y,
       .value        = SS_LSFT(SS_LCTL("y")),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_K = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = SS_LCTL("k"),
};


const PROGMEM dv_node_t dvnode_B_U_B_D = {
       .parent       = &dvnode_B_U,
       .children     = NULL,
       .children_num = 0,
       .key          = B_D,
       .value        = "_",
};

const dv_node_t* dvnode_B_J_children[1] = {
	&dvnode_B_J_B_W,
};
const PROGMEM dv_node_t dvnode_B_J = {
       .parent       = &dvnode_root,
       .children     = dvnode_B_J_children,
       .children_num = 1,
       .key          = B_J,
       .value        = "j",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_C = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_C,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_W = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_W,
       .value        = SS_LSFT(SS_LCTL("w")),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_G = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_G,
       .value        = SS_LSFT(SS_LCTL("g")),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_P = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = SS_LCTL("p"),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_O = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "O",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_D = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_D,
       .value        = SS_LSFT(SS_LCTL("d")),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_A = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_A,
       .value        = SS_LCTL("a"),
};


const PROGMEM dv_node_t dvnode_B_H_B_O = {
       .parent       = &dvnode_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "/",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_D = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_D,
       .value        = "D",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_I = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "I",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_J = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_R = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_R,
       .value        = SS_LSFT(SS_LCTL("r")),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_Z = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Z,
       .value        = SS_LCTL("z"),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_DOT = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_DOT,
       .value        = SS_LSFT(SS_LCTL(".")),
};


const PROGMEM dv_node_t dvnode_B_Y = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Y,
       .value        = "y",
};


const PROGMEM dv_node_t dvnode_B_E_B_L = {
       .parent       = &dvnode_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = "0",
};

const dv_node_t* dvnode_B_T_children[10] = {
	&dvnode_B_T_B_C,
	&dvnode_B_T_B_P,
	&dvnode_B_T_B_QUOT,
	&dvnode_B_T_B_COMM,
	&dvnode_B_T_B_G,
	&dvnode_B_T_B_DOT,
	&dvnode_B_T_B_R,
	&dvnode_B_T_B_L,
	&dvnode_B_T_B_F,
	&dvnode_B_T_B_Y,
};
const PROGMEM dv_node_t dvnode_B_T = {
       .parent       = &dvnode_root,
       .children     = dvnode_B_T_children,
       .children_num = 10,
       .key          = B_T,
       .value        = "t",
};


const PROGMEM dv_node_t dvnode_B_T_B_QUOT = {
       .parent       = &dvnode_B_T,
       .children     = NULL,
       .children_num = 0,
       .key          = B_QUOT,
       .value        = "1",
};


const PROGMEM dv_node_t dvnode_B_S = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_S,
       .value        = "s",
};

const dv_node_t* dvnode_B_RS2_B_LS2_children[30] = {
	&dvnode_B_RS2_B_LS2_B_S,
	&dvnode_B_RS2_B_LS2_B_M,
	&dvnode_B_RS2_B_LS2_B_QUOT,
	&dvnode_B_RS2_B_LS2_B_C,
	&dvnode_B_RS2_B_LS2_B_D,
	&dvnode_B_RS2_B_LS2_B_Z,
	&dvnode_B_RS2_B_LS2_B_SCLN,
	&dvnode_B_RS2_B_LS2_B_U,
	&dvnode_B_RS2_B_LS2_B_DOT,
	&dvnode_B_RS2_B_LS2_B_R,
	&dvnode_B_RS2_B_LS2_B_COMM,
	&dvnode_B_RS2_B_LS2_B_J,
	&dvnode_B_RS2_B_LS2_B_B,
	&dvnode_B_RS2_B_LS2_B_L,
	&dvnode_B_RS2_B_LS2_B_A,
	&dvnode_B_RS2_B_LS2_B_H,
	&dvnode_B_RS2_B_LS2_B_I,
	&dvnode_B_RS2_B_LS2_B_G,
	&dvnode_B_RS2_B_LS2_B_W,
	&dvnode_B_RS2_B_LS2_B_X,
	&dvnode_B_RS2_B_LS2_B_E,
	&dvnode_B_RS2_B_LS2_B_O,
	&dvnode_B_RS2_B_LS2_B_F,
	&dvnode_B_RS2_B_LS2_B_Y,
	&dvnode_B_RS2_B_LS2_B_K,
	&dvnode_B_RS2_B_LS2_B_N,
	&dvnode_B_RS2_B_LS2_B_V,
	&dvnode_B_RS2_B_LS2_B_Q,
	&dvnode_B_RS2_B_LS2_B_T,
	&dvnode_B_RS2_B_LS2_B_P,
};
const PROGMEM dv_node_t dvnode_B_RS2_B_LS2 = {
       .parent       = &dvnode_B_RS2,
       .children     = dvnode_B_RS2_B_LS2_children,
       .children_num = 30,
       .key          = B_LS2,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_E_B_Y = {
       .parent       = &dvnode_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Y,
       .value        = "5",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_S = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_S,
       .value        = SS_LSFT(SS_LCTL("s")),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_H = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = SS_LCTL("h"),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_DOT = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_DOT,
       .value        = SS_LCTL("."),
};


const PROGMEM dv_node_t dvnode_B_F = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_F,
       .value        = "f",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_P = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = SS_LSFT(SS_LCTL("p")),
};


const PROGMEM dv_node_t dvnode_B_U_B_L = {
       .parent       = &dvnode_B_U,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = "!",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_L = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_RS2_B_K = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "K",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_C = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_C,
       .value        = "C",
};


const PROGMEM dv_node_t dvnode_B_W_B_J = {
       .parent       = &dvnode_B_W,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = SS_TAP(X_TAB),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_SCLN = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_SCLN,
       .value        = ":",
};


const PROGMEM dv_node_t dvnode_B_V = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_V,
       .value        = "v",
};

const dv_node_t* dvnode_B_LS2_B_N_children[1] = {
	&dvnode_B_LS2_B_N_B_E,
};
const PROGMEM dv_node_t dvnode_B_LS2_B_N = {
       .parent       = &dvnode_B_LS2,
       .children     = dvnode_B_LS2_B_N_children,
       .children_num = 1,
       .key          = B_N,
       .value        = SS_LCTL("n"),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_Z = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Z,
       .value        = SS_LSFT(SS_LCTL("z")),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_S = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_S,
       .value        = "S",
};

const dv_node_t* dvnode_B_I_children[1] = {
	&dvnode_B_I_B_U,
};
const PROGMEM dv_node_t dvnode_B_I = {
       .parent       = &dvnode_root,
       .children     = dvnode_B_I_children,
       .children_num = 1,
       .key          = B_I,
       .value        = "i",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_Q = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Q,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_LS2_B_G = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_G,
       .value        = SS_LCTL("g"),
};


const PROGMEM dv_node_t dvnode_B_H_B_I = {
       .parent       = &dvnode_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "|",
};


const PROGMEM dv_node_t dvnode_B_U_B_R = {
       .parent       = &dvnode_B_U,
       .children     = NULL,
       .children_num = 0,
       .key          = B_R,
       .value        = "$",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_X = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_X,
       .value        = SS_LSFT(SS_LCTL("x")),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_COMM = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_COMM,
       .value        = SS_LSFT(SS_LCTL(",")),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_J = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = SS_LSFT(SS_LCTL("j")),
};

const dv_node_t* dvnode_B_RS2_children[31] = {
	&dvnode_B_RS2_B_R,
	&dvnode_B_RS2_B_LS2,
	&dvnode_B_RS2_B_COMM,
	&dvnode_B_RS2_B_J,
	&dvnode_B_RS2_B_B,
	&dvnode_B_RS2_B_A,
	&dvnode_B_RS2_B_L,
	&dvnode_B_RS2_B_E,
	&dvnode_B_RS2_B_H,
	&dvnode_B_RS2_B_I,
	&dvnode_B_RS2_B_W,
	&dvnode_B_RS2_B_X,
	&dvnode_B_RS2_B_O,
	&dvnode_B_RS2_B_F,
	&dvnode_B_RS2_B_Y,
	&dvnode_B_RS2_B_K,
	&dvnode_B_RS2_B_N,
	&dvnode_B_RS2_B_V,
	&dvnode_B_RS2_B_Q,
	&dvnode_B_RS2_B_T,
	&dvnode_B_RS2_B_P,
	&dvnode_B_RS2_B_D,
	&dvnode_B_RS2_B_S,
	&dvnode_B_RS2_B_M,
	&dvnode_B_RS2_B_QUOT,
	&dvnode_B_RS2_B_C,
	&dvnode_B_RS2_B_Z,
	&dvnode_B_RS2_B_SCLN,
	&dvnode_B_RS2_B_G,
	&dvnode_B_RS2_B_U,
	&dvnode_B_RS2_B_DOT,
};
const PROGMEM dv_node_t dvnode_B_RS2 = {
       .parent       = &dvnode_root,
       .children     = dvnode_B_RS2_children,
       .children_num = 31,
       .key          = B_RS2,
       .value        = SS_TAP(X_ENT),
};


const PROGMEM dv_node_t dvnode_B_E_B_R = {
       .parent       = &dvnode_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_R,
       .value        = "9",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_Q = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Q,
       .value        = SS_LSFT(SS_LCTL("q")),
};


const PROGMEM dv_node_t dvnode_B_H_B_X = {
       .parent       = &dvnode_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_X,
       .value        = "+",
};


const PROGMEM dv_node_t dvnode_B_U_B_I = {
       .parent       = &dvnode_B_U,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = SS_TAP(X_ESC),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_A = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_A,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_U_B_W = {
       .parent       = &dvnode_B_U,
       .children     = NULL,
       .children_num = 0,
       .key          = B_W,
       .value        = "?",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_U = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_U,
       .value        = SS_LSFT(SS_LCTL("u")),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_Q = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Q,
       .value        = SS_LCTL("q"),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_G = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_G,
       .value        = "G",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_T = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_T,
       .value        = SS_LSFT(SS_LCTL("t")),
};

const dv_node_t* dvnode_B_W_children[1] = {
	&dvnode_B_W_B_J,
};
const PROGMEM dv_node_t dvnode_B_W = {
       .parent       = &dvnode_root,
       .children     = dvnode_B_W_children,
       .children_num = 1,
       .key          = B_W,
       .value        = "w",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_P = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_E_B_G = {
       .parent       = &dvnode_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_G,
       .value        = "7",
};


const PROGMEM dv_node_t dvnode_B_T_B_DOT = {
       .parent       = &dvnode_B_T,
       .children     = NULL,
       .children_num = 0,
       .key          = B_DOT,
       .value        = "3",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_N = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = SS_LSFT(SS_LCTL("n")),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_C = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_C,
       .value        = SS_LSFT(SS_LCTL("c")),
};

const dv_node_t* dvnode_B_U_children[13] = {
	&dvnode_B_U_B_F,
	&dvnode_B_U_B_N,
	&dvnode_B_U_B_V,
	&dvnode_B_U_B_S,
	&dvnode_B_U_B_M,
	&dvnode_B_U_B_C,
	&dvnode_B_U_B_D,
	&dvnode_B_U_B_R,
	&dvnode_B_U_B_B,
	&dvnode_B_U_B_L,
	&dvnode_B_U_B_I,
	&dvnode_B_U_B_G,
	&dvnode_B_U_B_W,
};
const PROGMEM dv_node_t dvnode_B_U = {
       .parent       = &dvnode_root,
       .children     = dvnode_B_U_children,
       .children_num = 13,
       .key          = B_U,
       .value        = "u",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_U = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_U,
       .value        = SS_LCTL("u"),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_U = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_U,
       .value        = "U",
};


const PROGMEM dv_node_t dvnode_B_U_B_S = {
       .parent       = &dvnode_B_U,
       .children     = NULL,
       .children_num = 0,
       .key          = B_S,
       .value        = "~",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_R = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_R,
       .value        = SS_LCTL("r"),
};


const PROGMEM dv_node_t dvnode_B_T_B_Y = {
       .parent       = &dvnode_B_T,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Y,
       .value        = "5",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_L = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = "L",
};


const PROGMEM dv_node_t dvnode_B_QUOT = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_QUOT,
       .value        = "'",
};


const PROGMEM dv_node_t dvnode_B_E_B_QUOT = {
       .parent       = &dvnode_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_QUOT,
       .value        = "1",
};

const dv_node_t* dvnode_B_E_B_LS2_children[1] = {
	&dvnode_B_E_B_LS2_B_N,
};
const PROGMEM dv_node_t dvnode_B_E_B_LS2 = {
       .parent       = &dvnode_B_E,
       .children     = dvnode_B_E_B_LS2_children,
       .children_num = 1,
       .key          = B_LS2,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_H = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = SS_LSFT(SS_LCTL("h")),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_X = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_X,
       .value        = "X",
};


const PROGMEM dv_node_t dvnode_B_H_B_QUOT = {
       .parent       = &dvnode_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_QUOT,
       .value        = "`",
};


const PROGMEM dv_node_t dvnode_B_E_B_F = {
       .parent       = &dvnode_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_F,
       .value        = "6",
};


const PROGMEM dv_node_t dvnode_B_K = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "k",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_Z = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Z,
       .value        = "Z",
};


const PROGMEM dv_node_t dvnode_B_G = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_G,
       .value        = "g",
};


const PROGMEM dv_node_t dvnode_B_E_B_C = {
       .parent       = &dvnode_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_C,
       .value        = "8",
};


const PROGMEM dv_node_t dvnode_B_B = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_B,
       .value        = "b",
};


const PROGMEM dv_node_t dvnode_B_H_B_A = {
       .parent       = &dvnode_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_A,
       .value        = "#",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_A = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_A,
       .value        = "A",
};


const PROGMEM dv_node_t dvnode_B_H_B_P = {
       .parent       = &dvnode_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "(",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_S = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_S,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_QUOT = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_QUOT,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_O = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = SS_LSFT(SS_LCTL("o")),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_D = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_D,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_N_B_LS2_B_E = {
       .parent       = &dvnode_B_N_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_E,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_RS2_B_T = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_T,
       .value        = "T",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_F = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_F,
       .value        = SS_LSFT(SS_LCTL("f")),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_O = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_M = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_M,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_U = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_U,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_C = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_C,
       .value        = "c",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_H = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_U_B_V = {
       .parent       = &dvnode_B_U,
       .children     = NULL,
       .children_num = 0,
       .key          = B_V,
       .value        = "*",
};


const PROGMEM dv_node_t dvnode_B_T_B_COMM = {
       .parent       = &dvnode_B_T,
       .children     = NULL,
       .children_num = 0,
       .key          = B_COMM,
       .value        = "2",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_W = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_W,
       .value        = SS_LCTL("w"),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_X = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_X,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_V = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_V,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_COMM = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_COMM,
       .value        = ",",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_K = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_SCLN = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_SCLN,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_N = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_RS2_B_E = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_E,
       .value        = "E",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_Y = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Y,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_K = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = SS_LSFT(SS_LCTL("k")),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_L = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = SS_LCTL("l"),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_I = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = SS_LCTL("i"),
};


const PROGMEM dv_node_t dvnode_B_LS3 = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS3,
       .value        = "hey",
};


const PROGMEM dv_node_t dvnode_B_U_B_C = {
       .parent       = &dvnode_B_U,
       .children     = NULL,
       .children_num = 0,
       .key          = B_C,
       .value        = "}",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_V = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_V,
       .value        = "V",
};


const PROGMEM dv_node_t dvnode_B_U_B_B = {
       .parent       = &dvnode_B_U,
       .children     = NULL,
       .children_num = 0,
       .key          = B_B,
       .value        = "-",
};


const PROGMEM dv_node_t dvnode_B_Q = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Q,
       .value        = "q",
};

const dv_node_t* dvnode_B_LS2_B_RS2_children[30] = {
	&dvnode_B_LS2_B_RS2_B_N,
	&dvnode_B_LS2_B_RS2_B_V,
	&dvnode_B_LS2_B_RS2_B_X,
	&dvnode_B_LS2_B_RS2_B_S,
	&dvnode_B_LS2_B_RS2_B_M,
	&dvnode_B_LS2_B_RS2_B_Y,
	&dvnode_B_LS2_B_RS2_B_K,
	&dvnode_B_LS2_B_RS2_B_QUOT,
	&dvnode_B_LS2_B_RS2_B_Q,
	&dvnode_B_LS2_B_RS2_B_C,
	&dvnode_B_LS2_B_RS2_B_T,
	&dvnode_B_LS2_B_RS2_B_P,
	&dvnode_B_LS2_B_RS2_B_D,
	&dvnode_B_LS2_B_RS2_B_Z,
	&dvnode_B_LS2_B_RS2_B_SCLN,
	&dvnode_B_LS2_B_RS2_B_DOT,
	&dvnode_B_LS2_B_RS2_B_COMM,
	&dvnode_B_LS2_B_RS2_B_J,
	&dvnode_B_LS2_B_RS2_B_G,
	&dvnode_B_LS2_B_RS2_B_W,
	&dvnode_B_LS2_B_RS2_B_U,
	&dvnode_B_LS2_B_RS2_B_R,
	&dvnode_B_LS2_B_RS2_B_B,
	&dvnode_B_LS2_B_RS2_B_A,
	&dvnode_B_LS2_B_RS2_B_L,
	&dvnode_B_LS2_B_RS2_B_E,
	&dvnode_B_LS2_B_RS2_B_H,
	&dvnode_B_LS2_B_RS2_B_I,
	&dvnode_B_LS2_B_RS2_B_O,
	&dvnode_B_LS2_B_RS2_B_F,
};
const PROGMEM dv_node_t dvnode_B_LS2_B_RS2 = {
       .parent       = &dvnode_B_LS2,
       .children     = dvnode_B_LS2_B_RS2_children,
       .children_num = 30,
       .key          = B_RS2,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_Z = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Z,
       .value        = "z",
};


const PROGMEM dv_node_t dvnode_B_E_B_P = {
       .parent       = &dvnode_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "4",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_COMM = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_COMM,
       .value        = SS_LCTL(","),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_QUOT = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_QUOT,
       .value        = SS_LSFT(SS_LCTL("'")),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_T = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_T,
       .value        = SS_LCTL("t"),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_R = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_R,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_T_B_G = {
       .parent       = &dvnode_B_T,
       .children     = NULL,
       .children_num = 0,
       .key          = B_G,
       .value        = "7",
};


const PROGMEM dv_node_t dvnode_B_E_B_DOT = {
       .parent       = &dvnode_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_DOT,
       .value        = "3",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_J = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = SS_LCTL("j"),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_E = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_E,
       .value        = SS_LSFT(SS_LCTL("e")),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_H = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "H",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_B = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_B,
       .value        = SS_LSFT(SS_LCTL("b")),
};


const PROGMEM dv_node_t dvnode_B_J_B_W = {
       .parent       = &dvnode_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_W,
       .value        = SS_TAP(X_TAB),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_E_B_N = {
       .parent       = &dvnode_B_LS2_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = SS_LCTL("^"),
};


const PROGMEM dv_node_t dvnode_B_LS2_B_X = {
       .parent       = &dvnode_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_X,
       .value        = SS_LCTL("x"),
};


const PROGMEM dv_node_t dvnode_B_RS2_B_J = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "J",
};


const PROGMEM dv_node_t dvnode_B_U_B_N = {
       .parent       = &dvnode_B_U,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "^",
};


const PROGMEM dv_node_t dvnode_B_E_B_COMM = {
       .parent       = &dvnode_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_COMM,
       .value        = "2",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_P = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "P",
};

const dv_node_t* dvnode_B_LS2_children[31] = {
	&dvnode_B_LS2_B_U,
	&dvnode_B_LS2_B_DOT,
	&dvnode_B_LS2_B_RS2,
	&dvnode_B_LS2_B_R,
	&dvnode_B_LS2_B_E,
	&dvnode_B_LS2_B_COMM,
	&dvnode_B_LS2_B_J,
	&dvnode_B_LS2_B_B,
	&dvnode_B_LS2_B_A,
	&dvnode_B_LS2_B_L,
	&dvnode_B_LS2_B_H,
	&dvnode_B_LS2_B_I,
	&dvnode_B_LS2_B_G,
	&dvnode_B_LS2_B_W,
	&dvnode_B_LS2_B_N,
	&dvnode_B_LS2_B_X,
	&dvnode_B_LS2_B_O,
	&dvnode_B_LS2_B_F,
	&dvnode_B_LS2_B_Y,
	&dvnode_B_LS2_B_K,
	&dvnode_B_LS2_B_V,
	&dvnode_B_LS2_B_Q,
	&dvnode_B_LS2_B_T,
	&dvnode_B_LS2_B_P,
	&dvnode_B_LS2_B_S,
	&dvnode_B_LS2_B_M,
	&dvnode_B_LS2_B_QUOT,
	&dvnode_B_LS2_B_C,
	&dvnode_B_LS2_B_D,
	&dvnode_B_LS2_B_Z,
	&dvnode_B_LS2_B_SCLN,
};
const PROGMEM dv_node_t dvnode_B_LS2 = {
       .parent       = &dvnode_root,
       .children     = dvnode_B_LS2_children,
       .children_num = 31,
       .key          = B_LS2,
       .value        = " ",
};


const PROGMEM dv_node_t dvnode_B_LS2_B_RS2_B_L = {
       .parent       = &dvnode_B_LS2_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = SS_LSFT(SS_LCTL("l")),
};


const PROGMEM dv_node_t dvnode_B_L = {
       .parent       = &dvnode_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = "l",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_LS2_B_I = {
       .parent       = &dvnode_B_RS2_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = NULL,
};


const PROGMEM dv_node_t dvnode_B_T_B_L = {
       .parent       = &dvnode_B_T,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = "0",
};


const PROGMEM dv_node_t dvnode_B_RS2_B_COMM = {
       .parent       = &dvnode_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_COMM,
       .value        = "<",
};
