/**
 * This file is generated by naginata_keydata_gen.py
 * Do not edit this file directly.
 */
#pragma once

#include "naginata.h"

struct naginata_node;

typedef struct naginata_node naginata_node_t;

struct naginata_node {
  const naginata_node_t *parent;                      // 4 bytes
  const naginata_node_t *(*next_node)(uint16_t key);  // 4 bytes
  const uint16_t key;
  const uint8_t bounds;  //  First 4 bits: modifier, Last 4 bits: keycode
                         //  bounds & 0xF0: Enter event end of the string
                         //  bounds & 0x0F: Exit event end of the string
  const uint16_t keys[];
};

const naginata_node_t naginata_node_root;
