/**
 * This file is generated by code generator
 * Do not edit this file directly.
 */
#include "naginata_keydata.h"

#define B_A    0
#define B_B    1
#define B_C    2
#define B_D    3
#define B_E    4
#define B_F    5
#define B_G    6
#define B_H    7
#define B_I    8
#define B_J    9
#define B_K    10
#define B_L    11
#define B_M    12
#define B_N    13
#define B_O    14
#define B_P    15
#define B_Q    16
#define B_R    17
#define B_S    18
#define B_T    19
#define B_U    20
#define B_V    21
#define B_W    22
#define B_X    23
#define B_Y    24
#define B_Z    25
#define B_SLSH 26
#define B_COMM 27
#define B_DOT  28
#define B_SCLN 29
#define B_LS1  30
#define B_RS1  31
#define B_LS2  32
#define B_RS2  33
#define B_LS3  34
#define B_RS3  35

const naginata_node_t PROGMEM naginata_node_B_W_B_J_B_P;
const naginata_node_t PROGMEM naginata_node_B_R_B_I;
const naginata_node_t PROGMEM naginata_node_B_I_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_B_B_I;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_L;
const naginata_node_t PROGMEM naginata_node_B_J_B_R_B_H;
const naginata_node_t PROGMEM naginata_node_B_SCLN_B_V_B_N;
const naginata_node_t PROGMEM naginata_node_B_J_B_R_B_I;
const naginata_node_t PROGMEM naginata_node_B_V_B_H_B_K;
const naginata_node_t PROGMEM naginata_node_B_O;
const naginata_node_t PROGMEM naginata_node_B_R_B_J_B_H;
const naginata_node_t PROGMEM naginata_node_B_F_B_L_B_K;
const naginata_node_t PROGMEM naginata_node_B_J_B_G;
const naginata_node_t PROGMEM naginata_node_B_X_B_M_B_P;
const naginata_node_t PROGMEM naginata_node_B_V_B_L_B_O;
const naginata_node_t PROGMEM naginata_node_B_J_B_D_B_L;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_SCLN;
const naginata_node_t PROGMEM naginata_node_B_J_B_X_B_P;
const naginata_node_t PROGMEM naginata_node_B_H_B_V_B_O;
const naginata_node_t PROGMEM naginata_node_B_X_B_J_B_I;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_I;
const naginata_node_t PROGMEM naginata_node_B_J_B_F;
const naginata_node_t PROGMEM naginata_node_B_V_B_SCLN;
const naginata_node_t PROGMEM naginata_node_B_M_B_R_B_O;
const naginata_node_t PROGMEM naginata_node_B_J_B_D;
const naginata_node_t PROGMEM naginata_node_B_DOT_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_H_B_F_B_K;
const naginata_node_t PROGMEM naginata_node_B_J_B_V;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_DOT;
const naginata_node_t PROGMEM naginata_node_B_X_B_H;
const naginata_node_t PROGMEM naginata_node_B_Q_B_H;
const naginata_node_t PROGMEM naginata_node_B_J_B_Z;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_S;
const naginata_node_t PROGMEM naginata_node_B_L_B_F;
const naginata_node_t PROGMEM naginata_node_B_J_B_E_B_K;
const naginata_node_t PROGMEM naginata_node_B_F_B_L;
const naginata_node_t PROGMEM naginata_node_B_H_B_F;
const naginata_node_t PROGMEM naginata_node_B_V_B_L_B_N;
const naginata_node_t PROGMEM naginata_node_B_Q_B_I;
const naginata_node_t PROGMEM naginata_node_B_R_B_M_B_O;
const naginata_node_t PROGMEM naginata_node_B_G_B_M_B_O;
const naginata_node_t PROGMEM naginata_node_B_D_B_P;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_E;
const naginata_node_t PROGMEM naginata_node_B_F_B_L_B_J;
const naginata_node_t PROGMEM naginata_node_B_E_B_M_B_K;
const naginata_node_t PROGMEM naginata_node_B_L_B_F_B_K;
const naginata_node_t PROGMEM naginata_node_B_M_B_X_B_I;
const naginata_node_t PROGMEM naginata_node_B_G_B_J_B_H;
const naginata_node_t PROGMEM naginata_node_B_L_B_V;
const naginata_node_t PROGMEM naginata_node_B_SCLN_B_V_B_L;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_N;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_C;
const naginata_node_t PROGMEM naginata_node_B_Q;
const naginata_node_t PROGMEM naginata_node_B_V_B_SCLN_B_K;
const naginata_node_t PROGMEM naginata_node_B_P;
const naginata_node_t PROGMEM naginata_node_B_H;
const naginata_node_t PROGMEM naginata_node_B_J_B_R_B_O;
const naginata_node_t PROGMEM naginata_node_B_D;
const naginata_node_t PROGMEM naginata_node_B_F_B_U;
const naginata_node_t PROGMEM naginata_node_B_I;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_B;
const naginata_node_t PROGMEM naginata_node_B_R_B_J_B_O;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_D;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_H;
const naginata_node_t PROGMEM naginata_node_B_V;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_U;
const naginata_node_t PROGMEM naginata_node_B_G_B_J;
const naginata_node_t PROGMEM naginata_node_B_K_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_V_B_L;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_M;
const naginata_node_t PROGMEM naginata_node_B_E_B_J;
const naginata_node_t PROGMEM naginata_node_B_M_B_D;
const naginata_node_t PROGMEM naginata_node_B_H_B_F_B_J;
const naginata_node_t PROGMEM naginata_node_B_J_B_X_B_I;
const naginata_node_t PROGMEM naginata_node_B_V_B_SCLN_B_L;
const naginata_node_t PROGMEM naginata_node_B_SCLN_B_V_B_P;
const naginata_node_t PROGMEM naginata_node_B_L_B_F_B_J;
const naginata_node_t PROGMEM naginata_node_B_SCLN;
const naginata_node_t PROGMEM naginata_node_B_M_B_D_B_L;
const naginata_node_t PROGMEM naginata_node_B_B_B_H;
const naginata_node_t PROGMEM naginata_node_B_G_B_H;
const naginata_node_t PROGMEM naginata_node_B_M_B_R;
const naginata_node_t PROGMEM naginata_node_B_J_B_G_B_I;
const naginata_node_t PROGMEM naginata_node_B_M_B_X;
const naginata_node_t PROGMEM naginata_node_B_H_B_F_B_O;
const naginata_node_t PROGMEM naginata_node_B_J_B_G_B_P;
const naginata_node_t PROGMEM naginata_node_B_F_B_H_B_N;
const naginata_node_t PROGMEM naginata_node_B_V_B_L_B_J;
const naginata_node_t PROGMEM naginata_node_B_V_B_H_B_J;
const naginata_node_t PROGMEM naginata_node_B_R_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_J_B_X;
const naginata_node_t PROGMEM naginata_node_B_X;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_D;
const naginata_node_t PROGMEM naginata_node_B_H_B_V_B_J;
const naginata_node_t PROGMEM naginata_node_B_W_B_J_B_I;
const naginata_node_t PROGMEM naginata_node_B_R;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_H;
const naginata_node_t PROGMEM naginata_node_B_W_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_E_B_M;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_J;
const naginata_node_t PROGMEM naginata_node_B_W_B_P;
const naginata_node_t PROGMEM naginata_node_B_Z;
const naginata_node_t PROGMEM naginata_node_B_K_B_V_B_O;
const naginata_node_t PROGMEM naginata_node_B_V_B_H;
const naginata_node_t PROGMEM naginata_node_B_SCLN_B_V;
const naginata_node_t PROGMEM naginata_node_B_J_B_R_B_P;
const naginata_node_t PROGMEM naginata_node_B_X_B_J;
const naginata_node_t PROGMEM naginata_node_B_R_B_J;
const naginata_node_t PROGMEM naginata_node_B_X_B_M_B_H;
const naginata_node_t PROGMEM naginata_node_B_J_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_B;
const naginata_node_t PROGMEM naginata_node_B_J_B_A;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_COMM;
const naginata_node_t PROGMEM naginata_node_B_P_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_R;
const naginata_node_t PROGMEM naginata_node_B_V_B_K_B_O;
const naginata_node_t PROGMEM naginata_node_B_SLSH;
const naginata_node_t PROGMEM naginata_node_B_O_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_J_B_W_B_H;
const naginata_node_t PROGMEM naginata_node_B_U;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_J;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_W;
const naginata_node_t PROGMEM naginata_node_B_E_B_J_B_P;
const naginata_node_t PROGMEM naginata_node_B_E_B_I;
const naginata_node_t PROGMEM naginata_node_B_J_B_W_B_P;
const naginata_node_t PROGMEM naginata_node_B_G_B_J_B_I;
const naginata_node_t PROGMEM naginata_node_B_N_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_V_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_J_B_R;
const naginata_node_t PROGMEM naginata_node_B_RS2;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_K;
const naginata_node_t PROGMEM naginata_node_B_W_B_I;
const naginata_node_t PROGMEM naginata_node_B_M_B_G_B_O;
const naginata_node_t PROGMEM naginata_node_B_SCLN_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_Q_B_P;
const naginata_node_t PROGMEM naginata_node_B_X_B_M;
const naginata_node_t PROGMEM naginata_node_B_X_B_P;
const naginata_node_t PROGMEM naginata_node_B_H_B_V_B_K;
const naginata_node_t PROGMEM naginata_node_B_N;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_F;
const naginata_node_t PROGMEM naginata_node_B_J_B_W_B_I;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_A;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_V;
const naginata_node_t PROGMEM naginata_node_B_J_B_C;
const naginata_node_t PROGMEM naginata_node_B_Q_B_K;
const naginata_node_t PROGMEM naginata_node_B_V_B_H_B_O;
const naginata_node_t PROGMEM naginata_node_B_COMM_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_G_B_J_B_P;
const naginata_node_t PROGMEM naginata_node_B_M_B_E;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_O;
const naginata_node_t PROGMEM naginata_node_B_G_B_P;
const naginata_node_t PROGMEM naginata_node_B_E_B_P;
const naginata_node_t PROGMEM naginata_node_B_L_B_V_B_O;
const naginata_node_t PROGMEM naginata_node_B_X_B_M_B_I;
const naginata_node_t PROGMEM naginata_node_B_E_B_H;
const naginata_node_t PROGMEM naginata_node_B_F_B_SCLN;
const naginata_node_t PROGMEM naginata_node_B_V_B_SCLN_B_P;
const naginata_node_t PROGMEM naginata_node_B_COMM;
const naginata_node_t PROGMEM naginata_node_B_F;
const naginata_node_t PROGMEM naginata_node_B_G_B_J_B_O;
const naginata_node_t PROGMEM naginata_node_B_H_B_V;
const naginata_node_t PROGMEM naginata_node_B_E;
const naginata_node_t PROGMEM naginata_node_B_F_B_L_B_N;
const naginata_node_t PROGMEM naginata_node_B_D_B_I;
const naginata_node_t PROGMEM naginata_node_B_L_B_V_B_K;
const naginata_node_t PROGMEM naginata_node_B_X_B_I;
const naginata_node_t PROGMEM naginata_node_B_F_B_G;
const naginata_node_t PROGMEM naginata_node_B_J_B_W;
const naginata_node_t PROGMEM naginata_node_B_F_B_P;
const naginata_node_t PROGMEM naginata_node_B_G_B_F;
const naginata_node_t PROGMEM naginata_node_B_V_B_K;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_F;
const naginata_node_t PROGMEM naginata_node_B_A_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_M_B_X_B_H;
const naginata_node_t PROGMEM naginata_node_B_C;
const naginata_node_t PROGMEM naginata_node_B_L_B_V_B_N;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_K;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_R;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_SCLN;
const naginata_node_t PROGMEM naginata_node_B_M_B_E_B_P;
const naginata_node_t PROGMEM naginata_node_B_G_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_DOT;
const naginata_node_t PROGMEM naginata_node_B_L_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_S;
const naginata_node_t PROGMEM naginata_node_B_G_B_M;
const naginata_node_t PROGMEM naginata_node_B_L_B_F_B_O;
const naginata_node_t PROGMEM naginata_node_B_V_B_P;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_B;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_A;
const naginata_node_t PROGMEM naginata_node_B_M_B_X_B_P;
const naginata_node_t PROGMEM naginata_node_B_J_B_X_B_H;
const naginata_node_t PROGMEM naginata_node_B_K_B_V;
const naginata_node_t PROGMEM naginata_node_B_M_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_K;
const naginata_node_t PROGMEM naginata_node_B_F_B_H_B_J;
const naginata_node_t PROGMEM naginata_node_B_U_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_DOT;
const naginata_node_t PROGMEM naginata_node_B_F_B_L_B_P;
const naginata_node_t PROGMEM naginata_node_B_B_B_P;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_G;
const naginata_node_t PROGMEM naginata_node_B_Q_B_N;
const naginata_node_t PROGMEM naginata_node_B_R_B_P;
const naginata_node_t PROGMEM naginata_node_B_F_B_H_B_O;
const naginata_node_t PROGMEM naginata_node_B_F_B_L_B_O;
const naginata_node_t PROGMEM naginata_node_B_D_B_H;
const naginata_node_t PROGMEM naginata_node_B_M_B_Z;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_COMM;
const naginata_node_t PROGMEM naginata_node_B_J_B_E;
const naginata_node_t PROGMEM naginata_node_B_V_B_H_B_N;
const naginata_node_t PROGMEM naginata_node_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_X_B_J_B_P;
const naginata_node_t PROGMEM naginata_node_B_D_B_J;
const naginata_node_t PROGMEM naginata_node_B_M;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_W;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_N;
const naginata_node_t PROGMEM naginata_node_B_V_B_SCLN_B_J;
const naginata_node_t PROGMEM naginata_node_B_J_B_B;
const naginata_node_t PROGMEM naginata_node_B_G_B_I;
const naginata_node_t PROGMEM naginata_node_B_L_B_F_B_P;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_O;
const naginata_node_t PROGMEM naginata_node_B_M_B_E_B_K;
const naginata_node_t PROGMEM naginata_node_B_H_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_E_B_J_B_K;
const naginata_node_t PROGMEM naginata_node_B_J_B_S;
const naginata_node_t PROGMEM naginata_node_B_L_B_F_B_N;
const naginata_node_t PROGMEM naginata_node_B_F_B_O;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_G;
const naginata_node_t PROGMEM naginata_node_B_D_B_M_B_L;
const naginata_node_t PROGMEM naginata_node_B_D_B_J_B_L;
const naginata_node_t PROGMEM naginata_node_B_G;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_E;
const naginata_node_t PROGMEM naginata_node_B_D_B_M;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_M;
const naginata_node_t PROGMEM naginata_node_B_Q_B_L;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_P;
const naginata_node_t PROGMEM naginata_node_B_E_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_V_B_SCLN_B_N;
const naginata_node_t PROGMEM naginata_node_B_F_B_H_B_K;
const naginata_node_t PROGMEM naginata_node_B_R_B_M;
const naginata_node_t PROGMEM naginata_node_B_F_B_N;
const naginata_node_t PROGMEM naginata_node_B_A;
const naginata_node_t PROGMEM naginata_node_B_V_B_L_B_K;
const naginata_node_t PROGMEM naginata_node_B_R_B_J_B_I;
const naginata_node_t PROGMEM naginata_node_B_L_B_V_B_J;
const naginata_node_t PROGMEM naginata_node_B_F_B_H;
const naginata_node_t PROGMEM naginata_node_B_SCLN_B_V_B_J;
const naginata_node_t PROGMEM naginata_node_B_C_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_B_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_I;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_S;
const naginata_node_t PROGMEM naginata_node_B_RS2_B_V;
const naginata_node_t PROGMEM naginata_node_B_W_B_J;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_U;
const naginata_node_t PROGMEM naginata_node_B_W;
const naginata_node_t PROGMEM naginata_node_B_X_B_J_B_H;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_C;
const naginata_node_t PROGMEM naginata_node_B_R_B_H;
const naginata_node_t PROGMEM naginata_node_B_SCLN_B_V_B_K;
const naginata_node_t PROGMEM naginata_node_B_M_B_G;
const naginata_node_t PROGMEM naginata_node_B_J_B_E_B_P;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_L;
const naginata_node_t PROGMEM naginata_node_B_J_B_G_B_O;
const naginata_node_t PROGMEM naginata_node_B_Q_B_O;
const naginata_node_t PROGMEM naginata_node_B_Q_B_J;
const naginata_node_t PROGMEM naginata_node_B_S_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_E_B_M_B_P;
const naginata_node_t PROGMEM naginata_node_B_D_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_H_B_F_B_N;
const naginata_node_t PROGMEM naginata_node_B_H_B_V_B_N;
const naginata_node_t PROGMEM naginata_node_B_J;
const naginata_node_t PROGMEM naginata_node_B_M_B_C;
const naginata_node_t PROGMEM naginata_node_B_LS2_B_P;
const naginata_node_t PROGMEM naginata_node_B_R_B_J_B_P;
const naginata_node_t PROGMEM naginata_node_B_J_B_G_B_H;
const naginata_node_t PROGMEM naginata_node_B_F_B_LS2;
const naginata_node_t PROGMEM naginata_node_B_L;
const naginata_node_t PROGMEM naginata_node_B_W_B_J_B_H;
const naginata_node_t PROGMEM naginata_node_B_W_B_H;


const PROGMEM naginata_node_t naginata_node_B_R_B_J_B_O = {
       .parent       = &naginata_node_B_R_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "zye",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_R_B_H = {
       .parent       = &naginata_node_B_J_B_R,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "zya",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_R = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_R,
       .value        = "ne",
};

const naginata_node_t* naginata_node_B_J_B_R_children[4] = {
	&naginata_node_B_J_B_R_B_I,
	&naginata_node_B_J_B_R_B_P,
	&naginata_node_B_J_B_R_B_H,
	&naginata_node_B_J_B_R_B_O,
};
const PROGMEM naginata_node_t naginata_node_B_J_B_R = {
       .parent       = &naginata_node_B_J,
       .children     = naginata_node_B_J_B_R_children,
       .children_num = 4,
       .key          = B_R,
       .value        = "zi",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_SCLN_B_K = {
       .parent       = &naginata_node_B_V_B_SCLN,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "fi",
};


const PROGMEM naginata_node_t naginata_node_B_Q_B_J = {
       .parent       = &naginata_node_B_Q,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "xa",
};


const PROGMEM naginata_node_t naginata_node_B_Q_B_L = {
       .parent       = &naginata_node_B_Q,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = "xu",
};


const PROGMEM naginata_node_t naginata_node_B_O_B_LS2 = {
       .parent       = &naginata_node_B_O,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "e",
};


const PROGMEM naginata_node_t naginata_node_B_W_B_H = {
       .parent       = &naginata_node_B_W,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "kya",
};


const PROGMEM naginata_node_t naginata_node_B_W_B_I = {
       .parent       = &naginata_node_B_W,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "kyo",
};


const PROGMEM naginata_node_t naginata_node_B_F_B_G = {
       .parent       = &naginata_node_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_G,
       .value        = "dvo",
};


const PROGMEM naginata_node_t naginata_node_B_L_B_F_B_J = {
       .parent       = &naginata_node_B_L_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "va",
};


const PROGMEM naginata_node_t naginata_node_B_E_B_J_B_P = {
       .parent       = &naginata_node_B_E_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "dhu",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_C = {
       .parent       = &naginata_node_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_C,
       .value        = "ba",
};


const PROGMEM naginata_node_t naginata_node_B_SCLN_B_V_B_P = {
       .parent       = &naginata_node_B_SCLN_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "fyu",
};


const PROGMEM naginata_node_t naginata_node_B_K_B_LS2 = {
       .parent       = &naginata_node_B_K,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "mo",
};

const naginata_node_t* naginata_node_B_RS2_children[24] = {
	&naginata_node_B_RS2_B_W,
	&naginata_node_B_RS2_B_E,
	&naginata_node_B_RS2_B_R,
	&naginata_node_B_RS2_B_U,
	&naginata_node_B_RS2_B_I,
	&naginata_node_B_RS2_B_O,
	&naginata_node_B_RS2_B_P,
	&naginata_node_B_RS2_B_A,
	&naginata_node_B_RS2_B_S,
	&naginata_node_B_RS2_B_D,
	&naginata_node_B_RS2_B_F,
	&naginata_node_B_RS2_B_G,
	&naginata_node_B_RS2_B_H,
	&naginata_node_B_RS2_B_J,
	&naginata_node_B_RS2_B_K,
	&naginata_node_B_RS2_B_L,
	&naginata_node_B_RS2_B_SCLN,
	&naginata_node_B_RS2_B_C,
	&naginata_node_B_RS2_B_V,
	&naginata_node_B_RS2_B_B,
	&naginata_node_B_RS2_B_N,
	&naginata_node_B_RS2_B_M,
	&naginata_node_B_RS2_B_COMM,
	&naginata_node_B_RS2_B_DOT,
};
const PROGMEM naginata_node_t naginata_node_B_RS2 = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_RS2_children,
       .children_num = 24,
       .key          = B_RS2,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_G_B_P = {
       .parent       = &naginata_node_B_G,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "tyu",
};


const PROGMEM naginata_node_t naginata_node_B_E_B_M_B_K = {
       .parent       = &naginata_node_B_E_B_M,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "thi",
};


const PROGMEM naginata_node_t naginata_node_B_F_B_LS2 = {
       .parent       = &naginata_node_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "ma",
};


const PROGMEM naginata_node_t naginata_node_B_L_B_V_B_J = {
       .parent       = &naginata_node_B_L_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "tsa",
};

const naginata_node_t* naginata_node_B_V_children[6] = {
	&naginata_node_B_V_B_LS2,
	&naginata_node_B_V_B_P,
	&naginata_node_B_V_B_SCLN,
	&naginata_node_B_V_B_K,
	&naginata_node_B_V_B_L,
	&naginata_node_B_V_B_H,
};
const PROGMEM naginata_node_t naginata_node_B_V = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_V_children,
       .children_num = 6,
       .key          = B_V,
       .value        = "ko",
};

const naginata_node_t* naginata_node_B_H_children[3] = {
	&naginata_node_B_H_B_LS2,
	&naginata_node_B_H_B_F,
	&naginata_node_B_H_B_V,
};
const PROGMEM naginata_node_t naginata_node_B_H = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_H_children,
       .children_num = 3,
       .key          = B_H,
       .value        = "ku",
};


const PROGMEM naginata_node_t naginata_node_B_M_B_X_B_I = {
       .parent       = &naginata_node_B_M_B_X,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "pyo",
};

const naginata_node_t* naginata_node_B_D_children[6] = {
	&naginata_node_B_D_B_LS2,
	&naginata_node_B_D_B_I,
	&naginata_node_B_D_B_P,
	&naginata_node_B_D_B_H,
	&naginata_node_B_D_B_M,
	&naginata_node_B_D_B_J,
};
const PROGMEM naginata_node_t naginata_node_B_D = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_D_children,
       .children_num = 6,
       .key          = B_D,
       .value        = "to",
};

const naginata_node_t* naginata_node_B_M_B_R_children[1] = {
	&naginata_node_B_M_B_R_B_O,
};
const PROGMEM naginata_node_t naginata_node_B_M_B_R = {
       .parent       = &naginata_node_B_M,
       .children     = naginata_node_B_M_B_R_children,
       .children_num = 1,
       .key          = B_R,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_J = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "no",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_J = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "no",
};


const PROGMEM naginata_node_t naginata_node_B_H_B_V_B_J = {
       .parent       = &naginata_node_B_H_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "guxa",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_P = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "yu",
};

const naginata_node_t* naginata_node_B_K_children[2] = {
	&naginata_node_B_K_B_LS2,
	&naginata_node_B_K_B_V,
};
const PROGMEM naginata_node_t naginata_node_B_K = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_K_children,
       .children_num = 2,
       .key          = B_K,
       .value        = "i",
};


const PROGMEM naginata_node_t naginata_node_B_W_B_J_B_I = {
       .parent       = &naginata_node_B_W_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "gyo",
};

const naginata_node_t* naginata_node_B_X_B_M_children[3] = {
	&naginata_node_B_X_B_M_B_I,
	&naginata_node_B_X_B_M_B_P,
	&naginata_node_B_X_B_M_B_H,
};
const PROGMEM naginata_node_t naginata_node_B_X_B_M = {
       .parent       = &naginata_node_B_X,
       .children     = naginata_node_B_X_B_M_children,
       .children_num = 3,
       .key          = B_M,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_N = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "o",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_G_B_H = {
       .parent       = &naginata_node_B_J_B_G,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "dya",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_G_B_P = {
       .parent       = &naginata_node_B_J_B_G,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "dyu",
};


const PROGMEM naginata_node_t naginata_node_B_I_B_LS2 = {
       .parent       = &naginata_node_B_I,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "yo",
};


const PROGMEM naginata_node_t naginata_node_B_F_B_H_B_O = {
       .parent       = &naginata_node_B_F_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "kuxe",
};

const naginata_node_t* naginata_node_B_M_B_E_children[2] = {
	&naginata_node_B_M_B_E_B_P,
	&naginata_node_B_M_B_E_B_K,
};
const PROGMEM naginata_node_t naginata_node_B_M_B_E = {
       .parent       = &naginata_node_B_M,
       .children     = naginata_node_B_M_B_E_children,
       .children_num = 2,
       .key          = B_E,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_E = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_E,
       .value        = "ri",
};


const PROGMEM naginata_node_t naginata_node_B_G_B_J_B_H = {
       .parent       = &naginata_node_B_G_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "dya",
};

const naginata_node_t* naginata_node_B_J_B_G_children[4] = {
	&naginata_node_B_J_B_G_B_I,
	&naginata_node_B_J_B_G_B_P,
	&naginata_node_B_J_B_G_B_H,
	&naginata_node_B_J_B_G_B_O,
};
const PROGMEM naginata_node_t naginata_node_B_J_B_G = {
       .parent       = &naginata_node_B_J,
       .children     = naginata_node_B_J_B_G_children,
       .children_num = 4,
       .key          = B_G,
       .value        = "di",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_G = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_G,
       .value        = "ti",
};


const PROGMEM naginata_node_t naginata_node_B_F_B_L_B_K = {
       .parent       = &naginata_node_B_F_B_L,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "vi",
};


const PROGMEM naginata_node_t naginata_node_B_E_B_P = {
       .parent       = &naginata_node_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "ryu",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_S = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_S,
       .value        = "me",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_E_B_K = {
       .parent       = &naginata_node_B_J_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "dhi",
};


const PROGMEM naginata_node_t naginata_node_B_G_B_J_B_O = {
       .parent       = &naginata_node_B_G_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "dye",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_X_B_H = {
       .parent       = &naginata_node_B_J_B_X,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "bya",
};

const naginata_node_t* naginata_node_B_SCLN_children[2] = {
	&naginata_node_B_SCLN_B_LS2,
	&naginata_node_B_SCLN_B_V,
};
const PROGMEM naginata_node_t naginata_node_B_SCLN = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_SCLN_children,
       .children_num = 2,
       .key          = B_SCLN,
       .value        = "-",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_L_B_J = {
       .parent       = &naginata_node_B_V_B_L,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "tsa",
};


const PROGMEM naginata_node_t naginata_node_B_G_B_F = {
       .parent       = &naginata_node_B_G,
       .children     = NULL,
       .children_num = 0,
       .key          = B_F,
       .value        = "dvo",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_W_B_I = {
       .parent       = &naginata_node_B_J_B_W,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "gyo",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_SCLN_B_L = {
       .parent       = &naginata_node_B_V_B_SCLN,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = "fe",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_F = {
       .parent       = &naginata_node_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_F,
       .value        = "ga",
};


const PROGMEM naginata_node_t naginata_node_B_F_B_P = {
       .parent       = &naginata_node_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "be",
};


const PROGMEM naginata_node_t naginata_node_B_M_B_R_B_O = {
       .parent       = &naginata_node_B_M_B_R,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "sye",
};

const naginata_node_t* naginata_node_root_children[30] = {
	&naginata_node_B_W,
	&naginata_node_B_E,
	&naginata_node_B_R,
	&naginata_node_B_U,
	&naginata_node_B_I,
	&naginata_node_B_O,
	&naginata_node_B_P,
	&naginata_node_B_A,
	&naginata_node_B_S,
	&naginata_node_B_D,
	&naginata_node_B_F,
	&naginata_node_B_G,
	&naginata_node_B_H,
	&naginata_node_B_J,
	&naginata_node_B_K,
	&naginata_node_B_L,
	&naginata_node_B_SCLN,
	&naginata_node_B_Z,
	&naginata_node_B_X,
	&naginata_node_B_C,
	&naginata_node_B_V,
	&naginata_node_B_B,
	&naginata_node_B_N,
	&naginata_node_B_M,
	&naginata_node_B_COMM,
	&naginata_node_B_DOT,
	&naginata_node_B_SLSH,
	&naginata_node_B_LS2,
	&naginata_node_B_RS2,
	&naginata_node_B_Q,
};
const PROGMEM naginata_node_t naginata_node_root = {
       .parent       = NULL,
       .children     = naginata_node_root_children,
       .children_num = 30,
       .key          = -1,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_R_B_P = {
       .parent       = &naginata_node_B_R,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "syu",
};


const PROGMEM naginata_node_t naginata_node_B_F_B_L_B_J = {
       .parent       = &naginata_node_B_F_B_L,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "va",
};


const PROGMEM naginata_node_t naginata_node_B_F_B_N = {
       .parent       = &naginata_node_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "da",
};

const naginata_node_t* naginata_node_B_H_B_V_children[4] = {
	&naginata_node_B_H_B_V_B_O,
	&naginata_node_B_H_B_V_B_J,
	&naginata_node_B_H_B_V_B_K,
	&naginata_node_B_H_B_V_B_N,
};
const PROGMEM naginata_node_t naginata_node_B_H_B_V = {
       .parent       = &naginata_node_B_H,
       .children     = naginata_node_B_H_B_V_children,
       .children_num = 4,
       .key          = B_V,
       .value        = NULL,
};

const naginata_node_t* naginata_node_B_L_B_F_children[5] = {
	&naginata_node_B_L_B_F_B_O,
	&naginata_node_B_L_B_F_B_P,
	&naginata_node_B_L_B_F_B_J,
	&naginata_node_B_L_B_F_B_K,
	&naginata_node_B_L_B_F_B_N,
};
const PROGMEM naginata_node_t naginata_node_B_L_B_F = {
       .parent       = &naginata_node_B_L,
       .children     = naginata_node_B_L_B_F_children,
       .children_num = 5,
       .key          = B_F,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_A = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_A,
       .value        = "se",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_S = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_S,
       .value        = "me",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_C = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_C,
       .value        = "wo",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_H_B_N = {
       .parent       = &naginata_node_B_V_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "guxo",
};

const naginata_node_t* naginata_node_B_K_B_V_children[1] = {
	&naginata_node_B_K_B_V_B_O,
};
const PROGMEM naginata_node_t naginata_node_B_K_B_V = {
       .parent       = &naginata_node_B_K,
       .children     = naginata_node_B_K_B_V_children,
       .children_num = 1,
       .key          = B_V,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_V_B_L_B_O = {
       .parent       = &naginata_node_B_V_B_L,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "we",
};

const naginata_node_t* naginata_node_B_SCLN_B_V_children[5] = {
	&naginata_node_B_SCLN_B_V_B_P,
	&naginata_node_B_SCLN_B_V_B_J,
	&naginata_node_B_SCLN_B_V_B_K,
	&naginata_node_B_SCLN_B_V_B_L,
	&naginata_node_B_SCLN_B_V_B_N,
};
const PROGMEM naginata_node_t naginata_node_B_SCLN_B_V = {
       .parent       = &naginata_node_B_SCLN,
       .children     = naginata_node_B_SCLN_B_V_children,
       .children_num = 5,
       .key          = B_V,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_F_B_L_B_P = {
       .parent       = &naginata_node_B_F_B_L,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "vuxyu",
};


const PROGMEM naginata_node_t naginata_node_B_SLSH = {
       .parent       = &naginata_node_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_SLSH,
       .value        = "re",
};


const PROGMEM naginata_node_t naginata_node_B_L_B_F_B_K = {
       .parent       = &naginata_node_B_L_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "vi",
};

const naginata_node_t* naginata_node_B_I_children[1] = {
	&naginata_node_B_I_B_LS2,
};
const PROGMEM naginata_node_t naginata_node_B_I = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_I_children,
       .children_num = 1,
       .key          = B_I,
       .value        = "ru",
};


const PROGMEM naginata_node_t naginata_node_B_E_B_H = {
       .parent       = &naginata_node_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "rya",
};


const PROGMEM naginata_node_t naginata_node_B_D_B_P = {
       .parent       = &naginata_node_B_D,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "nyu",
};

const naginata_node_t* naginata_node_B_R_B_J_children[4] = {
	&naginata_node_B_R_B_J_B_I,
	&naginata_node_B_R_B_J_B_P,
	&naginata_node_B_R_B_J_B_H,
	&naginata_node_B_R_B_J_B_O,
};
const PROGMEM naginata_node_t naginata_node_B_R_B_J = {
       .parent       = &naginata_node_B_R,
       .children     = naginata_node_B_R_B_J_children,
       .children_num = 4,
       .key          = B_J,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_C_B_LS2 = {
       .parent       = &naginata_node_B_C,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "wo",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_W_B_H = {
       .parent       = &naginata_node_B_J_B_W,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "gya",
};

const naginata_node_t* naginata_node_B_G_B_J_children[4] = {
	&naginata_node_B_G_B_J_B_I,
	&naginata_node_B_G_B_J_B_P,
	&naginata_node_B_G_B_J_B_H,
	&naginata_node_B_G_B_J_B_O,
};
const PROGMEM naginata_node_t naginata_node_B_G_B_J = {
       .parent       = &naginata_node_B_G,
       .children     = naginata_node_B_G_B_J_children,
       .children_num = 4,
       .key          = B_J,
       .value        = NULL,
};

const naginata_node_t* naginata_node_B_N_children[1] = {
	&naginata_node_B_N_B_LS2,
};
const PROGMEM naginata_node_t naginata_node_B_N = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_N_children,
       .children_num = 1,
       .key          = B_N,
       .value        = "ta",
};

const naginata_node_t* naginata_node_B_D_B_J_children[1] = {
	&naginata_node_B_D_B_J_B_L,
};
const PROGMEM naginata_node_t naginata_node_B_D_B_J = {
       .parent       = &naginata_node_B_D,
       .children     = naginata_node_B_D_B_J_children,
       .children_num = 1,
       .key          = B_J,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_F_B_O = {
       .parent       = &naginata_node_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "zu",
};


const PROGMEM naginata_node_t naginata_node_B_SCLN_B_LS2 = {
       .parent       = &naginata_node_B_SCLN,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "fu",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_I = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "yo",
};


const PROGMEM naginata_node_t naginata_node_B_H_B_F_B_K = {
       .parent       = &naginata_node_B_H_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "kuxi",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_H_B_K = {
       .parent       = &naginata_node_B_V_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "guxi",
};


const PROGMEM naginata_node_t naginata_node_B_M_B_E_B_P = {
       .parent       = &naginata_node_B_M_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "thu",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_W = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_W,
       .value        = "nu",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_U = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_U,
       .value        = "sa",
};


const PROGMEM naginata_node_t naginata_node_B_M_B_E_B_K = {
       .parent       = &naginata_node_B_M_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "thi",
};


const PROGMEM naginata_node_t naginata_node_B_M_B_G_B_O = {
       .parent       = &naginata_node_B_M_B_G,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "tye",
};


const PROGMEM naginata_node_t naginata_node_B_W_B_J_B_H = {
       .parent       = &naginata_node_B_W_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "gya",
};


const PROGMEM naginata_node_t naginata_node_B_W_B_LS2 = {
       .parent       = &naginata_node_B_W,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "nu",
};


const PROGMEM naginata_node_t naginata_node_B_X_B_P = {
       .parent       = &naginata_node_B_X,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "hyu",
};


const PROGMEM naginata_node_t naginata_node_B_D_B_M_B_L = {
       .parent       = &naginata_node_B_D_B_M,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = "toxu",
};


const PROGMEM naginata_node_t naginata_node_B_L_B_V_B_K = {
       .parent       = &naginata_node_B_L_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "wi",
};


const PROGMEM naginata_node_t naginata_node_B_D_B_I = {
       .parent       = &naginata_node_B_D,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "nyo",
};


const PROGMEM naginata_node_t naginata_node_B_H_B_F_B_J = {
       .parent       = &naginata_node_B_H_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "kuxa",
};

const naginata_node_t* naginata_node_B_J_children[14] = {
	&naginata_node_B_J_B_LS2,
	&naginata_node_B_J_B_W,
	&naginata_node_B_J_B_E,
	&naginata_node_B_J_B_R,
	&naginata_node_B_J_B_A,
	&naginata_node_B_J_B_S,
	&naginata_node_B_J_B_D,
	&naginata_node_B_J_B_F,
	&naginata_node_B_J_B_G,
	&naginata_node_B_J_B_Z,
	&naginata_node_B_J_B_X,
	&naginata_node_B_J_B_C,
	&naginata_node_B_J_B_V,
	&naginata_node_B_J_B_B,
};
const PROGMEM naginata_node_t naginata_node_B_J = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_J_children,
       .children_num = 14,
       .key          = B_J,
       .value        = "a",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_R = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_R,
       .value        = "ne",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_COMM = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_COMM,
       .value        = "mu",
};


const PROGMEM naginata_node_t naginata_node_B_R_B_LS2 = {
       .parent       = &naginata_node_B_R,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "ne",
};

const naginata_node_t* naginata_node_B_R_children[6] = {
	&naginata_node_B_R_B_LS2,
	&naginata_node_B_R_B_I,
	&naginata_node_B_R_B_P,
	&naginata_node_B_R_B_H,
	&naginata_node_B_R_B_J,
	&naginata_node_B_R_B_M,
};
const PROGMEM naginata_node_t naginata_node_B_R = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_R_children,
       .children_num = 6,
       .key          = B_R,
       .value        = "si",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_Z = {
       .parent       = &naginata_node_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Z,
       .value        = "bo",
};

const naginata_node_t* naginata_node_B_E_B_M_children[2] = {
	&naginata_node_B_E_B_M_B_P,
	&naginata_node_B_E_B_M_B_K,
};
const PROGMEM naginata_node_t naginata_node_B_E_B_M = {
       .parent       = &naginata_node_B_E,
       .children     = naginata_node_B_E_B_M_children,
       .children_num = 2,
       .key          = B_M,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_F_B_L_B_O = {
       .parent       = &naginata_node_B_F_B_L,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "ve",
};

const naginata_node_t* naginata_node_B_J_B_D_children[1] = {
	&naginata_node_B_J_B_D_B_L,
};
const PROGMEM naginata_node_t naginata_node_B_J_B_D = {
       .parent       = &naginata_node_B_J,
       .children     = naginata_node_B_J_B_D_children,
       .children_num = 1,
       .key          = B_D,
       .value        = "do",
};


const PROGMEM naginata_node_t naginata_node_B_F_B_U = {
       .parent       = &naginata_node_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_U,
       .value        = "za",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_P = {
       .parent       = &naginata_node_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "pe",
};


const PROGMEM naginata_node_t naginata_node_B_DOT_B_LS2 = {
       .parent       = &naginata_node_B_DOT,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "wa",
};

const naginata_node_t* naginata_node_B_F_B_H_children[4] = {
	&naginata_node_B_F_B_H_B_O,
	&naginata_node_B_F_B_H_B_J,
	&naginata_node_B_F_B_H_B_K,
	&naginata_node_B_F_B_H_B_N,
};
const PROGMEM naginata_node_t naginata_node_B_F_B_H = {
       .parent       = &naginata_node_B_F,
       .children     = naginata_node_B_F_B_H_children,
       .children_num = 4,
       .key          = B_H,
       .value        = "gu",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_SCLN = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_SCLN,
       .value        = "fu",
};


const PROGMEM naginata_node_t naginata_node_B_Z = {
       .parent       = &naginata_node_root,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Z,
       .value        = "ho",
};


const PROGMEM naginata_node_t naginata_node_B_L_B_F_B_P = {
       .parent       = &naginata_node_B_L_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "vuxyu",
};


const PROGMEM naginata_node_t naginata_node_B_M_B_D_B_L = {
       .parent       = &naginata_node_B_M_B_D,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = "toxu",
};


const PROGMEM naginata_node_t naginata_node_B_G_B_I = {
       .parent       = &naginata_node_B_G,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "tyo",
};

const naginata_node_t* naginata_node_B_W_B_J_children[3] = {
	&naginata_node_B_W_B_J_B_I,
	&naginata_node_B_W_B_J_B_P,
	&naginata_node_B_W_B_J_B_H,
};
const PROGMEM naginata_node_t naginata_node_B_W_B_J = {
       .parent       = &naginata_node_B_W,
       .children     = naginata_node_B_W_B_J_children,
       .children_num = 3,
       .key          = B_J,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_H_B_LS2 = {
       .parent       = &naginata_node_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "ya",
};


const PROGMEM naginata_node_t naginata_node_B_Q_B_K = {
       .parent       = &naginata_node_B_Q,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "xi",
};

const naginata_node_t* naginata_node_B_E_children[6] = {
	&naginata_node_B_E_B_LS2,
	&naginata_node_B_E_B_I,
	&naginata_node_B_E_B_P,
	&naginata_node_B_E_B_H,
	&naginata_node_B_E_B_M,
	&naginata_node_B_E_B_J,
};
const PROGMEM naginata_node_t naginata_node_B_E = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_E_children,
       .children_num = 6,
       .key          = B_E,
       .value        = "te",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_H_B_O = {
       .parent       = &naginata_node_B_V_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "guxe",
};


const PROGMEM naginata_node_t naginata_node_B_H_B_F_B_N = {
       .parent       = &naginata_node_B_H_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "kuxo",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_N = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "o",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_R_B_O = {
       .parent       = &naginata_node_B_J_B_R,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "zye",
};


const PROGMEM naginata_node_t naginata_node_B_M_B_Z = {
       .parent       = &naginata_node_B_M,
       .children     = NULL,
       .children_num = 0,
       .key          = B_Z,
       .value        = "po",
};


const PROGMEM naginata_node_t naginata_node_B_L_B_F_B_N = {
       .parent       = &naginata_node_B_L_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "vo",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_I = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "yo",
};


const PROGMEM naginata_node_t naginata_node_B_G_B_J_B_I = {
       .parent       = &naginata_node_B_G_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "dyo",
};


const PROGMEM naginata_node_t naginata_node_B_E_B_J_B_K = {
       .parent       = &naginata_node_B_E_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "dhi",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_H = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "ya",
};

const naginata_node_t* naginata_node_B_L_children[3] = {
	&naginata_node_B_L_B_LS2,
	&naginata_node_B_L_B_V,
	&naginata_node_B_L_B_F,
};
const PROGMEM naginata_node_t naginata_node_B_L = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_L_children,
       .children_num = 3,
       .key          = B_L,
       .value        = "u",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_R_B_P = {
       .parent       = &naginata_node_B_J_B_R,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "zyu",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_K = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "mo",
};


const PROGMEM naginata_node_t naginata_node_B_B_B_LS2 = {
       .parent       = &naginata_node_B_B,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "mi",
};


const PROGMEM naginata_node_t naginata_node_B_M_B_LS2 = {
       .parent       = &naginata_node_B_M,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = ".",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_W = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_W,
       .value        = "nu",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_B = {
       .parent       = &naginata_node_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_B,
       .value        = "zo",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_COMM = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_COMM,
       .value        = "mu",
};


const PROGMEM naginata_node_t naginata_node_B_R_B_M_B_O = {
       .parent       = &naginata_node_B_R_B_M,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "sye",
};

const naginata_node_t* naginata_node_B_DOT_children[1] = {
	&naginata_node_B_DOT_B_LS2,
};
const PROGMEM naginata_node_t naginata_node_B_DOT = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_DOT_children,
       .children_num = 1,
       .key          = B_DOT,
       .value        = "ra",
};

const naginata_node_t* naginata_node_B_P_children[1] = {
	&naginata_node_B_P_B_LS2,
};
const PROGMEM naginata_node_t naginata_node_B_P = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_P_children,
       .children_num = 1,
       .key          = B_P,
       .value        = "he",
};


const PROGMEM naginata_node_t naginata_node_B_F_B_H_B_N = {
       .parent       = &naginata_node_B_F_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "kuxo",
};


const PROGMEM naginata_node_t naginata_node_B_A_B_LS2 = {
       .parent       = &naginata_node_B_A,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "se",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_SCLN_B_N = {
       .parent       = &naginata_node_B_V_B_SCLN,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "fo",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_F = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_F,
       .value        = "ma",
};

const naginata_node_t* naginata_node_B_G_B_M_children[1] = {
	&naginata_node_B_G_B_M_B_O,
};
const PROGMEM naginata_node_t naginata_node_B_G_B_M = {
       .parent       = &naginata_node_B_G,
       .children     = naginata_node_B_G_B_M_children,
       .children_num = 1,
       .key          = B_M,
       .value        = NULL,
};

const naginata_node_t* naginata_node_B_H_B_F_children[4] = {
	&naginata_node_B_H_B_F_B_O,
	&naginata_node_B_H_B_F_B_J,
	&naginata_node_B_H_B_F_B_K,
	&naginata_node_B_H_B_F_B_N,
};
const PROGMEM naginata_node_t naginata_node_B_H_B_F = {
       .parent       = &naginata_node_B_H,
       .children     = naginata_node_B_H_B_F_children,
       .children_num = 4,
       .key          = B_F,
       .value        = NULL,
};

const naginata_node_t* naginata_node_B_B_children[4] = {
	&naginata_node_B_B_B_LS2,
	&naginata_node_B_B_B_I,
	&naginata_node_B_B_B_P,
	&naginata_node_B_B_B_H,
};
const PROGMEM naginata_node_t naginata_node_B_B = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_B_children,
       .children_num = 4,
       .key          = B_B,
       .value        = "so",
};


const PROGMEM naginata_node_t naginata_node_B_E_B_I = {
       .parent       = &naginata_node_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "ryo",
};


const PROGMEM naginata_node_t naginata_node_B_S_B_LS2 = {
       .parent       = &naginata_node_B_S,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "me",
};

const naginata_node_t* naginata_node_B_COMM_children[1] = {
	&naginata_node_B_COMM_B_LS2,
};
const PROGMEM naginata_node_t naginata_node_B_COMM = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_COMM_children,
       .children_num = 1,
       .key          = B_COMM,
       .value        = "nn",
};


const PROGMEM naginata_node_t naginata_node_B_H_B_F_B_O = {
       .parent       = &naginata_node_B_H_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "kuxe",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_S = {
       .parent       = &naginata_node_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_S,
       .value        = "ge",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_A = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_A,
       .value        = "se",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_F = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_F,
       .value        = "ma",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_D = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_D,
       .value        = "ni",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_B = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_B,
       .value        = "mi",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_U = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_U,
       .value        = "sa",
};


const PROGMEM naginata_node_t naginata_node_B_G_B_J_B_P = {
       .parent       = &naginata_node_B_G_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "dyu",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_SCLN_B_J = {
       .parent       = &naginata_node_B_V_B_SCLN,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "fa",
};


const PROGMEM naginata_node_t naginata_node_B_L_B_V_B_N = {
       .parent       = &naginata_node_B_L_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "uxo",
};


const PROGMEM naginata_node_t naginata_node_B_X_B_J_B_P = {
       .parent       = &naginata_node_B_X_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "byu",
};

const naginata_node_t* naginata_node_B_M_B_D_children[1] = {
	&naginata_node_B_M_B_D_B_L,
};
const PROGMEM naginata_node_t naginata_node_B_M_B_D = {
       .parent       = &naginata_node_B_M,
       .children     = naginata_node_B_M_B_D_children,
       .children_num = 1,
       .key          = B_D,
       .value        = NULL,
};

const naginata_node_t* naginata_node_B_V_B_K_children[1] = {
	&naginata_node_B_V_B_K_B_O,
};
const PROGMEM naginata_node_t naginata_node_B_V_B_K = {
       .parent       = &naginata_node_B_V,
       .children     = naginata_node_B_V_B_K_children,
       .children_num = 1,
       .key          = B_K,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_L_B_F_B_O = {
       .parent       = &naginata_node_B_L_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "ve",
};


const PROGMEM naginata_node_t naginata_node_B_M_B_C = {
       .parent       = &naginata_node_B_M,
       .children     = NULL,
       .children_num = 0,
       .key          = B_C,
       .value        = "pa",
};

const naginata_node_t* naginata_node_B_V_B_SCLN_children[5] = {
	&naginata_node_B_V_B_SCLN_B_P,
	&naginata_node_B_V_B_SCLN_B_J,
	&naginata_node_B_V_B_SCLN_B_K,
	&naginata_node_B_V_B_SCLN_B_L,
	&naginata_node_B_V_B_SCLN_B_N,
};
const PROGMEM naginata_node_t naginata_node_B_V_B_SCLN = {
       .parent       = &naginata_node_B_V,
       .children     = naginata_node_B_V_B_SCLN_children,
       .children_num = 5,
       .key          = B_SCLN,
       .value        = "pu",
};


const PROGMEM naginata_node_t naginata_node_B_H_B_V_B_O = {
       .parent       = &naginata_node_B_H_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "guxe",
};


const PROGMEM naginata_node_t naginata_node_B_L_B_V_B_O = {
       .parent       = &naginata_node_B_L_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "we",
};


const PROGMEM naginata_node_t naginata_node_B_H_B_V_B_K = {
       .parent       = &naginata_node_B_H_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "guxi",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_P = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "yu",
};


const PROGMEM naginata_node_t naginata_node_B_L_B_LS2 = {
       .parent       = &naginata_node_B_L,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "tu",
};

const naginata_node_t* naginata_node_B_L_B_V_children[4] = {
	&naginata_node_B_L_B_V_B_O,
	&naginata_node_B_L_B_V_B_K,
	&naginata_node_B_L_B_V_B_N,
	&naginata_node_B_L_B_V_B_J,
};
const PROGMEM naginata_node_t naginata_node_B_L_B_V = {
       .parent       = &naginata_node_B_L,
       .children     = naginata_node_B_L_B_V_children,
       .children_num = 4,
       .key          = B_V,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_X_B_H = {
       .parent       = &naginata_node_B_X,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "hya",
};


const PROGMEM naginata_node_t naginata_node_B_M_B_X_B_P = {
       .parent       = &naginata_node_B_M_B_X,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "pyu",
};


const PROGMEM naginata_node_t naginata_node_B_M_B_X_B_H = {
       .parent       = &naginata_node_B_M_B_X,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "pya",
};

const naginata_node_t* naginata_node_B_O_children[1] = {
	&naginata_node_B_O_B_LS2,
};
const PROGMEM naginata_node_t naginata_node_B_O = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_O_children,
       .children_num = 1,
       .key          = B_O,
       .value        = "su",
};


const PROGMEM naginata_node_t naginata_node_B_F_B_L_B_N = {
       .parent       = &naginata_node_B_F_B_L,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "vo",
};


const PROGMEM naginata_node_t naginata_node_B_E_B_LS2 = {
       .parent       = &naginata_node_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "ri",
};


const PROGMEM naginata_node_t naginata_node_B_B_B_I = {
       .parent       = &naginata_node_B_B,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "myo",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_H = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "ya",
};


const PROGMEM naginata_node_t naginata_node_B_E_B_M_B_P = {
       .parent       = &naginata_node_B_E_B_M,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "thu",
};


const PROGMEM naginata_node_t naginata_node_B_D_B_H = {
       .parent       = &naginata_node_B_D,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "nya",
};

const naginata_node_t* naginata_node_B_J_B_W_children[3] = {
	&naginata_node_B_J_B_W_B_I,
	&naginata_node_B_J_B_W_B_P,
	&naginata_node_B_J_B_W_B_H,
};
const PROGMEM naginata_node_t naginata_node_B_J_B_W = {
       .parent       = &naginata_node_B_J,
       .children     = naginata_node_B_J_B_W_children,
       .children_num = 3,
       .key          = B_W,
       .value        = "gi",
};


const PROGMEM naginata_node_t naginata_node_B_B_B_H = {
       .parent       = &naginata_node_B_B,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "mya",
};


const PROGMEM naginata_node_t naginata_node_B_G_B_M_B_O = {
       .parent       = &naginata_node_B_G_B_M,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "tye",
};


const PROGMEM naginata_node_t naginata_node_B_U_B_LS2 = {
       .parent       = &naginata_node_B_U,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "sa",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_DOT = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_DOT,
       .value        = "wa",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_K_B_O = {
       .parent       = &naginata_node_B_V_B_K,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "ixe",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_K = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "mo",
};

const naginata_node_t* naginata_node_B_LS2_children[24] = {
	&naginata_node_B_LS2_B_W,
	&naginata_node_B_LS2_B_E,
	&naginata_node_B_LS2_B_R,
	&naginata_node_B_LS2_B_U,
	&naginata_node_B_LS2_B_I,
	&naginata_node_B_LS2_B_O,
	&naginata_node_B_LS2_B_P,
	&naginata_node_B_LS2_B_A,
	&naginata_node_B_LS2_B_S,
	&naginata_node_B_LS2_B_D,
	&naginata_node_B_LS2_B_F,
	&naginata_node_B_LS2_B_G,
	&naginata_node_B_LS2_B_H,
	&naginata_node_B_LS2_B_J,
	&naginata_node_B_LS2_B_K,
	&naginata_node_B_LS2_B_L,
	&naginata_node_B_LS2_B_SCLN,
	&naginata_node_B_LS2_B_C,
	&naginata_node_B_LS2_B_V,
	&naginata_node_B_LS2_B_B,
	&naginata_node_B_LS2_B_N,
	&naginata_node_B_LS2_B_M,
	&naginata_node_B_LS2_B_COMM,
	&naginata_node_B_LS2_B_DOT,
};
const PROGMEM naginata_node_t naginata_node_B_LS2 = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_LS2_children,
       .children_num = 24,
       .key          = B_LS2,
       .value        = NULL,
};

const naginata_node_t* naginata_node_B_C_children[1] = {
	&naginata_node_B_C_B_LS2,
};
const PROGMEM naginata_node_t naginata_node_B_C = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_C_children,
       .children_num = 1,
       .key          = B_C,
       .value        = "ha",
};

const naginata_node_t* naginata_node_B_E_B_J_children[2] = {
	&naginata_node_B_E_B_J_B_P,
	&naginata_node_B_E_B_J_B_K,
};
const PROGMEM naginata_node_t naginata_node_B_E_B_J = {
       .parent       = &naginata_node_B_E,
       .children     = naginata_node_B_E_B_J_children,
       .children_num = 2,
       .key          = B_J,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_G = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_G,
       .value        = "ti",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_V = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_V,
       .value        = ",",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_DOT = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_DOT,
       .value        = "wa",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_A = {
       .parent       = &naginata_node_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_A,
       .value        = "ze",
};


const PROGMEM naginata_node_t naginata_node_B_X_B_I = {
       .parent       = &naginata_node_B_X,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "hyo",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_D = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_D,
       .value        = "ni",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_L = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = "tu",
};


const PROGMEM naginata_node_t naginata_node_B_X_B_M_B_H = {
       .parent       = &naginata_node_B_X_B_M,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "pya",
};


const PROGMEM naginata_node_t naginata_node_B_X_B_J_B_I = {
       .parent       = &naginata_node_B_X_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "byo",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_E = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_E,
       .value        = "ri",
};


const PROGMEM naginata_node_t naginata_node_B_X_B_J_B_H = {
       .parent       = &naginata_node_B_X_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "bya",
};


const PROGMEM naginata_node_t naginata_node_B_Q_B_I = {
       .parent       = &naginata_node_B_Q,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "xyo",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_R_B_I = {
       .parent       = &naginata_node_B_J_B_R,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "zyo",
};


const PROGMEM naginata_node_t naginata_node_B_F_B_H_B_J = {
       .parent       = &naginata_node_B_F_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "kuxa",
};


const PROGMEM naginata_node_t naginata_node_B_SCLN_B_V_B_N = {
       .parent       = &naginata_node_B_SCLN_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "fo",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_LS2 = {
       .parent       = &naginata_node_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = ",",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_M = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_M,
       .value        = ".",
};


const PROGMEM naginata_node_t naginata_node_B_F_B_SCLN = {
       .parent       = &naginata_node_B_F,
       .children     = NULL,
       .children_num = 0,
       .key          = B_SCLN,
       .value        = "bu",
};


const PROGMEM naginata_node_t naginata_node_B_W_B_J_B_P = {
       .parent       = &naginata_node_B_W_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "gyu",
};

const naginata_node_t* naginata_node_B_G_children[7] = {
	&naginata_node_B_G_B_LS2,
	&naginata_node_B_G_B_I,
	&naginata_node_B_G_B_P,
	&naginata_node_B_G_B_H,
	&naginata_node_B_G_B_J,
	&naginata_node_B_G_B_M,
	&naginata_node_B_G_B_F,
};
const PROGMEM naginata_node_t naginata_node_B_G = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_G_children,
       .children_num = 7,
       .key          = B_G,
       .value        = "xtu",
};


const PROGMEM naginata_node_t naginata_node_B_SCLN_B_V_B_K = {
       .parent       = &naginata_node_B_SCLN_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "fi",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_L_B_K = {
       .parent       = &naginata_node_B_V_B_L,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "wi",
};


const PROGMEM naginata_node_t naginata_node_B_SCLN_B_V_B_J = {
       .parent       = &naginata_node_B_SCLN_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "fa",
};

const naginata_node_t* naginata_node_B_Q_children[8] = {
	&naginata_node_B_Q_B_I,
	&naginata_node_B_Q_B_O,
	&naginata_node_B_Q_B_P,
	&naginata_node_B_Q_B_H,
	&naginata_node_B_Q_B_J,
	&naginata_node_B_Q_B_K,
	&naginata_node_B_Q_B_L,
	&naginata_node_B_Q_B_N,
};
const PROGMEM naginata_node_t naginata_node_B_Q = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_Q_children,
       .children_num = 8,
       .key          = B_Q,
       .value        = NULL,
};

const naginata_node_t* naginata_node_B_J_B_E_children[2] = {
	&naginata_node_B_J_B_E_B_P,
	&naginata_node_B_J_B_E_B_K,
};
const PROGMEM naginata_node_t naginata_node_B_J_B_E = {
       .parent       = &naginata_node_B_J,
       .children     = naginata_node_B_J_B_E_children,
       .children_num = 2,
       .key          = B_E,
       .value        = "de",
};


const PROGMEM naginata_node_t naginata_node_B_Q_B_N = {
       .parent       = &naginata_node_B_Q,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "xo",
};


const PROGMEM naginata_node_t naginata_node_B_N_B_LS2 = {
       .parent       = &naginata_node_B_N,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "o",
};


const PROGMEM naginata_node_t naginata_node_B_R_B_H = {
       .parent       = &naginata_node_B_R,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "sya",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_H_B_J = {
       .parent       = &naginata_node_B_V_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_J,
       .value        = "guxa",
};


const PROGMEM naginata_node_t naginata_node_B_K_B_V_B_O = {
       .parent       = &naginata_node_B_K_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "ixe",
};

const naginata_node_t* naginata_node_B_S_children[1] = {
	&naginata_node_B_S_B_LS2,
};
const PROGMEM naginata_node_t naginata_node_B_S = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_S_children,
       .children_num = 1,
       .key          = B_S,
       .value        = "ke",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_X_B_P = {
       .parent       = &naginata_node_B_J_B_X,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "byu",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_O = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "e",
};


const PROGMEM naginata_node_t naginata_node_B_R_B_J_B_I = {
       .parent       = &naginata_node_B_R_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "zyo",
};

const naginata_node_t* naginata_node_B_V_B_L_children[4] = {
	&naginata_node_B_V_B_L_B_O,
	&naginata_node_B_V_B_L_B_K,
	&naginata_node_B_V_B_L_B_N,
	&naginata_node_B_V_B_L_B_J,
};
const PROGMEM naginata_node_t naginata_node_B_V_B_L = {
       .parent       = &naginata_node_B_V,
       .children     = naginata_node_B_V_B_L_children,
       .children_num = 4,
       .key          = B_L,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_R_B_I = {
       .parent       = &naginata_node_B_R,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "syo",
};


const PROGMEM naginata_node_t naginata_node_B_G_B_H = {
       .parent       = &naginata_node_B_G,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "tya",
};


const PROGMEM naginata_node_t naginata_node_B_X_B_M_B_I = {
       .parent       = &naginata_node_B_X_B_M,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "pyo",
};


const PROGMEM naginata_node_t naginata_node_B_Q_B_P = {
       .parent       = &naginata_node_B_Q,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "xyu",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_L = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = "tu",
};


const PROGMEM naginata_node_t naginata_node_B_R_B_J_B_P = {
       .parent       = &naginata_node_B_R_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "zyu",
};


const PROGMEM naginata_node_t naginata_node_B_D_B_LS2 = {
       .parent       = &naginata_node_B_D,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "ni",
};


const PROGMEM naginata_node_t naginata_node_B_COMM_B_LS2 = {
       .parent       = &naginata_node_B_COMM,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "mu",
};


const PROGMEM naginata_node_t naginata_node_B_G_B_LS2 = {
       .parent       = &naginata_node_B_G,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "ti",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_X_B_I = {
       .parent       = &naginata_node_B_J_B_X,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "byo",
};

const naginata_node_t* naginata_node_B_M_B_X_children[3] = {
	&naginata_node_B_M_B_X_B_I,
	&naginata_node_B_M_B_X_B_P,
	&naginata_node_B_M_B_X_B_H,
};
const PROGMEM naginata_node_t naginata_node_B_M_B_X = {
       .parent       = &naginata_node_B_M,
       .children     = naginata_node_B_M_B_X_children,
       .children_num = 3,
       .key          = B_X,
       .value        = "pi",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_D_B_L = {
       .parent       = &naginata_node_B_J_B_D,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = "doxu",
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_V = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_V,
       .value        = ",",
};

const naginata_node_t* naginata_node_B_F_B_L_children[5] = {
	&naginata_node_B_F_B_L_B_O,
	&naginata_node_B_F_B_L_B_P,
	&naginata_node_B_F_B_L_B_J,
	&naginata_node_B_F_B_L_B_K,
	&naginata_node_B_F_B_L_B_N,
};
const PROGMEM naginata_node_t naginata_node_B_F_B_L = {
       .parent       = &naginata_node_B_F,
       .children     = naginata_node_B_F_B_L_children,
       .children_num = 5,
       .key          = B_L,
       .value        = "du",
};

const naginata_node_t* naginata_node_B_J_B_X_children[3] = {
	&naginata_node_B_J_B_X_B_I,
	&naginata_node_B_J_B_X_B_P,
	&naginata_node_B_J_B_X_B_H,
};
const PROGMEM naginata_node_t naginata_node_B_J_B_X = {
       .parent       = &naginata_node_B_J,
       .children     = naginata_node_B_J_B_X_children,
       .children_num = 3,
       .key          = B_X,
       .value        = "bi",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_V = {
       .parent       = &naginata_node_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_V,
       .value        = "go",
};

const naginata_node_t* naginata_node_B_X_B_J_children[3] = {
	&naginata_node_B_X_B_J_B_I,
	&naginata_node_B_X_B_J_B_P,
	&naginata_node_B_X_B_J_B_H,
};
const PROGMEM naginata_node_t naginata_node_B_X_B_J = {
       .parent       = &naginata_node_B_X,
       .children     = naginata_node_B_X_B_J_children,
       .children_num = 3,
       .key          = B_J,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_C = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_C,
       .value        = "wo",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_W_B_P = {
       .parent       = &naginata_node_B_J_B_W,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "gyu",
};

const naginata_node_t* naginata_node_B_V_B_H_children[4] = {
	&naginata_node_B_V_B_H_B_O,
	&naginata_node_B_V_B_H_B_J,
	&naginata_node_B_V_B_H_B_K,
	&naginata_node_B_V_B_H_B_N,
};
const PROGMEM naginata_node_t naginata_node_B_V_B_H = {
       .parent       = &naginata_node_B_V,
       .children     = naginata_node_B_V_B_H_children,
       .children_num = 4,
       .key          = B_H,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_RS2_B_SCLN = {
       .parent       = &naginata_node_B_RS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_SCLN,
       .value        = "fu",
};


const PROGMEM naginata_node_t naginata_node_B_W_B_P = {
       .parent       = &naginata_node_B_W,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "kyu",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_L_B_N = {
       .parent       = &naginata_node_B_V_B_L,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "uxo",
};


const PROGMEM naginata_node_t naginata_node_B_B_B_P = {
       .parent       = &naginata_node_B_B,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "myu",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_G_B_O = {
       .parent       = &naginata_node_B_J_B_G,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "dye",
};

const naginata_node_t* naginata_node_B_M_children[8] = {
	&naginata_node_B_M_B_LS2,
	&naginata_node_B_M_B_Z,
	&naginata_node_B_M_B_X,
	&naginata_node_B_M_B_C,
	&naginata_node_B_M_B_E,
	&naginata_node_B_M_B_D,
	&naginata_node_B_M_B_R,
	&naginata_node_B_M_B_G,
};
const PROGMEM naginata_node_t naginata_node_B_M = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_M_children,
       .children_num = 8,
       .key          = B_M,
       .value        = "na",
};


const PROGMEM naginata_node_t naginata_node_B_SCLN_B_V_B_L = {
       .parent       = &naginata_node_B_SCLN_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = "fe",
};


const PROGMEM naginata_node_t naginata_node_B_X_B_M_B_P = {
       .parent       = &naginata_node_B_X_B_M,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "pyu",
};


const PROGMEM naginata_node_t naginata_node_B_P_B_LS2 = {
       .parent       = &naginata_node_B_P,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "yu",
};


const PROGMEM naginata_node_t naginata_node_B_Q_B_H = {
       .parent       = &naginata_node_B_Q,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "xya",
};

const naginata_node_t* naginata_node_B_F_children[9] = {
	&naginata_node_B_F_B_LS2,
	&naginata_node_B_F_B_U,
	&naginata_node_B_F_B_O,
	&naginata_node_B_F_B_P,
	&naginata_node_B_F_B_H,
	&naginata_node_B_F_B_L,
	&naginata_node_B_F_B_SCLN,
	&naginata_node_B_F_B_N,
	&naginata_node_B_F_B_G,
};
const PROGMEM naginata_node_t naginata_node_B_F = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_F_children,
       .children_num = 9,
       .key          = B_F,
       .value        = "ka",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_B = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_B,
       .value        = "mi",
};

const naginata_node_t* naginata_node_B_R_B_M_children[1] = {
	&naginata_node_B_R_B_M_B_O,
};
const PROGMEM naginata_node_t naginata_node_B_R_B_M = {
       .parent       = &naginata_node_B_R,
       .children     = naginata_node_B_R_B_M_children,
       .children_num = 1,
       .key          = B_M,
       .value        = NULL,
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_O = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "e",
};


const PROGMEM naginata_node_t naginata_node_B_LS2_B_M = {
       .parent       = &naginata_node_B_LS2,
       .children     = NULL,
       .children_num = 0,
       .key          = B_M,
       .value        = ".",
};


const PROGMEM naginata_node_t naginata_node_B_H_B_V_B_N = {
       .parent       = &naginata_node_B_H_B_V,
       .children     = NULL,
       .children_num = 0,
       .key          = B_N,
       .value        = "guxo",
};


const PROGMEM naginata_node_t naginata_node_B_Q_B_O = {
       .parent       = &naginata_node_B_Q,
       .children     = NULL,
       .children_num = 0,
       .key          = B_O,
       .value        = "xe",
};


const PROGMEM naginata_node_t naginata_node_B_F_B_H_B_K = {
       .parent       = &naginata_node_B_F_B_H,
       .children     = NULL,
       .children_num = 0,
       .key          = B_K,
       .value        = "kuxi",
};


const PROGMEM naginata_node_t naginata_node_B_V_B_SCLN_B_P = {
       .parent       = &naginata_node_B_V_B_SCLN,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "fyu",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_LS2 = {
       .parent       = &naginata_node_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_LS2,
       .value        = "no",
};


const PROGMEM naginata_node_t naginata_node_B_R_B_J_B_H = {
       .parent       = &naginata_node_B_R_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_H,
       .value        = "zya",
};

const naginata_node_t* naginata_node_B_U_children[1] = {
	&naginata_node_B_U_B_LS2,
};
const PROGMEM naginata_node_t naginata_node_B_U = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_U_children,
       .children_num = 1,
       .key          = B_U,
       .value        = "sa",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_E_B_P = {
       .parent       = &naginata_node_B_J_B_E,
       .children     = NULL,
       .children_num = 0,
       .key          = B_P,
       .value        = "dhu",
};


const PROGMEM naginata_node_t naginata_node_B_D_B_J_B_L = {
       .parent       = &naginata_node_B_D_B_J,
       .children     = NULL,
       .children_num = 0,
       .key          = B_L,
       .value        = "doxu",
};

const naginata_node_t* naginata_node_B_M_B_G_children[1] = {
	&naginata_node_B_M_B_G_B_O,
};
const PROGMEM naginata_node_t naginata_node_B_M_B_G = {
       .parent       = &naginata_node_B_M,
       .children     = naginata_node_B_M_B_G_children,
       .children_num = 1,
       .key          = B_G,
       .value        = NULL,
};

const naginata_node_t* naginata_node_B_W_children[5] = {
	&naginata_node_B_W_B_LS2,
	&naginata_node_B_W_B_I,
	&naginata_node_B_W_B_P,
	&naginata_node_B_W_B_H,
	&naginata_node_B_W_B_J,
};
const PROGMEM naginata_node_t naginata_node_B_W = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_W_children,
       .children_num = 5,
       .key          = B_W,
       .value        = "ki",
};


const PROGMEM naginata_node_t naginata_node_B_J_B_G_B_I = {
       .parent       = &naginata_node_B_J_B_G,
       .children     = NULL,
       .children_num = 0,
       .key          = B_I,
       .value        = "dyo",
};

const naginata_node_t* naginata_node_B_A_children[1] = {
	&naginata_node_B_A_B_LS2,
};
const PROGMEM naginata_node_t naginata_node_B_A = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_A_children,
       .children_num = 1,
       .key          = B_A,
       .value        = "ro",
};

const naginata_node_t* naginata_node_B_D_B_M_children[1] = {
	&naginata_node_B_D_B_M_B_L,
};
const PROGMEM naginata_node_t naginata_node_B_D_B_M = {
       .parent       = &naginata_node_B_D,
       .children     = naginata_node_B_D_B_M_children,
       .children_num = 1,
       .key          = B_M,
       .value        = NULL,
};

const naginata_node_t* naginata_node_B_X_children[5] = {
	&naginata_node_B_X_B_I,
	&naginata_node_B_X_B_P,
	&naginata_node_B_X_B_H,
	&naginata_node_B_X_B_J,
	&naginata_node_B_X_B_M,
};
const PROGMEM naginata_node_t naginata_node_B_X = {
       .parent       = &naginata_node_root,
       .children     = naginata_node_B_X_children,
       .children_num = 5,
       .key          = B_X,
       .value        = "hi",
};
