/**
 * This file is generated by naginata_keydata_gen.py
 * Do not edit this file directly.
 */
#pragma once

#include "naginata.h"

struct naginata_node;

typedef struct naginata_node naginata_node_t;

struct naginata_node {
  const naginata_node_t *parent;                      // 4 bytes
  const naginata_node_t *(*next_node)(uint16_t key);  // 4 bytes
  const uint16_t key;
  const uint8_t bounds;
  const uint16_t keys[];
};

const naginata_node_t naginata_node_root;
