/**
 * This file is generated by naginata_keydata_gen.py
 * Do not edit this file directly.
 */
#pragma once

#include "naginata.h"

struct naginata_node;

typedef struct naginata_node naginata_node_t;

struct naginata_node {
    const naginata_node_t*  parent;
    const naginata_node_t** children;
    uint8_t                 children_num;
    int8_t                  key;
    const char*             value;
    bool                    reverse;
};

const naginata_node_t naginata_node_root;
